FreeCAD: TechDraw::DrawViewCollectionPy Class Reference
TechDraw::DrawViewCollectionPy Class Reference
The python export class for DrawViewCollection.
#include <DrawViewCollectionPy.h>
Public Types
typedef DrawViewCollection * PointerType
Public Types inherited from TechDraw::DrawViewPy
typedef DrawView * PointerType
Public Types inherited from App::DocumentObjectPy
typedef DocumentObject * PointerType
Public Types inherited from App::ExtensionContainerPy
typedef ExtensionContainer * PointerType
Public Types inherited from App::PropertyContainerPy
typedef PropertyContainer * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
DrawViewCollectionPy (DrawViewCollection *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DrawViewCollection * getDrawViewCollectionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from TechDraw::DrawViewPy
DrawViewPy (DrawView *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DrawView * getDrawViewPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::DocumentObjectPy
DocumentObjectPy (DocumentObject *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * addProperty (PyObject *args)
implementer for the addProperty() method
PyObject * removeProperty (PyObject *args)
implementer for the removeProperty() method
PyObject * supportedProperties (PyObject *args)
implementer for the supportedProperties() method
PyObject * touch (PyObject *args)
implementer for the touch() method
PyObject * purgeTouched (PyObject *args)
implementer for the purgeTouched() method
PyObject * enforceRecompute (PyObject *args)
implementer for the enforceRecompute() method
PyObject * setExpression (PyObject *args)
implementer for the setExpression() method
PyObject * recompute (PyObject *args)
implementer for the recompute() method
PyObject * getParentGroup (PyObject *args)
implementer for the getParentGroup() method
PyObject * getParentGeoFeatureGroup (PyObject *args)
implementer for the getParentGeoFeatureGroup() method
PyObject * getPathsByOutList (PyObject *args)
implementer for the getPathsByOutList() method
Py::List getOutList (void) const
getter for the OutList attribute
Py::List getOutListRecursive (void) const
getter for the OutListRecursive attribute
Py::List getInList (void) const
getter for the InList attribute
Py::List getInListRecursive (void) const
getter for the InListRecursive attribute
Py::String getName (void) const
getter for the Name attribute
Py::Object getDocument (void) const
getter for the Document attribute
Py::List getState (void) const
getter for the State attribute
Py::Object getViewObject (void) const
getter for the ViewObject attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DocumentObject * getDocumentObjectPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::ExtensionContainerPy
ExtensionContainerPy (ExtensionContainer *pcObject, PyTypeObject *T=&Type)
int finalization ()
int initialization ()
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ExtensionContainer * getExtensionContainerPtr (void) const
getter for the object handled by this class
PyObject * addExtension (PyObject *args)
implementer for the addExtension() method
PyObject * hasExtension (PyObject *args)
implementer for the hasExtension() method
Public Member Functions inherited from App::PropertyContainerPy
PropertyContainerPy (PropertyContainer *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getPropertyByName (PyObject *args)
implementer for the getPropertyByName() method
PyObject * getTypeOfProperty (PyObject *args)
implementer for the getTypeOfProperty() method
PyObject * getTypeIdOfProperty (PyObject *args)
implementer for the getTypeIdOfProperty() method
PyObject * setEditorMode (PyObject *args)
implementer for the setEditorMode() method
PyObject * getEditorMode (PyObject *args)
implementer for the getEditorMode() method
PyObject * getGroupOfProperty (PyObject *args)
implementer for the getGroupOfProperty() method
PyObject * getDocumentationOfProperty (PyObject *args)
implementer for the getDocumentationOfProperty() method
PyObject * dumpPropertyContent (PyObject *args, PyObject *kwd)
implementer for the dumpPropertyContent() method
PyObject * restorePropertyContent (PyObject *args)
implementer for the restorePropertyContent() method
Py::List getPropertiesList (void) const
getter for the PropertiesList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PropertyContainer * getPropertyContainerPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from TechDraw::DrawViewPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::DocumentObjectPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_addProperty (PyObject *self, PyObject *args)
callback for the addProperty() method
static PyObject * staticCallback_removeProperty (PyObject *self, PyObject *args)
callback for the removeProperty() method
static PyObject * staticCallback_supportedProperties (PyObject *self, PyObject *args)
callback for the supportedProperties() method
static PyObject * staticCallback_touch (PyObject *self, PyObject *args)
callback for the touch() method
static PyObject * staticCallback_purgeTouched (PyObject *self, PyObject *args)
callback for the purgeTouched() method
static PyObject * staticCallback_enforceRecompute (PyObject *self, PyObject *args)
callback for the enforceRecompute() method
static PyObject * staticCallback_setExpression (PyObject *self, PyObject *args)
callback for the setExpression() method
static PyObject * staticCallback_recompute (PyObject *self, PyObject *args)
callback for the recompute() method
static PyObject * staticCallback_getParentGroup (PyObject *self, PyObject *args)
callback for the getParentGroup() method
static PyObject * staticCallback_getParentGeoFeatureGroup (PyObject *self, PyObject *args)
callback for the getParentGeoFeatureGroup() method
static PyObject * staticCallback_getPathsByOutList (PyObject *self, PyObject *args)
callback for the getPathsByOutList() method
static PyObject * staticCallback_getOutList (PyObject *self, void *closure)
getter callback for the OutList attribute
static int staticCallback_setOutList (PyObject *self, PyObject *value, void *closure)
setter callback for the OutList attribute
static PyObject * staticCallback_getOutListRecursive (PyObject *self, void *closure)
getter callback for the OutListRecursive attribute
static int staticCallback_setOutListRecursive (PyObject *self, PyObject *value, void *closure)
setter callback for the OutListRecursive attribute
static PyObject * staticCallback_getInList (PyObject *self, void *closure)
getter callback for the InList attribute
static int staticCallback_setInList (PyObject *self, PyObject *value, void *closure)
setter callback for the InList attribute
static PyObject * staticCallback_getInListRecursive (PyObject *self, void *closure)
getter callback for the InListRecursive attribute
static int staticCallback_setInListRecursive (PyObject *self, PyObject *value, void *closure)
setter callback for the InListRecursive attribute
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getDocument (PyObject *self, void *closure)
getter callback for the Document attribute
static int staticCallback_setDocument (PyObject *self, PyObject *value, void *closure)
setter callback for the Document attribute
static PyObject * staticCallback_getState (PyObject *self, void *closure)
getter callback for the State attribute
static int staticCallback_setState (PyObject *self, PyObject *value, void *closure)
setter callback for the State attribute
static PyObject * staticCallback_getViewObject (PyObject *self, void *closure)
getter callback for the ViewObject attribute
static int staticCallback_setViewObject (PyObject *self, PyObject *value, void *closure)
setter callback for the ViewObject attribute
Static Public Member Functions inherited from App::ExtensionContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_addExtension (PyObject *self, PyObject *args)
callback for the addExtension() method
static PyObject * staticCallback_hasExtension (PyObject *self, PyObject *args)
callback for the hasExtension() method
Static Public Member Functions inherited from App::PropertyContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getPropertyByName (PyObject *self, PyObject *args)
callback for the getPropertyByName() method
static PyObject * staticCallback_getTypeOfProperty (PyObject *self, PyObject *args)
callback for the getTypeOfProperty() method
static PyObject * staticCallback_getTypeIdOfProperty (PyObject *self, PyObject *args)
callback for the getTypeIdOfProperty() method
static PyObject * staticCallback_setEditorMode (PyObject *self, PyObject *args)
callback for the setEditorMode() method
static PyObject * staticCallback_getEditorMode (PyObject *self, PyObject *args)
callback for the getEditorMode() method
static PyObject * staticCallback_getGroupOfProperty (PyObject *self, PyObject *args)
callback for the getGroupOfProperty() method
static PyObject * staticCallback_getDocumentationOfProperty (PyObject *self, PyObject *args)
callback for the getDocumentationOfProperty() method
static PyObject * staticCallback_dumpPropertyContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpPropertyContent() method
static PyObject * staticCallback_restorePropertyContent (PyObject *self, PyObject *args)
callback for the restorePropertyContent() method
static PyObject * staticCallback_getPropertiesList (PyObject *self, void *closure)
getter callback for the PropertiesList attribute
static int staticCallback_setPropertiesList (PyObject *self, PyObject *value, void *closure)
setter callback for the PropertiesList attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of DrawViewCollectionPy.
static PyMethodDef Methods []
Methods structure of DrawViewCollectionPy.
static PyTypeObject Type
Type structure of DrawViewCollectionPy.
Static Public Attributes inherited from TechDraw::DrawViewPy
static PyGetSetDef GetterSetter []
Attribute structure of DrawViewPy.
static PyMethodDef Methods []
Methods structure of DrawViewPy.
static PyTypeObject Type
Type structure of DrawViewPy.
Static Public Attributes inherited from App::DocumentObjectPy
static PyGetSetDef GetterSetter []
Attribute structure of DocumentObjectPy.
static PyMethodDef Methods []
Methods structure of DocumentObjectPy.
static PyTypeObject Type
Type structure of DocumentObjectPy.
Static Public Attributes inherited from App::ExtensionContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionContainerPy.
static PyMethodDef Methods []
Methods structure of ExtensionContainerPy.
static PyTypeObject Type
Type structure of ExtensionContainerPy.
Static Public Attributes inherited from App::PropertyContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of PropertyContainerPy.
static PyMethodDef Methods []
Methods structure of PropertyContainerPy.
static PyTypeObject Type
Type structure of PropertyContainerPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~DrawViewCollectionPy ()
Protected Member Functions inherited from TechDraw::DrawViewPy
~DrawViewPy ()
Protected Member Functions inherited from App::DocumentObjectPy
~DocumentObjectPy ()
Protected Member Functions inherited from App::ExtensionContainerPy
~ExtensionContainerPy ()
Protected Member Functions inherited from App::PropertyContainerPy
~PropertyContainerPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * addView (PyObject *args)
implementer for the addView() method
PyObject * removeView (PyObject *args)
implementer for the removeView() method
static PyObject * staticCallback_addView (PyObject *self, PyObject *args)
callback for the addView() method
static PyObject * staticCallback_removeView (PyObject *self, PyObject *args)
callback for the removeView() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for DrawViewCollection.
Member Typedef Documentation
PointerType
typedef DrawViewCollection* TechDraw::DrawViewCollectionPy::PointerType
Constructor & Destructor Documentation
~DrawViewCollectionPy()
DrawViewCollectionPy::~DrawViewCollectionPy () protected
DrawViewCollectionPy()
DrawViewCollectionPy::DrawViewCollectionPy (DrawViewCollection * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
addView()
PyObject * DrawViewCollectionPy::addView (PyObject * args)
implementer for the addView() method
References TechDraw::DrawViewCollection::addView(), getDrawViewCollectionPtr(), TechDraw::DrawViewPy::getDrawViewPtr(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_addView().
getCustomAttributes()
PyObject * DrawViewCollectionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDrawViewCollectionPtr()
DrawViewCollection * DrawViewCollectionPy::getDrawViewCollectionPtr (void) const
getter for the object handled by this class
Referenced by addView(), and removeView().
GetType()
virtual PyTypeObject* TechDraw::DrawViewCollectionPy::GetType (void) virtual
Reimplemented from TechDraw::DrawViewPy.
Reimplemented in TechDraw::DrawProjGroupPy.
PyInit()
int DrawViewCollectionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from TechDraw::DrawViewPy.
Reimplemented in TechDraw::DrawProjGroupPy.
PyMake()
PyObject * DrawViewCollectionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
removeView()
PyObject * DrawViewCollectionPy::removeView (PyObject * args)
implementer for the removeView() method
References getDrawViewCollectionPtr(), TechDraw::DrawViewPy::getDrawViewPtr(), TechDraw::DrawViewCollection::removeView(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_removeView().
representation()
std::string DrawViewCollectionPy::representation (void) const
Referenced by config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr2(), config_control_design.degenerate_pcurve::wr2(), automotive_design.pcurve::wr2(), and automotive_design.degenerate_pcurve::wr2().
setCustomAttributes()
int DrawViewCollectionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_addView()
PyObject * DrawViewCollectionPy::staticCallback_addView (PyObject * self, PyObject * args) static
callback for the addView() method
References addView(), Base::BaseExceptionFreeCADError, Base::Console(), Base::ConsoleSingleton::Error(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_removeView()
PyObject * DrawViewCollectionPy::staticCallback_removeView (PyObject * self, PyObject * args) static
callback for the removeView() method
References Base::BaseExceptionFreeCADError, Base::Console(), Base::ConsoleSingleton::Error(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeView(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef DrawViewCollectionPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of DrawViewCollectionPy.
Methods
PyMethodDef DrawViewCollectionPy::Methods static
Initial value:
= {
    {"addView",
        reinterpret_cast<PyCFunction>( staticCallback_addView ),
        METH_VARARGS,
        "addView(DrawView object) - Add a new View to this Group. Returns count of views."
    },
    {"removeView",
        reinterpret_cast<PyCFunction>( staticCallback_removeView ),
        METH_VARARGS,
        "removeView(DrawView object) - Remove specified Viewfrom this Group. Returns count of views in Group."
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of DrawViewCollectionPy.
Type
PyTypeObject DrawViewCollectionPy::Type static
Type structure of DrawViewCollectionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchSchedule.CommandArchSchedule::IsActive(), and ArchAxis.CommandArchGrid::IsActive().
The documentation for this class was generated from the following files:
build/webdoc/src/Mod/TechDraw/App/DrawViewCollectionPy.h
src/Mod/TechDraw/App/DrawViewCollectionPyImp.cpp
build/webdoc/src/Mod/TechDraw/App/DrawViewCollectionPy.cpp