FreeCAD: Part::GeometryExtension Class Reference
Part::GeometryExtension Class Reference abstract
#include <GeometryExtension.h>
Public Member Functions
virtual std::unique_ptr< GeometryExtension > copy (void) const =0
virtual unsigned int getMemSize (void) const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
const std::string & getName () const
virtual PyObject * getPyObject (void)=0
This method returns the Python wrapper for a C++ object.
virtual void Restore (Base::XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const =0
This method is used to save properties to an XML document.
void setName (const std::string &str)
virtual ~GeometryExtension ()=default
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
void restoreNameAttribute (Base::XMLReader &)
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
~GeometryExtension()
virtual Part::GeometryExtension::~GeometryExtension () virtual default
GeometryExtension() [1/2]
GeometryExtension::GeometryExtension () protected
GeometryExtension() [2/2]
Part::GeometryExtension::GeometryExtension (const GeometryExtension & obj) protected default
Member Function Documentation
copy()
virtual std::unique_ptr<GeometryExtension> Part::GeometryExtension::copy (void) const pure virtual
Implemented in Sketcher::ExternalGeometryExtension, Part::GeometryDefaultExtension< T >, and Sketcher::SketchGeometryExtension.
getMemSize()
virtual unsigned int Part::GeometryExtension::getMemSize (void) const pure virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Implemented in Sketcher::ExternalGeometryExtension, Part::GeometryDefaultExtension< T >, and Sketcher::SketchGeometryExtension.
getName()
const std::string& Part::GeometryExtension::getName () const
Referenced by Sketcher::SketchGeometryExtension::copy(), Sketcher::ExternalGeometryExtension::copy(), Part::GeometryExtensionPy::getName(), Sketcher::SketchGeometryExtensionPy::representation(), Part::GeometryIntExtensionPy::representation(), Part::GeometryBoolExtensionPy::representation(), Sketcher::ExternalGeometryExtensionPy::representation(), Part::GeometryDoubleExtensionPy::representation(), Part::GeometryStringExtensionPy::representation(), Sketcher::SketchGeometryExtension::Save(), and Sketcher::ExternalGeometryExtension::Save().
getPyObject()
virtual PyObject* Part::GeometryExtension::getPyObject (void) pure virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Implemented in Sketcher::ExternalGeometryExtension, Part::GeometryDefaultExtension< T >, Sketcher::SketchGeometryExtension, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, and Part::GeometryDefaultExtension< T >.
Restore()
virtual void Part::GeometryExtension::Restore (Base::XMLReader &) pure virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Implemented in Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Sketcher::ExternalGeometryExtension, Part::GeometryDefaultExtension< T >, and Sketcher::SketchGeometryExtension.
Referenced by Part::Geometry::Restore().
restoreNameAttribute()
void GeometryExtension::restoreNameAttribute (Base::XMLReader & reader) protected
References Base::XMLReader::getAttribute(), Base::XMLReader::hasAttribute(), and setName().
Referenced by Sketcher::SketchGeometryExtension::Restore(), and Sketcher::ExternalGeometryExtension::Restore().
Save()
virtual void Part::GeometryExtension::Save (Base::Writer &) const pure virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Implemented in Sketcher::ExternalGeometryExtension, Part::GeometryDefaultExtension< T >, and Sketcher::SketchGeometryExtension.
setName()
void Part::GeometryExtension::setName (const std::string & str)
Referenced by Part::GeometryDefaultExtension< T >::GeometryDefaultExtension(), Part::GeometryStringExtensionPy::PyInit(), Part::GeometryIntExtensionPy::PyInit(), Part::GeometryBoolExtensionPy::PyInit(), Part::GeometryDoubleExtensionPy::PyInit(), restoreNameAttribute(), and Part::GeometryExtensionPy::setName().
The documentation for this class was generated from the following files:
src/Mod/Part/App/GeometryExtension.h
src/Mod/Part/App/GeometryExtension.cpp