FreeCAD: PathScripts.post.centroid_post Namespace Reference
PathScripts.post.centroid_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
AXIS_PRECISION
COMMAND_SPACE
COMMENT
CORNER_MAX
CORNER_MIN
FEED_PRECISION
HEADER
LINENR
MACHINE_NAME
MODAL
now
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
POST_OPERATION
POSTAMBLE
PRE_OPERATION
PREAMBLE
pythonopen
SAFETYBLOCK
SHOW_EDITOR
SPINDLE_DECIMALS
TOOL_CHANGE
TOOLRETURN
TOOLTIP
TOOLTIP_ARGS
UNIT_FORMAT
UNITS
ZAXISRETURN
Function Documentation
export()
def PathScripts.post.centroid_post.export (objectslist, filename, argstring)
References PathScripts.post.centroid_post.linenumber(), PathScripts.post.centroid_post.parse(), PathScripts.post.centroid_post.processArguments(), and PathScripts.post.centroid_post.pythonopen.
linenumber()
def PathScripts.post.centroid_post.linenumber ()
Referenced by PathScripts.post.centroid_post.export(), and PathScripts.post.centroid_post.parse().
parse()
def PathScripts.post.centroid_post.parse (pathobj)
References PathScripts.post.centroid_post.linenumber().
Referenced by PathScripts.post.centroid_post.export().
processArguments()
def PathScripts.post.centroid_post.processArguments (argstring)
Referenced by PathScripts.post.centroid_post.export().
Variable Documentation
AXIS_PRECISION
PathScripts.post.centroid_post.AXIS_PRECISION
COMMAND_SPACE
PathScripts.post.centroid_post.COMMAND_SPACE
COMMENT
PathScripts.post.centroid_post.COMMENT
CORNER_MAX
PathScripts.post.centroid_post.CORNER_MAX
CORNER_MIN
PathScripts.post.centroid_post.CORNER_MIN
FEED_PRECISION
PathScripts.post.centroid_post.FEED_PRECISION
HEADER
PathScripts.post.centroid_post.HEADER
LINENR
PathScripts.post.centroid_post.LINENR
MACHINE_NAME
PathScripts.post.centroid_post.MACHINE_NAME
MODAL
PathScripts.post.centroid_post.MODAL
now
PathScripts.post.centroid_post.now
OUTPUT_COMMENTS
PathScripts.post.centroid_post.OUTPUT_COMMENTS
OUTPUT_HEADER
PathScripts.post.centroid_post.OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
PathScripts.post.centroid_post.OUTPUT_LINE_NUMBERS
POST_OPERATION
PathScripts.post.centroid_post.POST_OPERATION
POSTAMBLE
PathScripts.post.centroid_post.POSTAMBLE
PRE_OPERATION
PathScripts.post.centroid_post.PRE_OPERATION
PREAMBLE
PathScripts.post.centroid_post.PREAMBLE
pythonopen
PathScripts.post.centroid_post.pythonopen
Referenced by PathScripts.post.centroid_post.export().
SAFETYBLOCK
PathScripts.post.centroid_post.SAFETYBLOCK
SHOW_EDITOR
PathScripts.post.centroid_post.SHOW_EDITOR
SPINDLE_DECIMALS
PathScripts.post.centroid_post.SPINDLE_DECIMALS
TOOL_CHANGE
PathScripts.post.centroid_post.TOOL_CHANGE
TOOLRETURN
PathScripts.post.centroid_post.TOOLRETURN
TOOLTIP
PathScripts.post.centroid_post.TOOLTIP
TOOLTIP_ARGS
PathScripts.post.centroid_post.TOOLTIP_ARGS
UNIT_FORMAT
PathScripts.post.centroid_post.UNIT_FORMAT
UNITS
PathScripts.post.centroid_post.UNITS
ZAXISRETURN
PathScripts.post.centroid_post.ZAXISRETURN