FreeCAD: ply.lex Namespace Reference
ply.lex Namespace Reference
Classes
class Lexer
class LexerReflect
class LexError
class LexToken
class NullLogger
class PlyLogger
Functions
def func_code (f)
def get_caller_module_dict (levels)
def lex (module=None, object=None, debug=0, optimize=0, lextab="lextab", reflags=0, nowarn=0, outputdir="", debuglog=None, errorlog=None)
def runmain (lexer=None, data=None)
def TOKEN (r)
Variables
StringTypes
Token
Function Documentation
func_code()
def ply.lex.func_code (f)
Referenced by ply.lex.lex(), and ply.lex.LexerReflect.validate_rules().
get_caller_module_dict()
def ply.lex.get_caller_module_dict (levels)
Referenced by ply.lex.lex().
lex()
def ply.lex.lex (module = None, object = None, debug = 0, optimize = 0, lextab = "lextab", reflags = 0, nowarn = 0, outputdir = "", debuglog = None, errorlog = None)
References ply.lex.func_code(), and ply.lex.get_caller_module_dict().
runmain()
def ply.lex.runmain (lexer = None, data = None)
TOKEN()
def ply.lex.TOKEN (r)
Variable Documentation
StringTypes
ply.lex.StringTypes
Token
ply.lex.Token