FreeCAD: femexamples.manager Namespace Reference
femexamples.manager Namespace Reference
Functions
def run_all ()
def run_analysis (doc, base_name, filepath="")
def run_boxanalysisfrequency (solver=None, base_name=None)
def run_boxanalysisstatic (solver=None, base_name=None)
def run_ccx_cantileverfaceload (solver=None, base_name=None)
def run_ccx_cantilevernodeload (solver=None, base_name=None)
def run_ccx_cantileverprescribeddisplacement (solver=None, base_name=None)
def run_constraint_contact_shell_shell (solver=None, base_name=None)
def run_constraint_contact_solid_solid (solver=None, base_name=None)
def run_constraint_tie (solver=None, base_name=None)
def run_material_multiple_twoboxes (solver=None, base_name=None)
def run_material_nl_platewithhole (solver=None, base_name=None)
def run_rcwall2d (solver=None, base_name=None)
def run_thermomech_bimetall (solver=None, base_name=None)
def run_thermomech_flow1d (solver=None, base_name=None)
def run_thermomech_spine (solver=None, base_name=None)
def setup_cantileverhexa20faceload (solver=None, base_name=None)
Function Documentation
run_all()
def femexamples.manager.run_all ()
References femexamples.manager.run_boxanalysisfrequency(), femexamples.manager.run_boxanalysisstatic(), femexamples.manager.run_ccx_cantileverfaceload(), femexamples.manager.run_ccx_cantilevernodeload(), femexamples.manager.run_ccx_cantileverprescribeddisplacement(), femexamples.manager.run_constraint_contact_shell_shell(), femexamples.manager.run_constraint_contact_solid_solid(), femexamples.manager.run_material_multiple_twoboxes(), femexamples.manager.run_material_nl_platewithhole(), femexamples.manager.run_rcwall2d(), femexamples.manager.run_thermomech_bimetall(), femexamples.manager.run_thermomech_flow1d(), and femexamples.manager.run_thermomech_spine().
run_analysis()
def femexamples.manager.run_analysis (doc, base_name, filepath = "")
Referenced by femexamples.manager.run_boxanalysisfrequency(), femexamples.manager.run_boxanalysisstatic(), femexamples.manager.run_ccx_cantileverfaceload(), femexamples.manager.run_ccx_cantilevernodeload(), femexamples.manager.run_ccx_cantileverprescribeddisplacement(), femexamples.manager.run_constraint_contact_shell_shell(), femexamples.manager.run_constraint_contact_solid_solid(), femexamples.manager.run_constraint_tie(), femexamples.manager.run_material_multiple_twoboxes(), femexamples.manager.run_material_nl_platewithhole(), femexamples.manager.run_rcwall2d(), femexamples.manager.run_thermomech_bimetall(), femexamples.manager.run_thermomech_flow1d(), femexamples.manager.run_thermomech_spine(), and femexamples.manager.setup_cantileverhexa20faceload().
run_boxanalysisfrequency()
def femexamples.manager.run_boxanalysisfrequency (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_boxanalysisstatic()
def femexamples.manager.run_boxanalysisstatic (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_ccx_cantileverfaceload()
def femexamples.manager.run_ccx_cantileverfaceload (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_ccx_cantilevernodeload()
def femexamples.manager.run_ccx_cantilevernodeload (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_ccx_cantileverprescribeddisplacement()
def femexamples.manager.run_ccx_cantileverprescribeddisplacement (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_constraint_contact_shell_shell()
def femexamples.manager.run_constraint_contact_shell_shell (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_constraint_contact_solid_solid()
def femexamples.manager.run_constraint_contact_solid_solid (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_constraint_tie()
def femexamples.manager.run_constraint_tie (solver = None, base_name = None)
References femexamples.manager.run_analysis().
run_material_multiple_twoboxes()
def femexamples.manager.run_material_multiple_twoboxes (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_material_nl_platewithhole()
def femexamples.manager.run_material_nl_platewithhole (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_rcwall2d()
def femexamples.manager.run_rcwall2d (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_thermomech_bimetall()
def femexamples.manager.run_thermomech_bimetall (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_thermomech_flow1d()
def femexamples.manager.run_thermomech_flow1d (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
run_thermomech_spine()
def femexamples.manager.run_thermomech_spine (solver = None, base_name = None)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all().
setup_cantileverhexa20faceload()
def femexamples.manager.setup_cantileverhexa20faceload (solver = None, base_name = None)
References femexamples.manager.run_analysis().