FreeCAD: draftguitools.gui_snaps Namespace Reference
draftguitools.gui_snaps Namespace Reference
Classes
class Draft_Snap_Angle
class Draft_Snap_Center
class Draft_Snap_Dimensions
class Draft_Snap_Endpoint
class Draft_Snap_Extension
class Draft_Snap_Grid
class Draft_Snap_Intersection
class Draft_Snap_Lock
class Draft_Snap_Midpoint
class Draft_Snap_Near
class Draft_Snap_Ortho
class Draft_Snap_Parallel
class Draft_Snap_Perpendicular
class Draft_Snap_Special
class Draft_Snap_WorkingPlane
class ShowSnapBar
Functions
def get_snap_statusbar_widget ()
def sync_snap_statusbar_button (button, status)
def sync_snap_toolbar_button (button, status)
Function Documentation
get_snap_statusbar_widget()
def draftguitools.gui_snaps.get_snap_statusbar_widget ()
Return snap statusbar button.
References Gui.getMainWindow().
Referenced by draftguitools.gui_snaps.sync_snap_statusbar_button().
sync_snap_statusbar_button()
def draftguitools.gui_snaps.sync_snap_statusbar_button (button, status)
Set snap statusbar button to given state.
References draftguitools.gui_snaps.get_snap_statusbar_widget().
Referenced by draftguitools.gui_snaps.Draft_Snap_Lock.Activated(), draftguitools.gui_snaps.Draft_Snap_Midpoint.Activated(), draftguitools.gui_snaps.Draft_Snap_Perpendicular.Activated(), draftguitools.gui_snaps.Draft_Snap_Grid.Activated(), draftguitools.gui_snaps.Draft_Snap_Intersection.Activated(), draftguitools.gui_snaps.Draft_Snap_Parallel.Activated(), draftguitools.gui_snaps.Draft_Snap_Endpoint.Activated(), draftguitools.gui_snaps.Draft_Snap_Angle.Activated(), draftguitools.gui_snaps.Draft_Snap_Center.Activated(), draftguitools.gui_snaps.Draft_Snap_Extension.Activated(), draftguitools.gui_snaps.Draft_Snap_Near.Activated(), draftguitools.gui_snaps.Draft_Snap_Ortho.Activated(), draftguitools.gui_snaps.Draft_Snap_Special.Activated(), draftguitools.gui_snaps.Draft_Snap_Dimensions.Activated(), and draftguitools.gui_snaps.Draft_Snap_WorkingPlane.Activated().
sync_snap_toolbar_button()
def draftguitools.gui_snaps.sync_snap_toolbar_button (button, status)
Set snap toolbar button to given state.
Referenced by draftguitools.gui_snaps.Draft_Snap_Lock.Activated(), draftguitools.gui_snaps.Draft_Snap_Midpoint.Activated(), draftguitools.gui_snaps.Draft_Snap_Perpendicular.Activated(), draftguitools.gui_snaps.Draft_Snap_Grid.Activated(), draftguitools.gui_snaps.Draft_Snap_Intersection.Activated(), draftguitools.gui_snaps.Draft_Snap_Parallel.Activated(), draftguitools.gui_snaps.Draft_Snap_Endpoint.Activated(), draftguitools.gui_snaps.Draft_Snap_Angle.Activated(), draftguitools.gui_snaps.Draft_Snap_Center.Activated(), draftguitools.gui_snaps.Draft_Snap_Extension.Activated(), draftguitools.gui_snaps.Draft_Snap_Near.Activated(), draftguitools.gui_snaps.Draft_Snap_Ortho.Activated(), draftguitools.gui_snaps.Draft_Snap_Special.Activated(), draftguitools.gui_snaps.Draft_Snap_Dimensions.Activated(), and draftguitools.gui_snaps.Draft_Snap_WorkingPlane.Activated().