FreeCAD: Gui::Sequencer Class Reference
Gui::Sequencer Class Reference
FreeCAD's progress bar for long operations To see how to use the progress bar have a look at the following examples:
#include <ProgressBar.h>
Public Member Functions
QProgressBar * getProgressBar (QWidget *parent=0)
Returns an instance of the progress bar.
bool isBlocking () const
Returns true if the running sequencer is blocking any user input.
void pause ()
This restores the last overridden cursor and release the keyboard while the progress bar is running.
void resume ()
This sets the wait cursor again and grabs the keyboard.
Public Member Functions inherited from Base::SequencerBase
bool isLocked () const
Returns true if the sequencer was locked, false otherwise.
bool isRunning () const
Returns true if the sequencer is running, otherwise returns false.
bool setLocked (bool bLock)
If bLock is true then the sequencer gets locked.
bool wasCanceled () const
Returns true if the pending operation was canceled.
Static Public Member Functions
static Sequencer * instance ()
Returns the sequencer object.
Static Public Member Functions inherited from Base::SequencerBase
static SequencerBase & Instance ()
Returns the last created sequencer instance.
Protected Member Functions
void nextStep (bool canAbort)
Increase the progress bar.
void resetData ()
Resets the sequencer.
Sequencer ()
Construction.
void setProgress (size_t)
Sets the progress indicator to a certain position.
void setText (const char *pszTxt)
Puts text to the status bar.
void showRemainingTime ()
void startStep ()
Starts the progress bar.
~Sequencer ()
Destruction.
Protected Member Functions inherited from Base::SequencerBase
bool next (bool canAbort=false)
Performs the next step and returns true if the operation is not yet finished.
size_t numberOfSteps () const
Returns the number of steps.
int progressInPercent () const
Returns the current state of progress in percent.
void rejectCancel ()
If you tried to cancel but then decided to continue the operation.
SequencerBase ()
construction
bool start (const char *pszStr, size_t steps)
Starts a new operation, returns false if there is already a pending operation, otherwise it returns true.
bool stop ()
Stops the sequencer if all operations are finished.
void tryToCancel ()
Try to cancel the pending operation(s).
virtual ~SequencerBase ()
Destruction.
Friends
class ProgressBar
Additional Inherited Members
Protected Attributes inherited from Base::SequencerBase
size_t nProgress
Stores the current amount of progress.
size_t nTotalSteps
Stores the total number of steps.
Detailed Description
FreeCAD's progress bar for long operations To see how to use the progress bar have a look at the following examples:
unsigned long steps = ...
Base::SequencerLauncher seq("Starting progress bar", 0);
for (unsigned long i=0; i<steps;i++)
{
  seq.next();
  // do one step of your algorithm
}
The example below shows how to use two nested progresses.
void function1()
{
  unsigned long steps = ...
  Base::SequencerLauncger seq("Starting progress bar", 0);
  for (unsigned long i=0; i<steps;i++)
  {
    seq.next();
    // do one step of your algorithm
  }
}
void function2()
{
  unsigned long steps = ...
  Base::SequencerLauncher seq("Starting progress bar", 0);
  for (unsigned long i=0; i<steps;i++)
  {
    seq.next();
    // do one step of your algorithm calling function1
    function1();
  }
}
If the total number of steps cannot be determined before, use 0 instead of to show just a busy indicator instead of percentage steps.
Author
Werner Mayer
Constructor & Destructor Documentation
Sequencer()
Sequencer::Sequencer () protected
Construction.
References Gui::SequencerPrivate::bar.
~Sequencer()
Sequencer::~Sequencer () protected
Destruction.
Member Function Documentation
getProgressBar()
QProgressBar * Sequencer::getProgressBar (QWidget * parent = 0)
Returns an instance of the progress bar.
It creates one if needed.
Referenced by Gui::MainWindow::MainWindow(), WebGui::BrowserView::onLoadProgress(), and WebGui::BrowserView::onLoadStarted().
instance()
Sequencer * Sequencer::instance (void) static
Returns the sequencer object.
Referenced by Gui::MainWindow::MainWindow(), WebGui::BrowserView::onLoadProgress(), and WebGui::BrowserView::onLoadStarted().
isBlocking()
bool Sequencer::isBlocking () const virtual
Returns true if the running sequencer is blocking any user input.
This might be only of interest of the GUI where the progress bar or dialog is used from a thread. If started from a thread this method should return false, otherwise true. The default implementation always returns true.
Reimplemented from Base::SequencerBase.
nextStep()
void Sequencer::nextStep (bool canAbort) protected virtual
Increase the progress bar.
Reimplemented from Base::SequencerBase.
pause()
void Sequencer::pause () virtual
This restores the last overridden cursor and release the keyboard while the progress bar is running.
This is useful e.g. if a modal dialog appears while a long operation is performed to indicate that the user can click on the dialog. Every pause() must eventually be followed by a corresponding resume().
Reimplemented from Base::SequencerBase.
resetData()
void Sequencer::resetData () protected virtual
Resets the sequencer.
Reimplemented from Base::SequencerBase.
References Gui::getMainWindow(), Gui::MainWindow::setPaneText(), and Gui::MainWindow::showMessage().
Referenced by Gui::ProgressBar::eventFilter().
resume()
void Sequencer::resume () virtual
This sets the wait cursor again and grabs the keyboard.
See also
pause()
Reimplemented from Base::SequencerBase.
setProgress()
void Sequencer::setProgress (size_t step) protected virtual
Sets the progress indicator to a certain position.
Reimplemented from Base::SequencerBase.
setText()
void Sequencer::setText (const char * pszTxt) protected virtual
Puts text to the status bar.
Reimplemented from Base::SequencerBase.
References Gui::getMainWindow(), and Gui::MainWindow::showMessage().
showRemainingTime()
void Sequencer::showRemainingTime () protected
References Gui::getMainWindow(), and Gui::MainWindow::showMessage().
startStep()
void Sequencer::startStep () protected virtual
Starts the progress bar.
Reimplemented from Base::SequencerBase.
Friends And Related Function Documentation
ProgressBar
friend class ProgressBar friend
The documentation for this class was generated from the following files:
src/Gui/ProgressBar.h
src/Gui/ProgressBar.cpp