FreeCAD: femexamples.boxanalysis Namespace Reference
femexamples.boxanalysis Namespace Reference
Functions
def init_doc (doc=None)
def setup_base (doc=None, solvertype="ccxtools")
def setup_frequency (doc=None, solvertype="ccxtools")
def setup_static (doc=None, solvertype="ccxtools")
Variables
mesh_name
Function Documentation
init_doc()
def femexamples.boxanalysis.init_doc (doc = None)
Referenced by femexamples.boxanalysis.setup_base().
setup_base()
def femexamples.boxanalysis.setup_base (doc = None, solvertype = "ccxtools")
References femexamples.boxanalysis.init_doc(), ObjectsFem.makeAnalysis(), and ObjectsFem.makeMaterialSolid().
Referenced by femexamples.boxanalysis.setup_frequency(), and femexamples.boxanalysis.setup_static().
setup_frequency()
def femexamples.boxanalysis.setup_frequency (doc = None, solvertype = "ccxtools")
References ObjectsFem.makeSolverCalculix(), ObjectsFem.makeSolverCalculixCcxTools(), and femexamples.boxanalysis.setup_base().
setup_static()
def femexamples.boxanalysis.setup_static (doc = None, solvertype = "ccxtools")
References ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintForce(), ObjectsFem.makeConstraintPressure(), ObjectsFem.makeSolverCalculix(), ObjectsFem.makeSolverCalculixCcxTools(), ObjectsFem.makeSolverElmer(), ObjectsFem.makeSolverZ88(), and femexamples.boxanalysis.setup_base().
Variable Documentation
mesh_name
femexamples.boxanalysis.mesh_name