FreeCAD: draftobjects.array Namespace Reference
draftobjects.array Namespace Reference
Classes
class Array
Functions
def circ_placements (base_placement, r_distance, tan_distance, axis, center, circle_number, symmetry)
def polar_placements (base_placement, center, angle, number, axis, axisvector)
def rect_placements (base_placement, xvector, yvector, zvector, xnum, ynum, znum)
Function Documentation
circ_placements()
def draftobjects.array.circ_placements (base_placement, r_distance, tan_distance, axis, center, circle_number, symmetry)
Determine the placements where the circular copies will be.
Referenced by draftobjects.array.Array.execute().
polar_placements()
def draftobjects.array.polar_placements (base_placement, center, angle, number, axis, axisvector)
Determine the placements where the polar copies will be.
References DraftVecUtils.isNull(), and DraftVecUtils.tup().
Referenced by draftobjects.array.Array.execute().
rect_placements()
def draftobjects.array.rect_placements (base_placement, xvector, yvector, zvector, xnum, ynum, znum)
Determine the placements where the rectangular copies will be.
Referenced by draftobjects.array.Array.execute().