FreeCAD: FemGui::Module Class Reference
FemGui::Module Class Reference
Public Member Functions
Module ()
virtual ~Module ()
Constructor & Destructor Documentation
Module()
FemGui::Module::Module ()
References Base::BaseExceptionFreeCADError, Gui::Blue, Base::Persistence::getClassTypeId(), FemGui::ActiveAnalysisObserver::highlightActiveObject(), FemGui::ActiveAnalysisObserver::instance(), and FemGui::ActiveAnalysisObserver::setActiveObject().
~Module()
virtual FemGui::Module::~Module () virtual
References FemGui::ActiveAnalysisObserver::instance().
The documentation for this class was generated from the following file:
src/Mod/Fem/Gui/AppFemGuiPy.cpp