FreeCAD: draftutils.init_draft_statusbar Namespace Reference
draftutils.init_draft_statusbar Namespace Reference
Functions
def get_scales (unit_system=0)
def hide_draft_statusbar ()
def init_draft_statusbar_scale ()
def init_draft_statusbar_snap ()
def label_to_scale (label)
def scale_to_label (scale)
def show_draft_statusbar ()
Variables
list draft_scales_arch_imperial
list draft_scales_eng_imperial
list draft_scales_metrics
Function Documentation
get_scales()
def draftutils.init_draft_statusbar.get_scales (unit_system = 0)
returns the list of preset scales accordin to unit system.
Parameters:
unit_system =   0 : default from user preferences
                1 : metrics
                2 : imperial architectural
                3 : imperial engineering
Referenced by draftutils.init_draft_statusbar.init_draft_statusbar_scale().
hide_draft_statusbar()
def draftutils.init_draft_statusbar.hide_draft_statusbar ()
hides draft statusbar if present
References Gui.getMainWindow().
init_draft_statusbar_scale()
def draftutils.init_draft_statusbar.init_draft_statusbar_scale ()
this function initializes draft statusbar scale widget
References draftutils.init_draft_statusbar.get_scales(), Gui.getMainWindow(), and draftutils.init_draft_statusbar.scale_to_label().
init_draft_statusbar_snap()
def draftutils.init_draft_statusbar.init_draft_statusbar_snap ()
this function initializes draft statusbar snap widget
References Gui.getMainWindow().
label_to_scale()
def draftutils.init_draft_statusbar.label_to_scale (label)
transform a scale string into scale factor as float
References Gui.getMainWindow(), and draftutils.init_draft_statusbar.scale_to_label().
scale_to_label()
def draftutils.init_draft_statusbar.scale_to_label (scale)
transform a float number into a 1:X or X:1 scale and return it as label
Referenced by draftutils.init_draft_statusbar.init_draft_statusbar_scale(), and draftutils.init_draft_statusbar.label_to_scale().
show_draft_statusbar()
def draftutils.init_draft_statusbar.show_draft_statusbar ()
shows draft statusbar if present or initializes it
References Gui.getMainWindow().
Variable Documentation
draft_scales_arch_imperial
list draftutils.init_draft_statusbar.draft_scales_arch_imperial
Initial value:
 =   ["1/16in=1ft", "3/32in=1ft", "1/8in=1ft",
                                "3/16in=1ft", "1/4in=1ft","3/8in=1ft",
                                "1/2in=1ft", "3/4in=1ft", "1in=1ft",
                                "1.5in=1ft", "3in=1ft",
                                QT_TRANSLATE_NOOP("draft","custom"),
                               ]
draft_scales_eng_imperial
list draftutils.init_draft_statusbar.draft_scales_eng_imperial
Initial value:
 =   ["1in=10ft", "1in=20ft", "1in=30ft",
                               "1in=40ft", "1in=50ft", "1in=60ft",
                               "1in=70ft", "1in=80ft", "1in=90ft",
                               "1in=100ft",
                               QT_TRANSLATE_NOOP("draft","custom"),
                              ]
draft_scales_metrics
list draftutils.init_draft_statusbar.draft_scales_metrics
Initial value:
 =   ["1:1000", "1:500", "1:250", "1:200", "1:100",
                          "1:50", "1:25","1:20", "1:10", "1:5","1:2",
                          "1:1",
                          "2:1", "5:1", "10:1", "20:1",
                          QT_TRANSLATE_NOOP("draft","custom"),
                         ]