FreeCAD: draftgeoutils.circles Namespace Reference
draftgeoutils.circles Namespace Reference
Functions
def circlefrom1Line2Points (edge, p1, p2)
def circlefrom2Lines1Point (edge1, edge2, point)
def circleFrom2LinesRadius (edge1, edge2, radius)
def circleFrom2PointsRadius (p1, p2, radius)
def circleFrom3LineTangents (edge1, edge2, edge3)
def circleFromPointLineRadius (point, edge, radius)
def findClosestCircle (point, circles)
def findHomotheticCenterOfCircles (circle1, circle2)
def findRadicalAxis (circle1, circle2)
def findRadicalCenter (circle1, circle2, circle3)
def getCircleFromSpline (edge)
Variables
Part = lz.LazyLoader("Part", globals(), "Part")
Function Documentation
circlefrom1Line2Points()
def draftgeoutils.circles.circlefrom1Line2Points (edge, p1, p2)
Return a list of circles created from an edge and two points.
It calculates up to 2 possible centers.
References DraftVecUtils.dist().
Referenced by draftgeoutils.circles.circlefrom2Lines1Point().
circlefrom2Lines1Point()
def draftgeoutils.circles.circlefrom2Lines1Point (edge1, edge2, point)
Return a list of circles from two edges and one point.
References draftgeoutils.circles.circlefrom1Line2Points().
circleFrom2LinesRadius()
def draftgeoutils.circles.circleFrom2LinesRadius (edge1, edge2, radius)
Retun a list of circles from two edges and one radius.
It calculates 4 centers.
References DraftVecUtils.angle(), and DraftVecUtils.rotate().
circleFrom2PointsRadius()
def draftgeoutils.circles.circleFrom2PointsRadius (p1, p2, radius)
Return a list of circles from two points, and one radius.
The two points must not be equal.
It calculates up to 2 possible centers.
References DraftVecUtils.dist(), and DraftVecUtils.equals().
circleFrom3LineTangents()
def draftgeoutils.circles.circleFrom3LineTangents (edge1, edge2, edge3)
Return a list of circles from three edges.
It calculates up to 6 possible centers.
References DraftVecUtils.equals(), and DraftVecUtils.rotate().
circleFromPointLineRadius()
def draftgeoutils.circles.circleFromPointLineRadius (point, edge, radius)
Return a list of circles from one point, one edge, and one radius.
It calculates up to 2 possible centers.
References DraftVecUtils.dist(), and DraftVecUtils.scaleTo().
findClosestCircle()
def draftgeoutils.circles.findClosestCircle (point, circles)
Return the circle with closest center to a given point.
findHomotheticCenterOfCircles()
def draftgeoutils.circles.findHomotheticCenterOfCircles (circle1, circle2)
Calculate the homothetic centers from two circles.
Return None if the objects are not circles, or if they are concentric.
http://en.wikipedia.org/wiki/Homothetic_center
http://mathworld.wolfram.com/HomotheticCenter.html
References DraftVecUtils.equals().
findRadicalAxis()
def draftgeoutils.circles.findRadicalAxis (circle1, circle2)
Calculate the radical axis of two circles.
On the radical axis (also called power line) of two circles any
tangents drawn from a point on the axis to both circles have
the same length.
http://en.wikipedia.org/wiki/Radical_axis
http://mathworld.wolfram.com/RadicalLine.html
See Also
--------
findRadicalCenter
References DraftVecUtils.dist(), and DraftVecUtils.equals().
Referenced by draftgeoutils.circles.findRadicalCenter().
findRadicalCenter()
def draftgeoutils.circles.findRadicalCenter (circle1, circle2, circle3)
Calculate the radical center of three circles.
It is also called the power center.
It is the intersection point of the three radical axes of the pairs
of circles.
http://en.wikipedia.org/wiki/Power_center_(geometry)
http://mathworld.wolfram.com/RadicalCenter.html
See Also
--------
findRadicalAxis
References draftgeoutils.circles.findRadicalAxis().
getCircleFromSpline()
def draftgeoutils.circles.getCircleFromSpline (edge)
Return a circle-based edge from a bspline-based edge.
Return None if the edge is not a BSplineCurve.
References DraftVecUtils.isNull(), and DraftVecUtils.rotate().
Variable Documentation
Part
draftgeoutils.circles.Part = lz.LazyLoader("Part", globals(), "Part")