FreeCAD: addonmanager_utilities Namespace Reference
addonmanager_utilities Namespace Reference
Functions
def getDescRegex (url)
def getReadmeRegex (url)
def getReadmeUrl (url)
def getRepoUrl (text)
def getserver (url)
def getZipUrl (baseurl)
def install_macro (macro, macro_repo_dir)
def remove_directory_if_empty (dir)
def remove_macro (macro)
def restartFreeCAD ()
def symlink (source, link_name)
def translate (context, text, disambig=None)
def update_macro_details (old_macro, new_macro)
def urlopen (url)
Variables
ssl_ctx = None
Function Documentation
getDescRegex()
def addonmanager_utilities.getDescRegex (url)
Returns a regex string that extracts a WB description to be displayed in the description
panel of the Addon manager, if the README could not be found
getReadmeRegex()
def addonmanager_utilities.getReadmeRegex (url)
Return a regex string that extracts the contents to be displayed in the description
panel of the Addon manager, from raw HTML data (the readme's html rendering usually)
getReadmeUrl()
def addonmanager_utilities.getReadmeUrl (url)
getRepoUrl()
def addonmanager_utilities.getRepoUrl (text)
getserver()
def addonmanager_utilities.getserver (url)
returns the server part of an url
Referenced by getZipUrl().
getZipUrl()
def addonmanager_utilities.getZipUrl (baseurl)
References getserver().
install_macro()
def addonmanager_utilities.install_macro (macro, macro_repo_dir)
Install a macro and all its related files
Returns True if the macro was installed correctly.
Parameters
----------
- macro: an addonmanager_macro.Macro instance
remove_directory_if_empty()
def addonmanager_utilities.remove_directory_if_empty (dir)
Remove the directory if it is empty
Directory FreeCAD.getUserMacroDir(True) will not be removed even if empty.
Referenced by remove_macro().
remove_macro()
def addonmanager_utilities.remove_macro (macro)
Remove a macro and all its related files
Returns True if the macro was removed correctly.
Parameters
----------
- macro: an addonmanager_macro.Macro instance
References remove_directory_if_empty().
restartFreeCAD()
def addonmanager_utilities.restartFreeCAD ()
symlink()
def addonmanager_utilities.symlink (source, link_name)
translate()
def addonmanager_utilities.translate (context, text, disambig = None)
update_macro_details()
def addonmanager_utilities.update_macro_details (old_macro, new_macro)
Update a macro with information from another one
Update a macro with information from another one, supposedly the same but
from a different source. The first source is supposed to be git, the second
one the wiki.
urlopen()
def addonmanager_utilities.urlopen (url)
Opens an url with urllib2
Referenced by importSHP.checkShapeFileLibrary().
Variable Documentation
ssl_ctx
addonmanager_utilities.ssl_ctx = None