FreeCAD: draftgeoutils.edges Namespace Reference
draftgeoutils.edges Namespace Reference
Functions
def findEdge (anEdge, aList)
def findMidpoint (edge)
def getTangent (edge, from_point=None)
def invert (shape)
def isLine (bspline)
def isSameLine (e1, e2)
def orientEdge (edge, normal=None, make_arc=False)
Variables
Part = lz.LazyLoader("Part", globals(), "Part")
Function Documentation
findEdge()
def draftgeoutils.edges.findEdge (anEdge, aList)
Return True if edge is found in list of edges.
References DraftVecUtils.equals().
findMidpoint()
def draftgeoutils.edges.findMidpoint (edge)
Return the midpoint of a straight line or circular edge.
References DraftVecUtils.scaleTo().
Referenced by draftgeoutils.edges.invert().
getTangent()
def draftgeoutils.edges.getTangent (edge, from_point = None)
Return the tangent to an edge, including BSpline and circular arcs.
If from_point is given, it is used to calculate the tangent,
only useful for a circular arc.
invert()
def draftgeoutils.edges.invert (shape)
Return an inverted copy of the edge or wire contained in the shape.
References draftgeoutils.edges.findMidpoint(), and draftgeoutils.edges.isLine().
isLine()
def draftgeoutils.edges.isLine (bspline)
Return True if the given BSpline curve is a straight line.
Referenced by draftgeoutils.edges.invert().
isSameLine()
def draftgeoutils.edges.isSameLine (e1, e2)
Return True if the 2 edges are lines and have the same points.
References DraftVecUtils.equals().
orientEdge()
def draftgeoutils.edges.orientEdge (edge, normal = None, make_arc = False)
Re-orient the edge such that it is in the XY plane.
Re-orients `edge` such that it is in the XY plane.
If `normal` is passed, this is used as the basis for the rotation,
otherwise the placement of `edge` is used.
References DraftVecUtils.angle().
Variable Documentation
Part
draftgeoutils.edges.Part = lz.LazyLoader("Part", globals(), "Part")