FreeCAD: App::RelabelDocumentObjectExpressionVisitor< P > Class Template Reference
App::RelabelDocumentObjectExpressionVisitor< P > Class Template Reference
The RelabelDocumentObjectExpressionVisitor class is a functor class used to rename variables in an expression.
#include <ExpressionVisitors.h>
Public Member Functions
RelabelDocumentObjectExpressionVisitor (P &_prop, const std::string &_oldName, const std::string &_newName)
void visit (Expression *node)
Visit each node in the expression, and if it is a VariableExpression object, incoke renameDocumentObject in it.
~RelabelDocumentObjectExpressionVisitor ()
Public Member Functions inherited from App::ExpressionModifier< P >
ExpressionModifier (P &_prop)
bool getChanged () const
void setExpressionChanged ()
virtual ~ExpressionModifier ()
Public Member Functions inherited from App::ExpressionVisitor
virtual ~ExpressionVisitor ()
Additional Inherited Members
Protected Attributes inherited from App::ExpressionModifier< P >
P & prop
boost::shared_ptr< typename AtomicPropertyChangeInterface< P >::AtomicPropertyChange > signaller
Detailed Description
template<class P>
class App::RelabelDocumentObjectExpressionVisitor< P >
The RelabelDocumentObjectExpressionVisitor class is a functor class used to rename variables in an expression.
Constructor & Destructor Documentation
RelabelDocumentObjectExpressionVisitor()
template<class P > App::RelabelDocumentObjectExpressionVisitor< P >::RelabelDocumentObjectExpressionVisitor (P & _prop, const std::string & _oldName, const std::string & _newName)
~RelabelDocumentObjectExpressionVisitor()
template<class P > App::RelabelDocumentObjectExpressionVisitor< P >::~RelabelDocumentObjectExpressionVisitor ()
Member Function Documentation
visit()
template<class P > void App::RelabelDocumentObjectExpressionVisitor< P >::visit (Expression * node) virtual
Visit each node in the expression, and if it is a VariableExpression object, incoke renameDocumentObject in it.
Parameters
node Node to visit
Implements App::ExpressionVisitor.
References Base::freecad_dynamic_cast(), App::VariableExpression::renameDocumentObject(), App::ExpressionModifier< P >::setExpressionChanged(), and App::VariableExpression::validDocumentObjectRename().
The documentation for this class was generated from the following file:
src/App/ExpressionVisitors.h