FreeCAD: Spreadsheet::BuildDocDepsExpressionVisitor Class Reference
Spreadsheet::BuildDocDepsExpressionVisitor Class Reference
Public Member Functions
BuildDocDepsExpressionVisitor (PropertySheet &prop, std::set< App::DocumentObject *> &_docDeps)
void visit (Expression *node)
Public Member Functions inherited from App::ExpressionModifier< PropertySheet >
ExpressionModifier (PropertySheet &_prop)
bool getChanged () const
void setExpressionChanged ()
virtual ~ExpressionModifier ()
Public Member Functions inherited from App::ExpressionVisitor
virtual ~ExpressionVisitor ()
Additional Inherited Members
Protected Attributes inherited from App::ExpressionModifier< PropertySheet >
PropertySheet & prop
boost::shared_ptr< typename AtomicPropertyChangeInterface< PropertySheet >::AtomicPropertyChange > signaller
Constructor & Destructor Documentation
BuildDocDepsExpressionVisitor()
Spreadsheet::BuildDocDepsExpressionVisitor::BuildDocDepsExpressionVisitor (PropertySheet & prop, std::set< App::DocumentObject *> & _docDeps)
Member Function Documentation
visit()
void Spreadsheet::BuildDocDepsExpressionVisitor::visit (Expression * node) virtual
Implements App::ExpressionVisitor.
References Base::freecad_dynamic_cast(), App::Property::getContainer(), and App::VariableExpression::getProperty().
The documentation for this class was generated from the following file:
src/Mod/Spreadsheet/App/PropertySheet.cpp