FreeCAD: Gui::LocationInterfaceComp< Ui > Class Template Reference
Gui::LocationInterfaceComp< Ui > Class Template Reference
This template class does basically the same as LocationInterface unless that the Ui class is used as composition not as further base class.
#include <InputVector.h>
Public Member Functions
bool directionActivated (LocationDialog *dlg, int index)
Base::Vector3d getDirection () const
Base::Vector3d getPosition () const
LocationInterfaceComp (QDialog *dlg)
void retranslate (QDialog *dlg)
void setDirection (const Base::Vector3d &dir)
void setPosition (const Base::Vector3d &v)
~LocationInterfaceComp ()
Detailed Description
template<class Ui>
class Gui::LocationInterfaceComp< Ui >
This template class does basically the same as LocationInterface unless that the Ui class is used as composition not as further base class.
This class acts as a small wrapper class around the UI_-generated classes by Qt for which the location interface is needed. This class can be used as composition in dialog-based classes without including the ui_-generated header file. The Ui_-class can simply be forward declared.
Author
Werner Mayer
Constructor & Destructor Documentation
LocationInterfaceComp()
template<class Ui> Gui::LocationInterfaceComp< Ui >::LocationInterfaceComp (QDialog * dlg)
~LocationInterfaceComp()
template<class Ui> Gui::LocationInterfaceComp< Ui >::~LocationInterfaceComp ()
Member Function Documentation
directionActivated()
template<class Ui> bool Gui::LocationInterfaceComp< Ui >::directionActivated (LocationDialog * dlg, int index)
References Base::Vector3< double >::epsilon(), Gui::LocationDialog::getUserDirection(), and Base::Vector3< _Precision >::Length().
Referenced by Gui::Dialog::Placement::accept(), and Gui::Dialog::Transform::on_applyButton_clicked().
getDirection()
template<class Ui> Base::Vector3d Gui::LocationInterfaceComp< Ui >::getDirection (void) const
Referenced by Gui::Dialog::Placement::getDirection(), and Gui::Dialog::Transform::getDirection().
getPosition()
template<class Ui> Base::Vector3d Gui::LocationInterfaceComp< Ui >::getPosition (void) const
retranslate()
template<class Ui> void Gui::LocationInterfaceComp< Ui >::retranslate (QDialog * dlg)
References Draft::translate().
Referenced by Gui::Dialog::Placement::changeEvent(), and Gui::Dialog::Transform::changeEvent().
setDirection()
template<class Ui> void Gui::LocationInterfaceComp< Ui >::setDirection (const Base::Vector3d & dir)
References femsolver.report::display(), Base::Vector3< double >::epsilon(), Base::Vector3< _Precision >::Length(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
setPosition()
template<class Ui> void Gui::LocationInterfaceComp< Ui >::setPosition (const Base::Vector3d & v)
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
The documentation for this class was generated from the following file:
src/Gui/InputVector.h