FreeCAD: ObjectLabelObserver Class Reference
ObjectLabelObserver Class Reference
Observer that watches relabeled objects and make sure that the labels inside a document are unique.
Public Member Functions
void slotRelabelObject (const App::DocumentObject &, const App::Property &)
Checks the new label of the object and relabel it if needed to make it unique document-wide.
Static Public Member Functions
static void destruct ()
Destructs the sole instance.
static ObjectLabelObserver * instance ()
The one and only instance.
Detailed Description
Observer that watches relabeled objects and make sure that the labels inside a document are unique.
Note
In the FreeCAD design it is explicitly allowed to have duplicate labels (i.e. the user visible text e.g. in the tree view) while the internal names are always guaranteed to be unique.
Member Function Documentation
destruct()
void ObjectLabelObserver::destruct (void) static
Destructs the sole instance.
instance()
ObjectLabelObserver * ObjectLabelObserver::instance () static
The one and only instance.
Referenced by App::Application::initTypes().
slotRelabelObject()
void ObjectLabelObserver::slotRelabelObject (const App::DocumentObject & obj, const App::Property & prop)
Checks the new label of the object and relabel it if needed to make it unique document-wide.
References DraftGeomUtils::bind(), App::GetApplication(), App::DocumentObject::getDocument(), ParameterGrp::GetGroup(), App::Document::getObjects(), Base::Tools::getUniqueName(), App::Application::GetUserParameter(), App::PropertyString::getValue(), App::DocumentObject::Label, and App::Application::signalChangedObject.
The documentation for this class was generated from the following file:
src/App/Application.cpp