FreeCAD: draftfunctions.scale Namespace Reference
draftfunctions.scale Namespace Reference
Functions
def copy_scaled_edge (obj, edge_index, scale, center)
def copy_scaled_edges (arguments)
def scale (objectslist, scale=App.Vector(1, 1, 1), center=App.Vector(0, 0, 0), copy=False)
def scale_edge (obj, edge_index, scale, center)
def scale_vector_from_center (vector, scale, center)
def scale_vertex (obj, vertex_index, scale, center)
Variables
def copyScaledEdge = copy_scaled_edge
def copyScaledEdges = copy_scaled_edges
def scaleEdge = scale_edge
def scaleVectorFromCenter = scale_vector_from_center
def scaleVertex = scale_vertex
Function Documentation
copy_scaled_edge()
def draftfunctions.scale.copy_scaled_edge (obj, edge_index, scale, center)
Needed for SubObjects modifiers.
Implemented by Dion Moult during 0.19 dev cycle (works only with Draft Wire).
References draftfunctions.scale.scaleVectorFromCenter.
copy_scaled_edges()
def draftfunctions.scale.copy_scaled_edges (arguments)
Needed for SubObjects modifiers.
Implemented by Dion Moult during 0.19 dev cycle (works only with Draft Wire).
References draftfunctions.scale.copyScaledEdge.
scale()
def draftfunctions.scale.scale (objectslist, scale = App.Vector(1,1,1), center = App.Vector(0,0,0), copy = False)
scale(objects, scale, [center], copy)
Scales the objects contained in objects (that can be a list of objects or
an object) of the given  around given center.
Parameters
----------
objectlist : list
scale : Base.Vector
    Scale factors defined by a given vector (in X, Y, Z directions).
objectlist : Base.Vector
    Center of the scale operation.
copy : bool
    If copy is True, the actual objects are not scaled, but copies
    are created instead.
Return
----------
The objects (or their copies) are returned.
References DraftVecUtils.project(), and draftfunctions.scale.scale_vertex().
scale_edge()
def draftfunctions.scale.scale_edge (obj, edge_index, scale, center)
Needed for SubObjects modifiers.
Implemented by Dion Moult during 0.19 dev cycle (works only with Draft Wire).
References draftfunctions.scale.scaleVertex.
scale_vector_from_center()
def draftfunctions.scale.scale_vector_from_center (vector, scale, center)
Needed for SubObjects modifiers.
Implemented by Dion Moult during 0.19 dev cycle (works only with Draft Wire).
scale_vertex()
def draftfunctions.scale.scale_vertex (obj, vertex_index, scale, center)
Needed for SubObjects modifiers.
Implemented by Dion Moult during 0.19 dev cycle (works only with Draft Wire).
References draftfunctions.scale.scaleVectorFromCenter.
Referenced by draftfunctions.scale.scale().
Variable Documentation
copyScaledEdge
def draftfunctions.scale.copyScaledEdge = copy_scaled_edge
Referenced by draftfunctions.scale.copy_scaled_edges().
copyScaledEdges
def draftfunctions.scale.copyScaledEdges = copy_scaled_edges
scaleEdge
def draftfunctions.scale.scaleEdge = scale_edge
scaleVectorFromCenter
def draftfunctions.scale.scaleVectorFromCenter = scale_vector_from_center
Referenced by draftfunctions.scale.copy_scaled_edge(), and draftfunctions.scale.scale_vertex().
scaleVertex
def draftfunctions.scale.scaleVertex = scale_vertex
Referenced by draftfunctions.scale.scale_edge().