FreeCAD: draftgeoutils.circle_inversion Namespace Reference
draftgeoutils.circle_inversion Namespace Reference
Functions
def circleInversion (circle, circle2)
def pointInversion (circle, point)
def polarInversion (circle, edge)
Variables
Part = lz.LazyLoader("Part", globals(), "Part")
Function Documentation
circleInversion()
def draftgeoutils.circle_inversion.circleInversion (circle, circle2)
Circle inversion of a circle, inverting the center point.
Returns the new circle created from the inverted center of circle2.
References DraftVecUtils.dist(), DraftVecUtils.equals(), and draftgeoutils.circle_inversion.pointInversion().
pointInversion()
def draftgeoutils.circle_inversion.pointInversion (circle, point)
Return the circle inversion of a point.
It will return `None` if the given point is equal to the center
of the circle.
References DraftVecUtils.dist(), and DraftVecUtils.equals().
Referenced by draftgeoutils.circle_inversion.circleInversion(), and draftgeoutils.circle_inversion.polarInversion().
polarInversion()
def draftgeoutils.circle_inversion.polarInversion (circle, edge)
Return the inversion pole of a line. The edge is the polar.
The nearest point on the line is inversed.
http://mathworld.wolfram.com/InversionPole.html
References draftgeoutils.circle_inversion.pointInversion().
Variable Documentation
Part
draftgeoutils.circle_inversion.Part = lz.LazyLoader("Part", globals(), "Part")