FreeCAD: draftguitools.gui_edit_draft_objects Namespace Reference
draftguitools.gui_edit_draft_objects Namespace Reference
Functions
def arcInvert (obj)
def get_supported_draft_objects ()
def getArcEnd (obj, global_placement=False)
def getArcMid (obj, global_placement=False)
def getArcStart (obj, global_placement=False)
def getCirclePts (obj)
def getDimensionPts (obj)
def getEllipsePts (obj)
def getPolygonPts (obj)
def getRectanglePts (obj)
def getWirePts (obj)
def pointOnCircle (obj, angle, global_placement=False)
def recomputePointsBezier (obj, pts, idx, v, degree, moveTrackers=False)
def smoothBezPoint (obj, point, style='Symmetric')
def updateBezCurve (obj, nodeIndex, v)
def updateCircle (obj, nodeIndex, v, alt_edit_mode=0)
def updateDimension (obj, nodeIndex, v)
def updateEllipse (obj, nodeIndex, v)
def updatePolygon (obj, nodeIndex, v)
def updateRectangle (obj, nodeIndex, v)
def updateWire (obj, nodeIndex, v)
Function Documentation
arcInvert()
def draftguitools.gui_edit_draft_objects.arcInvert (obj)
get_supported_draft_objects()
def draftguitools.gui_edit_draft_objects.get_supported_draft_objects ()
getArcEnd()
def draftguitools.gui_edit_draft_objects.getArcEnd (obj, global_placement = False)
References draftguitools.gui_edit_draft_objects.pointOnCircle().
Referenced by draftguitools.gui_edit_draft_objects.getCirclePts(), and draftguitools.gui_edit_draft_objects.updateCircle().
getArcMid()
def draftguitools.gui_edit_draft_objects.getArcMid (obj, global_placement = False)
References draftguitools.gui_edit_draft_objects.pointOnCircle().
Referenced by draftguitools.gui_edit_draft_objects.getCirclePts(), and draftguitools.gui_edit_draft_objects.updateCircle().
getArcStart()
def draftguitools.gui_edit_draft_objects.getArcStart (obj, global_placement = False)
References draftguitools.gui_edit_draft_objects.pointOnCircle().
Referenced by draftguitools.gui_edit_draft_objects.getCirclePts(), and draftguitools.gui_edit_draft_objects.updateCircle().
getCirclePts()
def draftguitools.gui_edit_draft_objects.getCirclePts (obj)
Return the list of edipoints for the given Draft Arc or Circle.
circle:
0 : Placement.Base or center
1 : radius
arc:
0 : Placement.Base or center
1 : first endpoint
2 : second endpoint
3 : midpoint
References draftguitools.gui_edit_draft_objects.getArcEnd(), draftguitools.gui_edit_draft_objects.getArcMid(), and draftguitools.gui_edit_draft_objects.getArcStart().
getDimensionPts()
def draftguitools.gui_edit_draft_objects.getDimensionPts (obj)
getEllipsePts()
def draftguitools.gui_edit_draft_objects.getEllipsePts (obj)
getPolygonPts()
def draftguitools.gui_edit_draft_objects.getPolygonPts (obj)
getRectanglePts()
def draftguitools.gui_edit_draft_objects.getRectanglePts (obj)
Return the list of edipoints for the given Draft Rectangle.
0 : Placement.Base
1 : Length
2 : Height
getWirePts()
def draftguitools.gui_edit_draft_objects.getWirePts (obj)
pointOnCircle()
def draftguitools.gui_edit_draft_objects.pointOnCircle (obj, angle, global_placement = False)
Referenced by draftguitools.gui_edit_draft_objects.getArcEnd(), draftguitools.gui_edit_draft_objects.getArcMid(), and draftguitools.gui_edit_draft_objects.getArcStart().
recomputePointsBezier()
def draftguitools.gui_edit_draft_objects.recomputePointsBezier (obj, pts, idx, v, degree, moveTrackers = False)
(object, Points as list, nodeIndex as Int, App.Vector of new point, moveTrackers as Bool)
return the new point list, applying the App.Vector to the given index point
Referenced by draftguitools.gui_edit_draft_objects.updateBezCurve().
smoothBezPoint()
def draftguitools.gui_edit_draft_objects.smoothBezPoint (obj, point, style = 'Symmetric')
updateBezCurve()
def draftguitools.gui_edit_draft_objects.updateBezCurve (obj, nodeIndex, v)
References draftguitools.gui_edit_draft_objects.recomputePointsBezier().
updateCircle()
def draftguitools.gui_edit_draft_objects.updateCircle (obj, nodeIndex, v, alt_edit_mode = 0)
References DraftVecUtils.angle(), draftguitools.gui_edit_draft_objects.getArcEnd(), draftguitools.gui_edit_draft_objects.getArcMid(), draftguitools.gui_edit_draft_objects.getArcStart(), and DraftVecUtils.project().
updateDimension()
def draftguitools.gui_edit_draft_objects.updateDimension (obj, nodeIndex, v)
updateEllipse()
def draftguitools.gui_edit_draft_objects.updateEllipse (obj, nodeIndex, v)
updatePolygon()
def draftguitools.gui_edit_draft_objects.updatePolygon (obj, nodeIndex, v)
updateRectangle()
def draftguitools.gui_edit_draft_objects.updateRectangle (obj, nodeIndex, v)
References DraftVecUtils.project().
updateWire()
def draftguitools.gui_edit_draft_objects.updateWire (obj, nodeIndex, v)