FreeCAD: TechDraw::CosmeticEdgePy Class Reference
TechDraw::CosmeticEdgePy Class Reference
The python export class for CosmeticEdge.
#include <CosmeticEdgePy.h>
Public Types
typedef CosmeticEdge * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
CosmeticEdgePy (CosmeticEdge *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
CosmeticEdge * getCosmeticEdgePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CosmeticEdgePy.
static PyMethodDef Methods []
Methods structure of CosmeticEdgePy.
static PyTypeObject Type
Type structure of CosmeticEdgePy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CosmeticEdgePy ()
Protected Member Functions inherited from Base::PyObjectBase
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * copy (PyObject *args)
implementer for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for CosmeticEdge.
Member Typedef Documentation
PointerType
typedef CosmeticEdge* TechDraw::CosmeticEdgePy::PointerType
Constructor & Destructor Documentation
~CosmeticEdgePy()
CosmeticEdgePy::~CosmeticEdgePy () protected
CosmeticEdgePy()
CosmeticEdgePy::CosmeticEdgePy (CosmeticEdge * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
clone()
PyObject * CosmeticEdgePy::clone (PyObject * args)
implementer for the clone() method
References TechDraw::CosmeticEdge::clone(), getCosmeticEdgePtr(), and GetType().
Referenced by ArchPanel.CommandPanelSheet::Activated(), and staticCallback_clone().
copy()
PyObject * CosmeticEdgePy::copy (PyObject * args)
implementer for the copy() method
References TechDraw::CosmeticEdge::copy(), getCosmeticEdgePtr(), and GetType().
Referenced by staticCallback_copy().
getCosmeticEdgePtr()
CosmeticEdge * CosmeticEdgePy::getCosmeticEdgePtr (void) const
getter for the object handled by this class
Referenced by clone(), copy(), and TechDraw::PropertyCosmeticEdgeList::setPyObject().
getCustomAttributes()
PyObject * CosmeticEdgePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
GetType()
virtual PyTypeObject* TechDraw::CosmeticEdgePy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
Referenced by clone(), and copy().
PyInit()
int CosmeticEdgePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * CosmeticEdgePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string CosmeticEdgePy::representation (void) const
Referenced by config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr2(), config_control_design.degenerate_pcurve::wr2(), automotive_design.pcurve::wr2(), and automotive_design.degenerate_pcurve::wr2().
setCustomAttributes()
int CosmeticEdgePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_clone()
PyObject * CosmeticEdgePy::staticCallback_clone (PyObject * self, PyObject * args) static
callback for the clone() method
References Base::BaseExceptionFreeCADError, clone(), Base::Console(), Base::ConsoleSingleton::Error(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_copy()
PyObject * CosmeticEdgePy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADError, Base::Console(), copy(), Base::ConsoleSingleton::Error(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef CosmeticEdgePy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of CosmeticEdgePy.
Methods
PyMethodDef CosmeticEdgePy::Methods static
Initial value:
= {
    {"clone",
        reinterpret_cast<PyCFunction>( staticCallback_clone ),
        METH_VARARGS,
        "Create a clone of this CosmeticEdge"
    },
    {"copy",
        reinterpret_cast<PyCFunction>( staticCallback_copy ),
        METH_VARARGS,
        "Create a copy of this CosmeticEdge"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of CosmeticEdgePy.
Type
PyTypeObject CosmeticEdgePy::Type static
Type structure of CosmeticEdgePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchSchedule.CommandArchSchedule::IsActive(), and ArchAxis.CommandArchGrid::IsActive().
The documentation for this class was generated from the following files:
build/webdoc/src/Mod/TechDraw/App/CosmeticEdgePy.h
src/Mod/TechDraw/App/CosmeticEdgePyImp.cpp
build/webdoc/src/Mod/TechDraw/App/CosmeticEdgePy.cpp