FreeCAD: draftfunctions.split Namespace Reference
draftfunctions.split Namespace Reference
Functions
def split (wire, newPoint, edgeIndex)
def split_closed_wire (wire, edgeIndex)
def split_open_wire (wire, newPoint, edgeIndex)
Variables
def splitClosedWire = split_closed_wire
def splitOpenWire = split_open_wire
Function Documentation
split()
def draftfunctions.split.split (wire, newPoint, edgeIndex)
References draftfunctions.split.split_closed_wire(), and draftfunctions.split.split_open_wire().
split_closed_wire()
def draftfunctions.split.split_closed_wire (wire, edgeIndex)
Referenced by draftfunctions.split.split().
split_open_wire()
def draftfunctions.split.split_open_wire (wire, newPoint, edgeIndex)
Referenced by draftfunctions.split.split().
Variable Documentation
splitClosedWire
def draftfunctions.split.splitClosedWire = split_closed_wire
splitOpenWire
def draftfunctions.split.splitOpenWire = split_open_wire