FreeCAD: draftobjects.patharray Namespace Reference
draftobjects.patharray Namespace Reference
Classes
class PathArray
Functions
def calculate_placement (globalRotation, edge, offset, RefPt, xlate, align, normal=None, mode='Original', overrideNormal=False)
def get_parameter_from_v0 (edge, offset)
def placements_on_path (shapeRotation, pathwire, count, xlate, align, mode='Original', forceNormal=False, normalOverride=None)
Variables
def calculatePlacement = calculate_placement
def calculatePlacementsOnPath = placements_on_path
DraftGeomUtils = lz.LazyLoader("DraftGeomUtils", globals(), "DraftGeomUtils")
def getParameterFromV0 = get_parameter_from_v0
Part = lz.LazyLoader("Part", globals(), "Part")
Function Documentation
calculate_placement()
def draftobjects.patharray.calculate_placement (globalRotation, edge, offset, RefPt, xlate, align, normal = None, mode = 'Original', overrideNormal = False)
Orient shape to a local coordinate system (tangent, normal, binormal).
Orient shape at parameter offset, normally length.
http://en.wikipedia.org/wiki/Euler_angles (previous version)
http://en.wikipedia.org/wiki/Quaternions
References draftobjects.patharray.get_parameter_from_v0().
Referenced by draftobjects.patharray.placements_on_path().
get_parameter_from_v0()
def draftobjects.patharray.get_parameter_from_v0 (edge, offset)
Return parameter at distance offset from edge.Vertexes[0].
sb method in Part.TopoShapeEdge???
References DraftVecUtils.equals().
Referenced by draftobjects.patharray.calculate_placement(), and draftobjects.patharray.placements_on_path().
placements_on_path()
def draftobjects.patharray.placements_on_path (shapeRotation, pathwire, count, xlate, align, mode = 'Original', forceNormal = False, normalOverride = None)
Calculate the placements of a shape along a given path.
Each copy will be distributed evenly.
References draftobjects.patharray.calculate_placement(), and draftobjects.patharray.get_parameter_from_v0().
Referenced by draftobjects.patharray.PathArray.execute().
Variable Documentation
calculatePlacement
def draftobjects.patharray.calculatePlacement = calculate_placement
calculatePlacementsOnPath
def draftobjects.patharray.calculatePlacementsOnPath = placements_on_path
DraftGeomUtils
draftobjects.patharray.DraftGeomUtils = lz.LazyLoader("DraftGeomUtils", globals(), "DraftGeomUtils")
getParameterFromV0
def draftobjects.patharray.getParameterFromV0 = get_parameter_from_v0
Part
draftobjects.patharray.Part = lz.LazyLoader("Part", globals(), "Part")