FreeCAD: draftfunctions.array Namespace Reference
draftfunctions.array Namespace Reference
Functions
def array (objectslist, arg1, arg2, arg3, arg4=None, arg5=None, arg6=None)
def polarArray (objectslist, center, angle, num)
def rectArray (objectslist, xvector, yvector, xnum, ynum)
def rectArray2 (objectslist, xvector, yvector, zvector, xnum, ynum, znum)
Function Documentation
array()
def draftfunctions.array.array (objectslist, arg1, arg2, arg3, arg4 = None, arg5 = None, arg6 = None)
This function creates an array of independent objects.
Use makeArray() to create a parametric array object.
Creates an array of the given objects (that can be an object or a list
of objects).
In case of rectangular array, xnum of iterations in the x direction
at xvector distance between iterations, and same for y and z directions
with yvector and ynum and zvector and znum.
In case of polar array, center is a vector, totalangle is the angle
to cover (in degrees) and totalnum is the number of objects, including
the original.
Use
---
array(objectslist, xvector, yvector, xnum, ynum) for rectangular array
array(objectslist, xvector, yvector, zvector, xnum, ynum, znum) for rectangular array
array(objectslist, center, totalangle, totalnum) for polar array
References draftfunctions.array.polarArray(), draftfunctions.array.rectArray(), and draftfunctions.array.rectArray2().
polarArray()
def draftfunctions.array.polarArray (objectslist, center, angle, num)
Referenced by draftfunctions.array.array().
rectArray()
def draftfunctions.array.rectArray (objectslist, xvector, yvector, xnum, ynum)
Referenced by draftfunctions.array.array().
rectArray2()
def draftfunctions.array.rectArray2 (objectslist, xvector, yvector, zvector, xnum, ynum, znum)
Referenced by draftfunctions.array.array().