FreeCAD: draftgeoutils.intersections Namespace Reference
draftgeoutils.intersections Namespace Reference
Functions
def angleBisection (edge1, edge2)
def connect (edges, closed=False)
def findIntersection (edge1, edge2, infinite1=False, infinite2=False, ex1=False, ex2=False, dts=True, findAll=False)
def wiresIntersect (wire1, wire2)
Variables
Part = lz.LazyLoader("Part", globals(), "Part")
Function Documentation
angleBisection()
def draftgeoutils.intersections.angleBisection (edge1, edge2)
Return an edge that bisects the angle between the 2 straight edges.
References DraftVecUtils.angle(), draftgeoutils.intersections.findIntersection(), and DraftVecUtils.rotate().
connect()
def draftgeoutils.intersections.connect (edges, closed = False)
Connect the edges in the given list by their intersections.
References DraftVecUtils.closest(), and draftgeoutils.intersections.findIntersection().
findIntersection()
def draftgeoutils.intersections.findIntersection (edge1, edge2, infinite1 = False, infinite2 = False, ex1 = False, ex2 = False, dts = True, findAll = False)
Return a list containing the intersection points of 2 edges.
You can also feed 4 points instead of `edge1` and `edge2`.
If `dts` is used, `Shape.distToShape()` is used, which can be buggy.
References DraftVecUtils.equals(), DraftVecUtils.isNull(), and DraftVecUtils.precision().
Referenced by draftgeoutils.intersections.angleBisection(), draftgeoutils.intersections.connect(), and draftgeoutils.intersections.wiresIntersect().
wiresIntersect()
def draftgeoutils.intersections.wiresIntersect (wire1, wire2)
Return True if some of the edges of the wires are intersecting.
Otherwise return `False`.
References draftgeoutils.intersections.findIntersection().
Variable Documentation
Part
draftgeoutils.intersections.Part = lz.LazyLoader("Part", globals(), "Part")