FreeCAD: App::BooleanExpression Class Reference
App::BooleanExpression Class Reference
#include <Expression.h>
Public Member Functions
BooleanExpression (const App::DocumentObject *_owner=0, bool _value=false)
virtual Expression * copy () const
Create and return a copy of the expression.
Public Member Functions inherited from App::NumberExpression
virtual Expression * eval () const
Evaluate the expression.
void negate ()
Negate the stored value.
NumberExpression (const App::DocumentObject *_owner=0, const Base::Quantity &quantity=Base::Quantity())
virtual int priority () const
virtual Expression * simplify () const
Simplify the expression.
virtual std::string toString () const
Return a string representation, in this case the unit string.
Public Member Functions inherited from App::UnitExpression
const Base::Quantity & getQuantity () const
double getScaler () const
const Base::Unit & getUnit () const
const std::string getUnitString () const
double getValue () const
boost::any getValueAsAny () const
void setUnit (const Base::Quantity &_quantity)
Set unit information.
UnitExpression (const App::DocumentObject *_owner=0, const Base::Quantity &_quantity=Base::Quantity(), const std::string &_unitStr=std::string())
Public Member Functions inherited from App::Expression
Expression (const App::DocumentObject *_owner)
virtual void getDeps (std::set< ObjectIdentifier > &) const
const App::DocumentObject * getOwner () const
virtual bool isTouched () const
virtual void visit (ExpressionVisitor &v)
virtual ~Expression ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from App::Expression
static Expression * parse (const App::DocumentObject *owner, const std::string &buffer)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=0)
Protected Attributes inherited from App::UnitExpression
Base::Quantity quantity
std::string unitStr
The unit string from the original parsed string.
Protected Attributes inherited from App::Expression
const App::DocumentObject * owner
The document object used to access unqualified variables (i.e local scope)
Constructor & Destructor Documentation
BooleanExpression()
BooleanExpression::BooleanExpression (const App::DocumentObject * _owner = 0, bool _value = false)
Referenced by copy().
Member Function Documentation
copy()
Expression * BooleanExpression::copy () const virtual
Create and return a copy of the expression.
Reimplemented from App::NumberExpression.
References BooleanExpression(), App::UnitExpression::getValue(), and App::Expression::owner.
The documentation for this class was generated from the following files:
src/App/Expression.h
src/App/Expression.cpp