FreeCAD: ImportOCAFGui Class Reference
ImportOCAFGui Class Reference
Public Member Functions
ImportOCAFGui (Handle(TDocStd_Document) h, App::Document *d, const std::string &name)
Public Member Functions inherited from Import::ImportOCAF
ImportOCAF (Handle(TDocStd_Document) h, App::Document *d, const std::string &name)
void loadShapes ()
void setMerge (bool)
virtual ~ImportOCAF ()
Constructor & Destructor Documentation
ImportOCAFGui()
ImportOCAFGui::ImportOCAFGui (Handle(TDocStd_Document) h, App::Document * d, const std::string & name)
References Base::Persistence::getClassTypeId(), Gui::Application::getViewProvider(), Gui::Application::Instance, and Base::BaseClass::isDerivedFrom().
The documentation for this class was generated from the following file:
src/Mod/Import/Gui/AppImportGuiPy.cpp