FreeCAD: RewriteExpressionVisitor Class Reference
RewriteExpressionVisitor Class Reference
The RewriteExpressionVisitor class.
Public Member Functions
bool changed () const
void reset ()
RewriteExpressionVisitor (CellAddress address, int rowCount, int colCount)
void visit (Expression *node)
~RewriteExpressionVisitor ()
Public Member Functions inherited from App::ExpressionVisitor
virtual ~ExpressionVisitor ()
Detailed Description
The RewriteExpressionVisitor class.
A class that visits each node of an expressions, and possibly rewrites variables. This is a helper class to rewrite expressions when rows or columns are either inserted or removed, to make sure that formulas referencing cells being moved to a new locations will still be valid, i.e rewritten.
Constructor & Destructor Documentation
RewriteExpressionVisitor()
RewriteExpressionVisitor::RewriteExpressionVisitor (CellAddress address, int rowCount, int colCount)
~RewriteExpressionVisitor()
RewriteExpressionVisitor::~RewriteExpressionVisitor ()
Member Function Documentation
changed()
bool RewriteExpressionVisitor::changed () const
reset()
void RewriteExpressionVisitor::reset (void)
visit()
void RewriteExpressionVisitor::visit (Expression * node) virtual
Implements App::ExpressionVisitor.
References Spreadsheet::columnName(), App::decodeColumn(), App::decodeRow(), Base::freecad_dynamic_cast(), App::Range::from(), App::Expression::getOwner(), App::VariableExpression::name(), Spreadsheet::rowName(), App::VariableExpression::setPath(), and App::Range::to().
The documentation for this class was generated from the following file:
src/Mod/Spreadsheet/App/PropertySheet.cpp