FreeCAD: ObjectDeletedExpressionVisitor Class Reference
ObjectDeletedExpressionVisitor Class Reference
Public Member Functions
bool isFound () const
ObjectDeletedExpressionVisitor (const App::DocumentObject *_obj)
void visit (Expression *node)
Visit each node in the expression, and if it is a VariableExpression object check if it references obj.
Public Member Functions inherited from App::ExpressionVisitor
virtual ~ExpressionVisitor ()
Constructor & Destructor Documentation
ObjectDeletedExpressionVisitor()
ObjectDeletedExpressionVisitor::ObjectDeletedExpressionVisitor (const App::DocumentObject * _obj)
Member Function Documentation
isFound()
bool ObjectDeletedExpressionVisitor::isFound () const
Referenced by App::PropertyExpressionEngine::slotObjectDeleted().
visit()
void ObjectDeletedExpressionVisitor::visit (Expression * node) virtual
Visit each node in the expression, and if it is a VariableExpression object check if it references obj.
Parameters
node Node to visit
Implements App::ExpressionVisitor.
References Base::freecad_dynamic_cast(), App::ObjectIdentifier::getDocumentObject(), and App::VariableExpression::getPath().
The documentation for this class was generated from the following file:
src/App/PropertyExpressionEngine.cpp