FreeCAD: TechDraw::CenterLinePy Class Reference
TechDraw::CenterLinePy Class Reference
The python export class for CenterLine.
#include <CenterLinePy.h>
Public Types
typedef CenterLine * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
CenterLinePy (CenterLine *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
CenterLine * getCenterLinePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CenterLinePy.
static PyMethodDef Methods []
Methods structure of CenterLinePy.
static PyTypeObject Type
Type structure of CenterLinePy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CenterLinePy ()
Protected Member Functions inherited from Base::PyObjectBase
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * copy (PyObject *args)
implementer for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for CenterLine.
Member Typedef Documentation
PointerType
typedef CenterLine* TechDraw::CenterLinePy::PointerType
Constructor & Destructor Documentation
~CenterLinePy()
CenterLinePy::~CenterLinePy () protected
CenterLinePy()
CenterLinePy::CenterLinePy (CenterLine * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
clone()
PyObject * CenterLinePy::clone (PyObject * args)
implementer for the clone() method
References TechDraw::CenterLine::clone(), getCenterLinePtr(), and GetType().
Referenced by ArchPanel.CommandPanelSheet::Activated(), and staticCallback_clone().
copy()
PyObject * CenterLinePy::copy (PyObject * args)
implementer for the copy() method
References TechDraw::CenterLine::copy(), getCenterLinePtr(), and GetType().
Referenced by staticCallback_copy().
getCenterLinePtr()
CenterLine * CenterLinePy::getCenterLinePtr (void) const
getter for the object handled by this class
Referenced by clone(), copy(), and TechDraw::PropertyCenterLineList::setPyObject().
getCustomAttributes()
PyObject * CenterLinePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
GetType()
virtual PyTypeObject* TechDraw::CenterLinePy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
Referenced by clone(), and copy().
PyInit()
int CenterLinePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * CenterLinePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string CenterLinePy::representation (void) const
Referenced by config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr2(), config_control_design.degenerate_pcurve::wr2(), automotive_design.pcurve::wr2(), and automotive_design.degenerate_pcurve::wr2().
setCustomAttributes()
int CenterLinePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_clone()
PyObject * CenterLinePy::staticCallback_clone (PyObject * self, PyObject * args) static
callback for the clone() method
References Base::BaseExceptionFreeCADError, clone(), Base::Console(), Base::ConsoleSingleton::Error(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_copy()
PyObject * CenterLinePy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADError, Base::Console(), copy(), Base::ConsoleSingleton::Error(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef CenterLinePy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of CenterLinePy.
Methods
PyMethodDef CenterLinePy::Methods static
Initial value:
= {
    {"clone",
        reinterpret_cast<PyCFunction>( staticCallback_clone ),
        METH_VARARGS,
        "Create a clone of this centerline"
    },
    {"copy",
        reinterpret_cast<PyCFunction>( staticCallback_copy ),
        METH_VARARGS,
        "Create a copy of this centerline"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of CenterLinePy.
Type
PyTypeObject CenterLinePy::Type static
Type structure of CenterLinePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchSchedule.CommandArchSchedule::IsActive(), and ArchAxis.CommandArchGrid::IsActive().
The documentation for this class was generated from the following files:
build/webdoc/src/Mod/TechDraw/App/CenterLinePy.h
src/Mod/TechDraw/App/CenterLinePyImp.cpp
build/webdoc/src/Mod/TechDraw/App/CenterLinePy.cpp