FreeCAD: draftgeoutils.circles_incomplete Namespace Reference
draftgeoutils.circles_incomplete Namespace Reference
Functions
def circleFrom1Circle2Lines (circle, line1, line2)
def circlefrom1Circle2Points (circle, point1, point2)
def circleFrom1tan1pt1rad (tan1, p1, rad)
def circleFrom1tan2pt (tan1, p1, p2)
def circleFrom2Circle1Lines (circle1, circle2, line)
def circlefrom2Circles1Point (circle1, circle2, point)
def circleFrom2CirclesRadius (circle1, circle2, radius)
def circleFrom2tan1pt (tan1, tan2, point)
def circleFrom2tan1rad (tan1, tan2, rad)
def circleFrom3tan (tan1, tan2, tan3)
def circlefromCircleLinePoint (circle, line, point)
def circleFromCircleLineRadius (circle, line, radius)
def circleFromPointCircleRadius (point, circle, radius)
Function Documentation
circleFrom1Circle2Lines()
def draftgeoutils.circles_incomplete.circleFrom1Circle2Lines (circle, line1, line2)
Do nothing. Placeholder function. Needs to be implemented.
Referenced by draftgeoutils.circles_incomplete.circleFrom3tan().
circlefrom1Circle2Points()
def draftgeoutils.circles_incomplete.circlefrom1Circle2Points (circle, point1, point2)
Do nothing. Placeholder function. Needs to be implemented.
Referenced by draftgeoutils.circles_incomplete.circleFrom1tan2pt().
circleFrom1tan1pt1rad()
def draftgeoutils.circles_incomplete.circleFrom1tan1pt1rad (tan1, p1, rad)
Circle from one tangent, one point, and radius.
The tangents should be edges, and they may be either straight line edges
or circular edges, so two combinations are possible.
References draftgeoutils.circles_incomplete.circleFromPointCircleRadius().
circleFrom1tan2pt()
def draftgeoutils.circles_incomplete.circleFrom1tan2pt (tan1, p1, p2)
Circle from one tangent and two points.
The tangents should be edges, and they may be either straight line edges
or circular edges, so two combinations are possible.
References draftgeoutils.circles_incomplete.circlefrom1Circle2Points().
circleFrom2Circle1Lines()
def draftgeoutils.circles_incomplete.circleFrom2Circle1Lines (circle1, circle2, line)
Do nothing. Placeholder function. Needs to be implemented.
Referenced by draftgeoutils.circles_incomplete.circleFrom3tan().
circlefrom2Circles1Point()
def draftgeoutils.circles_incomplete.circlefrom2Circles1Point (circle1, circle2, point)
Do nothing. Placeholder function. Needs to be implemented.
Referenced by draftgeoutils.circles_incomplete.circleFrom2tan1pt().
circleFrom2CirclesRadius()
def draftgeoutils.circles_incomplete.circleFrom2CirclesRadius (circle1, circle2, radius)
Do nothing. Placeholder function. Needs to be implemented.
Referenced by draftgeoutils.circles_incomplete.circleFrom2tan1rad().
circleFrom2tan1pt()
def draftgeoutils.circles_incomplete.circleFrom2tan1pt (tan1, tan2, point)
Circle from two tangents and one point.
The tangents should be edges, and they may be either straight line edges
or circular edges, so four combinations are possible.
References draftgeoutils.circles_incomplete.circlefrom2Circles1Point(), and draftgeoutils.circles_incomplete.circlefromCircleLinePoint().
circleFrom2tan1rad()
def draftgeoutils.circles_incomplete.circleFrom2tan1rad (tan1, tan2, rad)
Circle from two tangents and one radius.
The tangents should be edges, and they may be either straight line edges
or circular edges, so four combinations are possible.
References draftgeoutils.circles_incomplete.circleFrom2CirclesRadius(), and draftgeoutils.circles_incomplete.circleFromCircleLineRadius().
circleFrom3tan()
def draftgeoutils.circles_incomplete.circleFrom3tan (tan1, tan2, tan3)
Circle from three tangents.
The tangents should be edges, and they may be either straight line edges
or circular edges, so eight combinations are possible.
References draftgeoutils.circles_incomplete.circleFrom1Circle2Lines(), and draftgeoutils.circles_incomplete.circleFrom2Circle1Lines().
circlefromCircleLinePoint()
def draftgeoutils.circles_incomplete.circlefromCircleLinePoint (circle, line, point)
Do nothing. Placeholder function. Needs to be implemented.
Referenced by draftgeoutils.circles_incomplete.circleFrom2tan1pt().
circleFromCircleLineRadius()
def draftgeoutils.circles_incomplete.circleFromCircleLineRadius (circle, line, radius)
Do nothing. Placeholder function. Needs to be implemented.
Referenced by draftgeoutils.circles_incomplete.circleFrom2tan1rad().
circleFromPointCircleRadius()
def draftgeoutils.circles_incomplete.circleFromPointCircleRadius (point, circle, radius)
Do nothing. Placeholder function. Needs to be implemented.
Referenced by draftgeoutils.circles_incomplete.circleFrom1tan1pt1rad().