FreeCAD: Part::GeometryDefaultExtension< T > Class Template Reference
Part::GeometryDefaultExtension< T > Class Template Reference
#include <GeometryDefaultExtension.h>
Public Member Functions
virtual std::unique_ptr< Part::GeometryExtension > copy (void) const override
GeometryDefaultExtension ()
GeometryDefaultExtension ()
GeometryDefaultExtension ()
GeometryDefaultExtension (const T &val, std::string name=std::string())
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
const T & getValue () const
virtual void Restore (Base::XMLReader &) override
This method is used to restore properties from an XML document.
void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const override
This method is used to save properties to an XML document.
void setValue (const T &val)
virtual ~GeometryDefaultExtension () override=default
Public Member Functions inherited from Part::GeometryExtension
const std::string & getName () const
void setName (const std::string &str)
virtual ~GeometryExtension ()=default
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from Part::GeometryExtension
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
void restoreNameAttribute (Base::XMLReader &)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
GeometryDefaultExtension() [1/4]
template<typename T > Part::GeometryDefaultExtension< T >::GeometryDefaultExtension
GeometryDefaultExtension() [2/4]
template<typename T > GeometryDefaultExtension::GeometryDefaultExtension (const T & val, std::string name = std::string())
References Part::GeometryExtension::setName().
~GeometryDefaultExtension()
template<typename T > virtual Part::GeometryDefaultExtension< T >::~GeometryDefaultExtension () override virtual default
GeometryDefaultExtension() [3/4]
Part::GeometryDefaultExtension< long >::GeometryDefaultExtension ()
GeometryDefaultExtension() [4/4]
Part::GeometryDefaultExtension< double >::GeometryDefaultExtension ()
Member Function Documentation
copy()
template<typename T > std::unique_ptr< Part::GeometryExtension > GeometryDefaultExtension::copy (void) const override virtual
Implements Part::GeometryExtension.
getMemSize()
template<typename T > unsigned int GeometryDefaultExtension::getMemSize (void) const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Part::GeometryExtension.
getPyObject() [1/5]
PyObject * Part::GeometryDefaultExtension< long >::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
getPyObject() [2/5]
PyObject * Part::GeometryDefaultExtension< std::string >::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
getPyObject() [3/5]
PyObject * Part::GeometryDefaultExtension< bool >::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
getPyObject() [4/5]
PyObject * Part::GeometryDefaultExtension< double >::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
getPyObject() [5/5]
template<typename T > PyObject * GeometryDefaultExtension::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
getValue()
template<typename T > const T& Part::GeometryDefaultExtension< T >::getValue () const
Referenced by Part::GeometryBoolExtensionPy::representation(), Part::GeometryStringExtensionPy::representation(), Part::GeometryIntExtensionPy::representation(), and Part::GeometryDoubleExtensionPy::representation().
Restore() [1/4]
template<typename T > void GeometryDefaultExtension::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Part::GeometryExtension.
References Base::XMLReader::getAttribute().
Restore() [2/4]
void Part::GeometryDefaultExtension< long >::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Part::GeometryExtension.
References Base::XMLReader::getAttributeAsInteger().
Restore() [3/4]
void Part::GeometryDefaultExtension< bool >::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Part::GeometryExtension.
References Base::XMLReader::getAttributeAsInteger().
Restore() [4/4]
void Part::GeometryDefaultExtension< double >::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Part::GeometryExtension.
References Base::XMLReader::getAttributeAsFloat().
Save()
template<typename T > void GeometryDefaultExtension::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Part::GeometryExtension.
References Base::Writer::ind(), and Base::Writer::Stream().
setValue()
template<typename T > void Part::GeometryDefaultExtension< T >::setValue (const T & val)
Referenced by Part::GeometryBoolExtensionPy::PyInit(), Part::GeometryIntExtensionPy::PyInit(), Part::GeometryStringExtensionPy::PyInit(), Part::GeometryDoubleExtensionPy::PyInit(), Part::GeometryBoolExtensionPy::setValue(), Part::GeometryDoubleExtensionPy::setValue(), Part::GeometryIntExtensionPy::setValue(), and Part::GeometryStringExtensionPy::setValue().
The documentation for this class was generated from the following files:
src/Mod/Part/App/GeometryDefaultExtension.h
src/Mod/Part/App/GeometryDefaultExtension.cpp