FreeCAD: draftmake.make_sketch Namespace Reference
draftmake.make_sketch Namespace Reference
Functions
def make_sketch (objectslist, autoconstraints=False, addTo=None, delete=False, name="Sketch", radiusPrecision=-1)
Variables
makeSketch = make_sketch
Function Documentation
make_sketch()
def draftmake.make_sketch.make_sketch (objectslist, autoconstraints = False, addTo = None, delete = False, name = "Sketch", radiusPrecision = -1)
makeSketch(objectslist,[autoconstraints],[addTo],[delete],[name],[radiusPrecision])
Makes a Sketch objectslist with the given Draft objects.
Parameters
----------
objectlist: can be single or list of objects of Draft type objects,
    Part::Feature, Part.Shape, or mix of them.
autoconstraints(False): if True, constraints will be automatically added to
    wire nodes, rectangles and circles.
addTo(None) : if set to an existing sketch, geometry will be added to it
    instead of creating a new one.
delete(False): if True, the original object will be deleted.
    If set to a string 'all' the object and all its linked object will be
    deleted
name('Sketch'): the name for the new sketch object
radiusPrecision(-1): If <0, disable radius constraint. If =0, add indiviaul
    radius constraint. If >0, the radius will be rounded according to this
    precision, and 'Equal' constraint will be added to curve with equal
    radius within precision.
References DraftVecUtils.angle(), DraftVecUtils.equals(), and DraftVecUtils.rotate().
Variable Documentation
makeSketch
draftmake.make_sketch.makeSketch = make_sketch