FreeCAD: Gui::PropertyEditor::LinkListLabel Class Reference
Gui::PropertyEditor::LinkListLabel Class Reference
#include <PropertyItem.h>
Signals
void linkChanged (const QVariantList &)
Public Member Functions
LinkListLabel (QWidget *parent=0)
QVariantList propertyLinkList () const
void setPropertyLinkList (const QVariantList &o)
virtual ~LinkListLabel ()
Protected Slots
void onEditClicked ()
Protected Member Functions
void resizeEvent (QResizeEvent *)
Constructor & Destructor Documentation
LinkListLabel()
LinkListLabel::LinkListLabel (QWidget * parent = 0)
References DraftGeomUtils::connect(), and onEditClicked().
Referenced by Gui::PropertyEditor::PropertyLinkListItem::setValue().
~LinkListLabel()
LinkListLabel::~LinkListLabel () virtual
Member Function Documentation
linkChanged
void Gui::PropertyEditor::LinkListLabel::linkChanged (const QVariantList &) signal
Referenced by onEditClicked(), and Gui::PropertyEditor::PropertyLinkListItem::setValue().
onEditClicked
void LinkListLabel::onEditClicked () protected slot
References linkChanged(), Gui::Dialog::DlgPropertyLink::propertyLinkList(), setPropertyLinkList(), and Gui::Dialog::DlgPropertyLink::setSelectionMode().
Referenced by LinkListLabel().
propertyLinkList()
QVariantList LinkListLabel::propertyLinkList () const
Referenced by Gui::PropertyEditor::PropertyLinkListItem::setValue().
resizeEvent()
void LinkListLabel::resizeEvent (QResizeEvent * e) protected
setPropertyLinkList()
void LinkListLabel::setPropertyLinkList (const QVariantList & o)
Referenced by onEditClicked(), and Gui::PropertyEditor::PropertyLinkListItem::setValue().
The documentation for this class was generated from the following files:
src/Gui/propertyeditor/PropertyItem.h
src/Gui/propertyeditor/PropertyItem.cpp