FreeCAD: getSVG Namespace Reference
getSVG Namespace Reference
Functions
def getDiscretized (edge, plane)
def getLineStyle (linestyle, scale)
def getPattern (pat)
def getProj (vec, plane)
def getSVG (obj, scale=1, linewidth=0.35, fontsize=12, fillstyle="shape color", direction=None, linestyle=None, color=None, linespacing=None, techdraw=False, rotation=0, fillSpaces=False, override=True)
Function Documentation
getDiscretized()
def getSVG.getDiscretized (edge, plane)
References getProj().
Referenced by getSVG().
getLineStyle()
def getSVG.getLineStyle (linestyle, scale)
Referenced by getSVG().
getPattern()
def getSVG.getPattern (pat)
Referenced by getSVG().
getProj()
def getSVG.getProj (vec, plane)
References DraftVecUtils.project().
Referenced by getDiscretized(), and getSVG().
getSVG()
def getSVG.getSVG (obj, scale = 1, linewidth = 0.35, fontsize = 12, fillstyle = "shape color", direction = None, linestyle = None, color = None, linespacing = None, techdraw = False, rotation = 0, fillSpaces = False, override = True)
getSVG(object,[scale], [linewidth],[fontsize],[fillstyle],[direction],[linestyle],[color],[linespacing]):
returns a string containing a SVG representation of the given object,
with the given linewidth and fontsize (used if the given object contains
any text). You can also supply an arbitrary projection vector. the
scale parameter allows to scale linewidths down, so they are resolution-independant.
References DraftVecUtils.angle(), getDiscretized(), getLineStyle(), getPattern(), getProj(), WorkingPlane.plane, DraftVecUtils.rotate(), and DraftVecUtils.scaleTo().