FreeCAD: Base::ConsoleSingleton Class Reference
Base::ConsoleSingleton Class Reference
The console class This class manage all the stdio stuff.
#include <Console.h>
Public Types
enum ConnectionMode { Direct = 0, Queued =1 }
enum ConsoleMode { Verbose = 1 }
enumaration for the console modes
enum FreeCAD_ConsoleMsgType { MsgType_Txt = 1, MsgType_Log = 2, MsgType_Wrn = 4, MsgType_Err = 8 }
Public Member Functions
void AttachObserver (ILogger *pcObserver)
Attaches an Observer to FCConsole.
void DetachObserver (ILogger *pcObserver)
Detaches an Observer from FCConsole.
void EnableRefresh (bool enable)
virtual void Error (const char *pMsg,...)
Prints a error Message.
ILogger * Get (const char *Name) const
int * GetLogLevel (const char *tag, bool create=true)
bool IsMsgTypeEnabled (const char *sObs, FreeCAD_ConsoleMsgType type) const
Enables or disables message types of a certain console observer.
virtual void Log (const char *pMsg,...)
Prints a log Message.
int LogLevel (int level) const
virtual void Message (const char *pMsg,...)
Prints a Message.
void NotifyError (const char *sMsg)
void NotifyLog (const char *sMsg)
void NotifyMessage (const char *sMsg)
void NotifyWarning (const char *sMsg)
void Refresh ()
void SetConnectionMode (ConnectionMode mode)
void SetConsoleMode (ConsoleMode m)
Change mode.
void SetDefaultLogLevel (int level)
ConsoleMsgFlags SetEnabledMsgType (const char *sObs, ConsoleMsgFlags type, bool b)
Enables or disables message types of a certain console observer.
const char * Time (void)
Delivers a time/date string.
void UnsetConsoleMode (ConsoleMode m)
Change mode.
virtual void Warning (const char *pMsg,...)
Prints a warning Message.
Static Public Member Functions
static ConsoleSingleton & Instance (void)
singleton
Static Public Attributes
static const unsigned int BufferSize = 4024
static PyMethodDef Methods []
Protected Member Functions
ConsoleSingleton (void)
virtual ~ConsoleSingleton ()
Static Protected Member Functions
static PyObject * sPyError (PyObject *self, PyObject *args)
static PyObject * sPyGetStatus (PyObject *self, PyObject *args)
static PyObject * sPyLog (PyObject *self, PyObject *args)
static PyObject * sPyMessage (PyObject *self, PyObject *args)
static PyObject * sPySetStatus (PyObject *self, PyObject *args)
static PyObject * sPyWarning (PyObject *self, PyObject *args)
Protected Attributes
ConnectionMode connectionMode
Friends
class ConsoleOutput
Detailed Description
The console class This class manage all the stdio stuff.
This includes Messages, Warnings, Log entries and Errors. The incoming Messages are distributed with the FCConsoleObserver. The FCConsole class itself makes no IO, it's more like a manager.
ConsoleSingleton is a singleton! That means you can access the only instance of the class from every where in c++ by simply using:
#include <Base/Console.h>
Base::Console().Log("Stage: %d",i);
ConsoleSingleton is able to switch between several modes to, e.g. switch the logging on or off, or treat Warnings as Errors, and so on...
See also
ConsoleObserver
Member Enumeration Documentation
ConnectionMode
enum Base::ConsoleSingleton::ConnectionMode
Enumerator
Direct
Queued
ConsoleMode
enum Base::ConsoleSingleton::ConsoleMode
enumaration for the console modes
Enumerator
Verbose
FreeCAD_ConsoleMsgType
enum Base::ConsoleSingleton::FreeCAD_ConsoleMsgType
Enumerator
MsgType_Txt
MsgType_Log
MsgType_Wrn
MsgType_Err
Constructor & Destructor Documentation
ConsoleSingleton()
ConsoleSingleton::ConsoleSingleton (void) protected
References Base::ConsoleOutput::getInstance().
Referenced by Instance().
~ConsoleSingleton()
ConsoleSingleton::~ConsoleSingleton () protected virtual
References Base::ConsoleOutput::destruct().
Member Function Documentation
AttachObserver()
void ConsoleSingleton::AttachObserver (ILogger * pcObserver)
Attaches an Observer to FCConsole.
Attaches an Observer to Console Use this method to attach a ILogger derived class to the Console.
After the observer is attached all messages will also be forwarded to it.
See also
ILogger
Referenced by CmdTestConsoleOutput::activated(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::SplashObserver::SplashObserver(), and Gui::StatusBarObserver::StatusBarObserver().
DetachObserver()
void ConsoleSingleton::DetachObserver (ILogger * pcObserver)
Detaches an Observer from FCConsole.
Detaches an Observer from Console Use this method to detach a ILogger derived class.
After detaching you can destruct the Observer or reinsert it later.
See also
ILogger
Referenced by CmdTestConsoleOutput::activated(), App::Application::destructObserver(), Gui::DockWnd::ReportOutput::~ReportOutput(), Gui::SplashObserver::~SplashObserver(), and Gui::StatusBarObserver::~StatusBarObserver().
EnableRefresh()
void ConsoleSingleton::EnableRefresh (bool enable)
Referenced by Base::ConsoleRefreshDisabler::ConsoleRefreshDisabler(), and Base::ConsoleRefreshDisabler::~ConsoleRefreshDisabler().
Error()
void ConsoleSingleton::Error (const char * pMsg, ...) virtual
Prints a error Message.
Prints a Message This method issues an Error which makes some execution impossible.
Errors are used to get the users attention. That means when FreeCAD is running in GUI mode an Error Message Box pops up. In console mode a colored message is printed to the console! Don't use this carelessly. For information purposes the 'Log' or 'Message' methods are more appropriate.
You can use a printf like interface like:
Console().Error("Something really bad in %s happened\n",str);
See also
Message
Warning
Log
Referenced by ReverseEngineeringGui::Segmentation::accept(), MeshPartGui::Tessellation::accept(), TechDrawGui::TaskWeldingSymbol::accept(), Gui::StdCmdDownloadOnlineHelp::activated(), Gui::PythonCommand::activated(), CmdTestConsoleOutput::activated(), Gui::PythonGroupCommand::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), Gui::Application::activateWorkbench(), Sketcher::Sketch::addAngleAtPointConstraint(), TechDraw::DrawViewPart::addCenterLinesToGeom(), Sketcher::Sketch::addConstraints(), Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addExternal(), TechDraw::DrawProjGroup::addProjection(), Sketcher::Sketch::addSnellsLawConstraint(), Sketcher::SketchObject::addSymmetric(), Sketcher::Sketch::addTangentConstraint(), Gui::CommandManager::addTo(), TechDraw::DrawViewClipPy::addView(), TechDrawGui::QGVPage::addWeldSymbol(), Measure::Measurement::angle(), TechDraw::AOE::AOE(), TechDrawGui::TaskSectionView::apply(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::BaseGeom::baseFactory(), TechDrawGui::QGIFace::buildPixHatch(), TechDraw::CenterLine::calcEndPoints(), Sketcher::SketchObject::carbonCopy(), SurfaceGui::GeomFillSurface::changeFillType(), ParameterManager::CheckDocument(), Cloud::Module::cloudRestore(), Gui::cmdAppObjectShow(), Gui::MacroManager::commit(), TechDrawGui::QGIViewDimension::constructDimensionArc(), TechDrawGui::QGIViewDimension::constructDimensionLine(), Sketcher::SketchObject::convertToNURBS(), TechDrawGui::Grabber3d::copyActiveViewToSvgFile(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::QGISVGTemplate::createClickHandles(), Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createPrefWidget(), Gui::WidgetFactoryInst::createWidget(), Sketcher::SketchObject::delAllExternal(), Sketcher::SketchObject::delExternal(), Measure::Measurement::delta(), Base::Subject< const char * >::Detach(), PartGui::ViewProviderPart::doubleClicked(), FemGui::ViewProviderFemPostObject::doubleClicked(), SketcherGui::ViewProviderSketch::draw(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawRadiusExecutive(), TechDrawGui::TaskDetail::editByHighlight(), SpreadsheetGui::SheetView::editingFinished(), Gui::ViewProvider::eventCallback(), TechDraw::DrawViewDetail::execute(), Import::FeatureImportStep::Execute(), Import::FeatureImportIges::Execute(), TechDraw::DrawViewSection::execute(), TechDraw::DrawSVGTemplate::execute(), Sketcher::SketchObject::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewDimension::execute(), Part::AttachExtension::extensionOnChanged(), PartDesignGui::TaskTransformedParameters::fillAxisCombo(), PartDesignGui::TaskTransformedParameters::fillPlanesCombo(), TechDrawGui::QGIViewPart::geomToPainterPath(), TechDraw::DrawGeomHatch::getDecodedSpecsFromFile(), TechDraw::DrawProjGroup::getDirsFromFront(), TechDraw::DrawSVGTemplatePy::getEditFieldContent(), TechDraw::DrawGeomHatch::getParameters(), TechDraw::DrawViewDimension::getPointsEdgeVert(), TechDraw::DrawViewDimension::getPointsOneEdge(), TechDraw::DrawViewDimension::getPointsTwoEdges(), TechDraw::DrawViewDimension::getPointsTwoVerts(), TechDraw::ShapeExtractor::getShapes(), TechDraw::ShapeExtractor::getShapesFused(), TechDraw::DrawViewSpreadsheet::getSheetImage(), TechDraw::DrawViewPart::getSourceShape(), TechDraw::DrawViewPart::getSourceShapeFused(), Fem::FemVTKTools::importVTKMesh(), Sketcher::SketchObject::increaseBSplineDegree(), Gui::Application::initApplication(), Gui::Command::invoke(), TechDraw::DrawProjectSplit::isOnEdge(), Measure::Measurement::length(), StartGui::Workbench::loadStartPage(), TechDrawGui::QGIFace::loadSvgHatch(), TechDrawGui::QGITile::makeSymbol(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), Measure::Measurement::massCenter(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), Gui::GUIApplication::notify(), Gui::ViewProviderOrigin::onChanged(), SketcherGui::ViewProviderSketch::onDelete(), Gui::GestureNavigationStyle::onRollGesture(), DrawSketchHandlerExternal::onSelectionChanged(), DrawSketchHandlerCarbonCopy::onSelectionChanged(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::TaskLeaderLine::onTrackerFinished(), App::Application::openDocuments(), Gui::Dialog::PreferenceUiForm::PreferenceUiForm(), DrawSketchHandlerBSpline::pressButton(), App::Application::processCmdLineFiles(), App::Application::processFiles(), TechDraw::GeometryObject::projectShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), Measure::Measurement::radius(), Base::XMLReader::readFiles(), App::Document::readObjects(), App::Document::recompute(), PartDesignGui::ViewProviderTransformed::recomputeFeature(), DrawSketchHandlerLine::releaseButton(), DrawSketchHandlerBox::releaseButton(), DrawSketchHandlerLineSet::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerArc::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), DrawSketchHandler3PointArc::releaseButton(), DrawSketchHandlerCircle::releaseButton(), DrawSketchHandlerArcOfEllipse::releaseButton(), DrawSketchHandlerArcOfHyperbola::releaseButton(), DrawSketchHandlerArcOfParabola::releaseButton(), DrawSketchHandlerBSpline::releaseButton(), DrawSketchHandler3PointCircle::releaseButton(), DrawSketchHandlerPoint::releaseButton(), DrawSketchHandlerFillet::releaseButton(), DrawSketchHandlerTrimming::releaseButton(), DrawSketchHandlerExtend::releaseButton(), DrawSketchHandlerSlot::releaseButton(), DrawSketchHandlerRegularPolygon::releaseButton(), TechDraw::DrawViewClipPy::removeView(), Base::PyException::ReportException(), TechDraw::PropertyCenterLineList::Restore(), Part::PropertyGeometryList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), TechDraw::PropertyGeomFormatList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), Part::Primitive::Restore(), PartDesign::Fillet::Restore(), PartDesign::Chamfer::Restore(), PartDesign::ProfileBased::Restore(), PartDesign::Transformed::Restore(), App::Document::restore(), App::PropertyContainer::Restore(), Fem::PropertyPostDataObject::RestoreDocFile(), Part::PropertyPartShape::RestoreDocFile(), Gui::Document::RestoreDocFile(), App::ExtensionContainer::restoreExtensions(), Sandbox::PythonThread::run(), Gui::ConsoleErrorTask::run(), Gui::Application::runApplication(), TechDraw::CenterLine::Save(), App::PropertyContainer::Save(), Fem::PropertyPostDataObject::SaveDocFile(), Part::PropertyPartShape::SaveDocFile(), App::ExtensionContainer::saveExtensions(), TechDraw::CenterLine::scaledGeometry(), SketcherGui::ViewProviderSketch::setEdit(), TechDraw::DrawSVGTemplatePy::setEditFieldContent(), SketcherGui::ViewProviderSketch::setEditViewer(), Gui::PropertyEditor::PropertyItem::setPropertyValue(), Gui::ViewProviderOrigin::setTemporaryVisibility(), Gui::Application::sExport(), Gui::Application::sInsert(), Gui::Application::sOpen(), sPyError(), Gui::NetworkRetriever::startDownload(), Part::TopoShapePy::staticCallback___getstate__(), Part::BSplineCurvePy::staticCallback___reduce__(), Base::VectorPy::staticCallback___reduce__(), Part::TopoShapePy::staticCallback___setstate__(), Path::AreaPy::staticCallback_abort(), App::DocumentPy::staticCallback_abortTransaction(), Gui::WorkbenchPy::staticCallback_activate(), Gui::DocumentPy::staticCallback_activeObject(), Gui::DocumentPy::staticCallback_activeView(), Part::TopoShapeCompoundPy::staticCallback_add(), Part::TopoShapeCompSolidPy::staticCallback_add(), Path::AreaPy::staticCallback_add(), Part::TopoShapeShellPy::staticCallback_add(), Part::TopoShapeWirePy::staticCallback_add(), Base::VectorPy::staticCallback_add(), Base::BoundBoxPy::staticCallback_add(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_add(), Gui::DocumentPy::staticCallback_addAnnotation(), Path::PathPy::staticCallback_addCommands(), Sketcher::SketchPy::staticCallback_addConstraint(), Sketcher::SketchObjectPy::staticCallback_addConstraint(), Sketcher::SketchObjectPy::staticCallback_addCopy(), Gui::ViewProviderPy::staticCallback_addDisplayMode(), Fem::FemMeshPy::staticCallback_addEdge(), App::ExtensionContainerPy::staticCallback_addExtension(), Sketcher::SketchObjectPy::staticCallback_addExternal(), Fem::FemMeshPy::staticCallback_addFace(), Mesh::MeshPy::staticCallback_addFacet(), Mesh::MeshPy::staticCallback_addFacets(), Sketcher::SketchObjectPy::staticCallback_addGeometry(), Sketcher::SketchPy::staticCallback_addGeometry(), Fem::FemMeshPy::staticCallback_addHypothesis(), Mesh::MeshPy::staticCallback_addMesh(), Sketcher::SketchObjectPy::staticCallback_addMove(), Fem::FemMeshPy::staticCallback_addNode(), Path::FeaturePathCompoundPy::staticCallback_addObject(), App::GroupExtensionPy::staticCallback_addObject(), App::DocumentPy::staticCallback_addObject(), App::GroupExtensionPy::staticCallback_addObjects(), Points::PointsPy::staticCallback_addPoints(), TechDraw::DrawProjGroupPy::staticCallback_addProjection(), App::DocumentObjectPy::staticCallback_addProperty(), Gui::ViewProviderPy::staticCallback_addProperty(), Fem::FemMeshPy::staticCallback_addQuad(), Sketcher::SketchObjectPy::staticCallback_addRectangularArray(), Measure::MeasurementPy::staticCallback_addReference3D(), MeshGui::ViewProviderMeshPy::staticCallback_addSelection(), Sketcher::SketchObjectPy::staticCallback_addSymmetric(), Path::TooltablePy::staticCallback_addTools(), TechDraw::DrawPagePy::staticCallback_addView(), TechDraw::DrawViewClipPy::staticCallback_addView(), TechDraw::DrawViewCollectionPy::staticCallback_addView(), Fem::FemMeshPy::staticCallback_addVolume(), Sketcher::SketchObjectPy::staticCallback_analyseMissingPointOnPointCoincident(), Base::MatrixPy::staticCallback_analyze(), Part::TopoShapePy::staticCallback_ancestorsOfType(), Measure::MeasurementPy::staticCallback_angle(), Gui::PythonWorkbenchPy::staticCallback_appendCommandbar(), Gui::PythonWorkbenchPy::staticCallback_AppendCommandbar(), Gui::PythonWorkbenchPy::staticCallback_appendContextMenu(), Gui::PythonWorkbenchPy::staticCallback_AppendContextMenu(), Gui::PythonWorkbenchPy::staticCallback_appendMenu(), Gui::PythonWorkbenchPy::staticCallback_AppendMenu(), Gui::PythonWorkbenchPy::staticCallback_appendToolbar(), Gui::PythonWorkbenchPy::staticCallback_AppendToolbar(), PathSimulator::PathSimPy::staticCallback_ApplyCommand(), FemGui::ViewProviderFemMeshPy::staticCallback_applyDisplacement(), Part::TopoShapeWirePy::staticCallback_approximate(), Part::BSplineCurve2dPy::staticCallback_approximate(), Part::BSplineCurvePy::staticCallback_approximate(), Part::BSplineSurfacePy::staticCallback_approximate(), Part::Curve2dPy::staticCallback_approximateBSpline(), Part::GeometryCurvePy::staticCallback_approximateBSpline(), Sketcher::SketchObjectPy::staticCallback_autoconstraint(), TechDraw::DrawProjGroupItemPy::staticCallback_autoPosition(), Sketcher::SketchObjectPy::staticCallback_autoRemoveRedundants(), PathSimulator::PathSimPy::staticCallback_BeginSimulation(), Part::BezierSurfacePy::staticCallback_bounds(), Part::BSplineSurfacePy::staticCallback_bounds(), Part::GeometrySurfacePy::staticCallback_bounds(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_build(), Part::BSplineCurve2dPy::staticCallback_buildFromPoles(), Part::BSplineCurvePy::staticCallback_buildFromPoles(), Part::BSplineCurve2dPy::staticCallback_buildFromPolesMultsKnots(), Part::BSplineCurvePy::staticCallback_buildFromPolesMultsKnots(), Part::BSplineSurfacePy::staticCallback_buildFromPolesMultsKnots(), Sketcher::SketchObjectPy::staticCallback_calculateAngleViaPoint(), Attacher::AttachEnginePy::staticCallback_calculateAttachedPlacement(), Sketcher::SketchObjectPy::staticCallback_calculateConstraintError(), Sketcher::SketchObjectPy::staticCallback_carbonCopy(), Part::Curve2dPy::staticCallback_centerOfCurvature(), Part::GeometryCurvePy::staticCallback_centerOfCurvature(), Part::TopoShapeEdgePy::staticCallback_centerOfCurvatureAt(), Part::AttachExtensionPy::staticCallback_changeAttacherType(), Sketcher::SketchObjectPy::staticCallback_changeConstraintsLocking(), Robot::Robot6AxisPy::staticCallback_check(), Part::TopoShapePy::staticCallback_check(), Part::TopoShapePy::staticCallback_childShapes(), Gui::ViewProviderPy::staticCallback_claimChildren(), Part::TopoShapePy::staticCallback_cleaned(), Measure::MeasurementPy::staticCallback_clear(), Sketcher::SketchPy::staticCallback_clear(), Spreadsheet::SheetPy::staticCallback_clear(), Mesh::MeshPy::staticCallback_clear(), Spreadsheet::SheetPy::staticCallback_clearAll(), TechDraw::DrawViewPartPy::staticCallback_clearCenterLines(), TechDraw::DrawViewPartPy::staticCallback_clearCosmeticEdges(), TechDraw::DrawViewPartPy::staticCallback_clearCosmeticVertices(), TechDraw::DrawViewPartPy::staticCallback_clearGeomFormats(), MeshGui::ViewProviderMeshPy::staticCallback_clearSelection(), App::DocumentPy::staticCallback_clearUndos(), TechDraw::CenterLinePy::staticCallback_clone(), TechDraw::CosmeticEdgePy::staticCallback_clone(), TechDraw::CosmeticVertexPy::staticCallback_clone(), TechDraw::GeomFormatPy::staticCallback_clone(), Part::GeometryPy::staticCallback_clone(), Base::BoundBoxPy::staticCallback_closestPoint(), Mesh::MeshPy::staticCallback_coarsen(), Mesh::MeshPy::staticCallback_collapseEdge(), Mesh::MeshPy::staticCallback_collapseFacet(), Mesh::MeshPy::staticCallback_collapseFacets(), Measure::MeasurementPy::staticCallback_com(), App::DocumentPy::staticCallback_commitTransaction(), Part::TopoShapePy::staticCallback_common(), Part::TopoShapePy::staticCallback_complement(), Part::ParabolaPy::staticCallback_compute(), Fem::FemMeshPy::staticCallback_compute(), Part::TopoShapeCompoundPy::staticCallback_connectEdgesToWires(), Sketcher::SketchObjectPy::staticCallback_convertToNURBS(), Base::AxisPy::staticCallback_copy(), Part::GeometryExtensionPy::staticCallback_copy(), Path::ToolPy::staticCallback_copy(), Path::TooltablePy::staticCallback_copy(), Points::PointsPy::staticCallback_copy(), Base::PlacementPy::staticCallback_copy(), TechDraw::CenterLinePy::staticCallback_copy(), TechDraw::CosmeticEdgePy::staticCallback_copy(), TechDraw::CosmeticVertexPy::staticCallback_copy(), TechDraw::GeomFormatPy::staticCallback_copy(), Mesh::MeshPy::staticCallback_copy(), Part::Geometry2dPy::staticCallback_copy(), Part::GeometryPy::staticCallback_copy(), Attacher::AttachEnginePy::staticCallback_copy(), Path::PathPy::staticCallback_copy(), Fem::FemMeshPy::staticCallback_copy(), Part::TopoShapePy::staticCallback_copy(), App::DocumentPy::staticCallback_copyObject(), Mesh::MeshPy::staticCallback_countComponents(), Mesh::MeshFeaturePy::staticCallback_countFacets(), Mesh::MeshPy::staticCallback_countNonUniformOrientedFacets(), Mesh::MeshFeaturePy::staticCallback_countPoints(), Mesh::MeshPy::staticCallback_countSegments(), Base::VectorPy::staticCallback_cross(), Mesh::MeshPy::staticCallback_crossSections(), Part::GeometrySurfacePy::staticCallback_curvature(), Part::Curve2dPy::staticCallback_curvature(), Part::GeometryCurvePy::staticCallback_curvature(), Part::TopoShapeFacePy::staticCallback_curvatureAt(), Part::TopoShapeEdgePy::staticCallback_curvatureAt(), Part::GeometrySurfacePy::staticCallback_curvatureDirections(), Part::TopoShapeFacePy::staticCallback_curveOnSurface(), Part::TopoShapePy::staticCallback_cut(), Mesh::MeshPy::staticCallback_cut(), Part::TopoShapeFacePy::staticCallback_cutHoles(), Mesh::MeshPy::staticCallback_decimate(), Part::TopoShapePy::staticCallback_defeaturing(), Sketcher::SketchObjectPy::staticCallback_delConstraint(), Sketcher::SketchObjectPy::staticCallback_delConstraintOnPoint(), Sketcher::SketchObjectPy::staticCallback_deleteAllConstraints(), Sketcher::SketchObjectPy::staticCallback_deleteAllGeometry(), Path::PathPy::staticCallback_deleteCommand(), Part::GeometryPy::staticCallback_deleteExtensionOfName(), Part::GeometryPy::staticCallback_deleteExtensionOfType(), Robot::TrajectoryPy::staticCallback_deleteLast(), Path::TooltablePy::staticCallback_deleteTool(), Sketcher::SketchObjectPy::staticCallback_DeleteUnusedInternalGeometry(), Sketcher::SketchObjectPy::staticCallback_deleteUnusedInternalGeometry(), Sketcher::SketchObjectPy::staticCallback_delExternal(), Sketcher::SketchObjectPy::staticCallback_delGeometry(), Measure::MeasurementPy::staticCallback_delta(), Part::TopoShapeFacePy::staticCallback_derivative1At(), Part::TopoShapeEdgePy::staticCallback_derivative1At(), Part::TopoShapeFacePy::staticCallback_derivative2At(), Part::TopoShapeEdgePy::staticCallback_derivative2At(), Part::TopoShapeEdgePy::staticCallback_derivative3At(), Sketcher::SketchObjectPy::staticCallback_detectMissingEqualityConstraints(), Sketcher::SketchObjectPy::staticCallback_detectMissingPointOnPointConstraints(), Sketcher::SketchObjectPy::staticCallback_detectMissingVerticalHorizontalConstraints(), Base::MatrixPy::staticCallback_determinant(), Mesh::MeshPy::staticCallback_difference(), Part::GeometryCurvePy::staticCallback_discretize(), Part::Curve2dPy::staticCallback_discretize(), Part::TopoShapeWirePy::staticCallback_discretize(), Part::TopoShapeEdgePy::staticCallback_discretize(), Base::CoordinateSystemPy::staticCallback_displacement(), Base::VectorPy::staticCallback_distanceToLine(), Base::VectorPy::staticCallback_distanceToLineSegment(), Base::VectorPy::staticCallback_distanceToPlane(), Base::VectorPy::staticCallback_distanceToPoint(), Part::TopoShapePy::staticCallback_distToShape(), Base::VectorPy::staticCallback_dot(), Attacher::AttachEnginePy::staticCallback_downgradeRefType(), TechDraw::DrawParametricTemplatePy::staticCallback_drawLine(), Base::PersistencePy::staticCallback_dumpContent(), App::PropertyContainerPy::staticCallback_dumpPropertyContent(), TechDraw::DrawViewSymbolPy::staticCallback_dumpSymbol(), Part::TopoShapePy::staticCallback_dumpToString(), App::DocumentObjectPy::staticCallback_enforceRecompute(), Base::BoundBoxPy::staticCallback_enlarge(), Part::BezierSurfacePy::staticCallback_exchangeUV(), Part::BSplineSurfacePy::staticCallback_exchangeUV(), Part::TopoShapePy::staticCallback_exportBinary(), Part::TopoShapePy::staticCallback_exportBrep(), Part::TopoShapePy::staticCallback_exportBrepToString(), Spreadsheet::SheetPy::staticCallback_exportFile(), App::DocumentPy::staticCallback_exportGraphviz(), Part::TopoShapePy::staticCallback_exportIges(), Part::TopoShapePy::staticCallback_exportStep(), Part::TopoShapePy::staticCallback_exportStl(), Sketcher::SketchObjectPy::staticCallback_ExposeInternalGeometry(), Sketcher::SketchObjectPy::staticCallback_exposeInternalGeometry(), Sketcher::SketchObjectPy::staticCallback_extend(), Part::TopoShapePy::staticCallback_extrude(), Sketcher::SketchObjectPy::staticCallback_fillet(), Mesh::MeshPy::staticCallback_fillupHoles(), App::DocumentPy::staticCallback_findObjects(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_firstShape(), Part::TopoShapeEdgePy::staticCallback_firstVertex(), Part::TopoShapePy::staticCallback_fix(), Mesh::MeshPy::staticCallback_fixCaps(), Mesh::MeshPy::staticCallback_fixDeformations(), Mesh::MeshFeaturePy::staticCallback_fixDegenerations(), Mesh::MeshPy::staticCallback_fixDegenerations(), Mesh::MeshFeaturePy::staticCallback_fixIndices(), Mesh::MeshPy::staticCallback_fixIndices(), Mesh::MeshFeaturePy::staticCallback_fixSelfIntersections(), Mesh::MeshPy::staticCallback_fixSelfIntersections(), Part::TopoShapePy::staticCallback_fixTolerance(), Part::TopoShapeWirePy::staticCallback_fixWire(), Mesh::MeshPy::staticCallback_flipNormals(), Mesh::MeshPy::staticCallback_foraminate(), Points::PointsPy::staticCallback_fromSegment(), Points::PointsPy::staticCallback_fromValid(), Part::TopoShapePy::staticCallback_fuse(), Part::TopoShapePy::staticCallback_generalFuse(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_generated(), Spreadsheet::SheetPy::staticCallback_get(), Sketcher::SketchObjectPy::staticCallback_getActive(), Spreadsheet::SheetPy::staticCallback_getAlias(), Spreadsheet::SheetPy::staticCallback_getAlignment(), Base::BaseClassPy::staticCallback_getAllDerivedFrom(), TechDraw::DrawPagePy::staticCallback_getAllViews(), Base::VectorPy::staticCallback_getAngle(), TechDraw::DrawViewDimensionPy::staticCallback_getAnglePoints(), TechDraw::DrawViewDimensionPy::staticCallback_getArcPoints(), Path::FeatureAreaPy::staticCallback_getArea(), Sketcher::SketchObjectPy::staticCallback_getAxis(), Spreadsheet::SheetPy::staticCallback_getBackground(), Part::TopoShapeShellPy::staticCallback_getBadEdges(), PartDesign::FeaturePy::staticCallback_getBaseObject(), Part::BSplineCurve2dPy::staticCallback_getCardinalSplineTangents(), Part::BSplineCurvePy::staticCallback_getCardinalSplineTangents(), Fem::FemMeshPy::staticCallback_getccxVolumesByFace(), Spreadsheet::SheetPy::staticCallback_getCellFromAlias(), TechDraw::DrawViewClipPy::staticCallback_getChildViewNames(), Spreadsheet::SheetPy::staticCallback_getColumnWidth(), Spreadsheet::SheetPy::staticCallback_getContents(), TechDraw::DrawViewPartPy::staticCallback_getCosmeticEdgeByIndex(), TechDraw::DrawViewPartPy::staticCallback_getCosmeticVertexByIndex(), Sketcher::SketchObjectPy::staticCallback_getDatum(), Path::AreaPy::staticCallback_getDefaultParams(), Spreadsheet::SheetPy::staticCallback_getDisplayUnit(), App::PropertyContainerPy::staticCallback_getDocumentationOfProperty(), Sketcher::SketchObjectPy::staticCallback_getDriving(), Base::BoundBoxPy::staticCallback_getEdge(), Fem::FemMeshPy::staticCallback_getEdgesByEdge(), TechDraw::DrawSVGTemplatePy::staticCallback_getEditFieldContent(), App::PropertyContainerPy::staticCallback_getEditorMode(), Mesh::MeshPy::staticCallback_getEigenSystem(), Part::TopoShapePy::staticCallback_getElement(), Fem::FemMeshPy::staticCallback_getElementNodes(), Fem::FemMeshPy::staticCallback_getElementType(), Part::GeometryPy::staticCallback_getExtensionOfName(), Part::GeometryPy::staticCallback_getExtensionOfType(), Part::GeometryPy::staticCallback_getExtensions(), Fem::FemMeshPy::staticCallback_getFacesByFace(), Data::ComplexGeoDataPy::staticCallback_getFacesFromSubelement(), Mesh::MeshPy::staticCallback_getFacetSelection(), Spreadsheet::SheetPy::staticCallback_getForeground(), Part::TopoShapeShellPy::staticCallback_getFreeEdges(), Sketcher::SketchObjectPy::staticCallback_getGeometryWithDependentParameters(), App::GeoFeaturePy::staticCallback_getGlobalPlacement(), Fem::FemMeshPy::staticCallback_getGroupElements(), Fem::FemMeshPy::staticCallback_getGroupElementType(), Fem::FemMeshPy::staticCallback_getGroupName(), App::PropertyContainerPy::staticCallback_getGroupOfProperty(), Fem::FemMeshPy::staticCallback_getIdByElementType(), Gui::DocumentPy::staticCallback_getInEdit(), Mesh::MeshPy::staticCallback_getInternalFacets(), Base::BoundBoxPy::staticCallback_getIntersectionPoint(), TechDraw::DrawProjGroupPy::staticCallback_getItemByLabel(), Part::BSplineCurve2dPy::staticCallback_getKnot(), Part::BSplineCurvePy::staticCallback_getKnot(), Part::BSplineCurve2dPy::staticCallback_getKnots(), Part::BSplineCurvePy::staticCallback_getKnots(), Fem::FemPostPipelinePy::staticCallback_getLastPostObject(), TechDraw::DrawViewDimensionPy::staticCallback_getLinearPoints(), Attacher::AttachEnginePy::staticCallback_getModeInfo(), Part::TopoShapeSolidPy::staticCallback_getMomentOfInertia(), Part::BSplineCurve2dPy::staticCallback_getMultiplicities(), Part::BSplineCurvePy::staticCallback_getMultiplicities(), Part::BSplineCurve2dPy::staticCallback_getMultiplicity(), Part::BSplineCurvePy::staticCallback_getMultiplicity(), Fem::FemMeshPy::staticCallback_getNodeById(), Fem::FemMeshPy::staticCallback_getNodesByEdge(), Fem::FemMeshPy::staticCallback_getNodesByFace(), Fem::FemMeshPy::staticCallback_getNodesBySolid(), Fem::FemMeshPy::staticCallback_getNodesByVertex(), Mesh::MeshPy::staticCallback_getNonUniformOrientedFacets(), App::GroupExtensionPy::staticCallback_getObject(), Gui::DocumentPy::staticCallback_getObject(), App::DocumentPy::staticCallback_getObject(), App::DocumentPy::staticCallback_getObjectsByLabel(), TechDraw::DrawPagePy::staticCallback_getPageHeight(), TechDraw::DrawPagePy::staticCallback_getPageOrientation(), TechDraw::DrawPagePy::staticCallback_getPageWidth(), Part::TopoShapeEdgePy::staticCallback_getParameterByLength(), Path::AreaPy::staticCallback_getParams(), Path::AreaPy::staticCallback_getParamsDesc(), App::DocumentObjectPy::staticCallback_getParentGeoFeatureGroup(), App::DocumentObjectPy::staticCallback_getParentGroup(), App::GeoFeaturePy::staticCallback_getPaths(), App::DocumentObjectPy::staticCallback_getPathsByOutList(), Mesh::MeshPy::staticCallback_getPlanarSegments(), Base::BoundBoxPy::staticCallback_getPoint(), Sketcher::SketchObjectPy::staticCallback_getPoint(), Mesh::MeshPy::staticCallback_getPointNormals(), Mesh::MeshPy::staticCallback_getPointSelection(), Part::BezierCurve2dPy::staticCallback_getPole(), Part::BezierCurvePy::staticCallback_getPole(), Part::BSplineCurve2dPy::staticCallback_getPole(), Part::BSplineCurvePy::staticCallback_getPole(), Part::BezierSurfacePy::staticCallback_getPole(), Part::BSplineSurfacePy::staticCallback_getPole(), Part::BezierCurve2dPy::staticCallback_getPoles(), Part::BezierCurvePy::staticCallback_getPoles(), Part::BSplineCurve2dPy::staticCallback_getPoles(), Part::BSplineCurvePy::staticCallback_getPoles(), Part::BezierSurfacePy::staticCallback_getPoles(), Part::BSplineSurfacePy::staticCallback_getPoles(), Part::BSplineCurve2dPy::staticCallback_getPolesAndWeights(), Part::BSplineCurvePy::staticCallback_getPolesAndWeights(), Part::BSplineSurfacePy::staticCallback_getPolesAndWeights(), App::PropertyContainerPy::staticCallback_getPropertyByName(), App::GeoFeaturePy::staticCallback_getPropertyNameOfGeometry(), Part::TopoShapeSolidPy::staticCallback_getRadiusOfGyration(), Attacher::AttachEnginePy::staticCallback_getRefTypeInfo(), Attacher::AttachEnginePy::staticCallback_getRefTypeOfShape(), Part::BezierCurve2dPy::staticCallback_getResolution(), Part::BezierCurvePy::staticCallback_getResolution(), Part::BSplineCurve2dPy::staticCallback_getResolution(), Part::BSplineCurvePy::staticCallback_getResolution(), Part::BezierSurfacePy::staticCallback_getResolution(), Part::BSplineSurfacePy::staticCallback_getResolution(), PathSimulator::PathSimPy::staticCallback_GetResultMesh(), Robot::RobotObjectPy::staticCallback_getRobot(), Spreadsheet::SheetPy::staticCallback_getRowHeight(), Mesh::MeshPy::staticCallback_getSegment(), Mesh::MeshPy::staticCallback_getSegmentsByCurvature(), Mesh::MeshPy::staticCallback_getSegmentsOfType(), Mesh::MeshPy::staticCallback_getSelfIntersections(), Mesh::MeshPy::staticCallback_getSeparateComponents(), Path::AreaPy::staticCallback_getShape(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_getStatus(), Spreadsheet::SheetPy::staticCallback_getStyle(), App::DocumentPy::staticCallback_getTempFileName(), TechDraw::DrawViewDimensionPy::staticCallback_getText(), Part::TopoShapePy::staticCallback_getTolerance(), Path::TooltablePy::staticCallback_getTool(), Path::ToolPy::staticCallback_getToolMaterials(), Path::ToolPy::staticCallback_getToolTypes(), App::PropertyContainerPy::staticCallback_getTypeIdOfProperty(), App::PropertyContainerPy::staticCallback_getTypeOfProperty(), Part::BSplineSurfacePy::staticCallback_getUKnot(), Part::BSplineSurfacePy::staticCallback_getUKnots(), Part::BSplineSurfacePy::staticCallback_getUMultiplicities(), Part::BSplineSurfacePy::staticCallback_getUMultiplicity(), Base::QuantityPy::staticCallback_getUserPreferred(), Part::TopoShapeFacePy::staticCallback_getUVNodes(), Base::QuantityPy::staticCallback_getValueAs(), Sketcher::SketchObjectPy::staticCallback_getVirtualSpace(), Part::BSplineSurfacePy::staticCallback_getVKnot(), Part::BSplineSurfacePy::staticCallback_getVKnots(), Part::BSplineSurfacePy::staticCallback_getVMultiplicities(), Part::BSplineSurfacePy::staticCallback_getVMultiplicity(), Fem::FemMeshPy::staticCallback_getVolumesByFace(), Part::BezierCurve2dPy::staticCallback_getWeight(), Part::BezierCurvePy::staticCallback_getWeight(), Part::BSplineCurve2dPy::staticCallback_getWeight(), Part::BSplineCurvePy::staticCallback_getWeight(), Part::BezierSurfacePy::staticCallback_getWeight(), Part::BSplineSurfacePy::staticCallback_getWeight(), Part::BezierCurve2dPy::staticCallback_getWeights(), Part::BezierCurvePy::staticCallback_getWeights(), Part::BSplineCurve2dPy::staticCallback_getWeights(), Part::BSplineCurvePy::staticCallback_getWeights(), Part::BezierSurfacePy::staticCallback_getWeights(), Part::BSplineSurfacePy::staticCallback_getWeights(), TechDraw::DrawProjGroupPy::staticCallback_getXYPosition(), Part::TopoShapePy::staticCallback_globalTolerance(), Mesh::MeshFeaturePy::staticCallback_harmonizeNormals(), Mesh::MeshPy::staticCallback_harmonizeNormals(), Measure::MeasurementPy::staticCallback_has3DReferences(), App::ExtensionContainerPy::staticCallback_hasExtension(), Part::GeometryPy::staticCallback_hasExtensionOfName(), Part::GeometryPy::staticCallback_hasExtensionOfType(), Part::TopoShapePy::staticCallback_hashCode(), Mesh::MeshPy::staticCallback_hasInvalidPoints(), Mesh::MeshPy::staticCallback_hasNonManifolds(), Mesh::MeshPy::staticCallback_hasNonUniformOrientedFacets(), App::GroupExtensionPy::staticCallback_hasObject(), Mesh::MeshPy::staticCallback_hasSelfIntersections(), Gui::DocumentPy::staticCallback_hide(), Gui::ViewProviderPy::staticCallback_hide(), Fem::FemPostPipelinePy::staticCallback_holdsPostObject(), Part::TopoShapePy::staticCallback_importBinary(), Part::TopoShapePy::staticCallback_importBrep(), Part::TopoShapePy::staticCallback_importBrepFromString(), Spreadsheet::SheetPy::staticCallback_importFile(), Part::BezierCurve2dPy::staticCallback_increase(), Part::BezierCurvePy::staticCallback_increase(), Part::BezierSurfacePy::staticCallback_increase(), Sketcher::SketchObjectPy::staticCallback_increaseBSplineDegree(), Part::BSplineCurve2dPy::staticCallback_increaseDegree(), Part::BSplineCurvePy::staticCallback_increaseDegree(), Part::BSplineSurfacePy::staticCallback_increaseDegree(), Part::BSplineCurve2dPy::staticCallback_increaseMultiplicity(), Part::BSplineCurvePy::staticCallback_increaseMultiplicity(), Part::BSplineSurfacePy::staticCallback_increaseUMultiplicity(), Part::BSplineSurfacePy::staticCallback_increaseVMultiplicity(), Part::BSplineCurve2dPy::staticCallback_incrementMultiplicity(), Part::BSplineCurvePy::staticCallback_incrementMultiplicity(), Part::BSplineSurfacePy::staticCallback_incrementUMultiplicity(), Part::BSplineSurfacePy::staticCallback_incrementVMultiplicity(), Mesh::MeshPy::staticCallback_inner(), Spreadsheet::SheetPy::staticCallback_insertColumns(), Path::PathPy::staticCallback_insertCommand(), Part::BSplineCurve2dPy::staticCallback_insertKnot(), Part::BSplineCurvePy::staticCallback_insertKnot(), Part::BSplineCurve2dPy::staticCallback_insertKnots(), Part::BSplineCurvePy::staticCallback_insertKnots(), PartDesign::BodyPy::staticCallback_insertObject(), Part::BezierCurve2dPy::staticCallback_insertPoleAfter(), Part::BezierCurvePy::staticCallback_insertPoleAfter(), Part::BezierCurve2dPy::staticCallback_insertPoleBefore(), Part::BezierCurvePy::staticCallback_insertPoleBefore(), Part::BezierSurfacePy::staticCallback_insertPoleColAfter(), Part::BezierSurfacePy::staticCallback_insertPoleColBefore(), Part::BezierSurfacePy::staticCallback_insertPoleRowAfter(), Part::BezierSurfacePy::staticCallback_insertPoleRowBefore(), Spreadsheet::SheetPy::staticCallback_insertRows(), Part::BSplineSurfacePy::staticCallback_insertUKnot(), Part::BSplineSurfacePy::staticCallback_insertUKnots(), Mesh::MeshPy::staticCallback_insertVertex(), Part::BSplineSurfacePy::staticCallback_insertVKnot(), Part::BSplineSurfacePy::staticCallback_insertVKnots(), Robot::TrajectoryPy::staticCallback_insertWaypoints(), Part::BSplineCurve2dPy::staticCallback_interpolate(), Part::BSplineCurvePy::staticCallback_interpolate(), Part::BSplineSurfacePy::staticCallback_interpolate(), Mesh::FacetPy::staticCallback_intersect(), Base::BoundBoxPy::staticCallback_intersect(), Mesh::MeshPy::staticCallback_intersect(), Part::GeometryCurvePy::staticCallback_intersect(), Part::GeometrySurfacePy::staticCallback_intersect(), Part::GeometryCurvePy::staticCallback_intersect2d(), Part::Curve2dPy::staticCallback_intersectCC(), Part::GeometryCurvePy::staticCallback_intersectCC(), Part::GeometryCurvePy::staticCallback_intersectCS(), Base::BoundBoxPy::staticCallback_intersected(), Part::GeometrySurfacePy::staticCallback_intersectSS(), Part::TopoShapePy::staticCallback_inTolerance(), Base::PlacementPy::staticCallback_inverse(), Base::MatrixPy::staticCallback_inverse(), Base::RotationPy::staticCallback_invert(), Base::MatrixPy::staticCallback_invert(), Base::RotationPy::staticCallback_inverted(), MeshGui::ViewProviderMeshPy::staticCallback_invertSelection(), Part::BezierCurve2dPy::staticCallback_isClosed(), Part::BSplineCurve2dPy::staticCallback_isClosed(), Part::BezierCurvePy::staticCallback_isClosed(), Part::BSplineCurvePy::staticCallback_isClosed(), Part::GeometryCurvePy::staticCallback_isClosed(), Part::TopoShapePy::staticCallback_isClosed(), Base::BoundBoxPy::staticCallback_isCutPlane(), Mesh::FacetPy::staticCallback_isDeformed(), Mesh::FacetPy::staticCallback_isDegenerated(), Base::BaseClassPy::staticCallback_isDerivedFrom(), Base::VectorPy::staticCallback_isEqual(), Part::TopoShapePy::staticCallback_isEqual(), Attacher::AttachEnginePy::staticCallback_isFittingRefType(), Base::PlacementPy::staticCallback_isIdentity(), Base::RotationPy::staticCallback_isIdentity(), Base::BoundBoxPy::staticCallback_isInside(), Part::TopoShapePy::staticCallback_isInside(), Base::RotationPy::staticCallback_isNull(), Part::TopoShapePy::staticCallback_isNull(), Gui::SelectionObjectPy::staticCallback_isObjectTypeOf(), Base::MatrixPy::staticCallback_isOrthogonal(), Part::TopoShapePy::staticCallback_isPartner(), Part::TopoShapeFacePy::staticCallback_isPartOfDomain(), Part::BezierCurve2dPy::staticCallback_isPeriodic(), Part::BSplineCurve2dPy::staticCallback_isPeriodic(), Part::BezierCurvePy::staticCallback_isPeriodic(), Part::BSplineCurvePy::staticCallback_isPeriodic(), Part::GeometryCurvePy::staticCallback_isPeriodic(), Part::GeometrySurfacePy::staticCallback_isPlanar(), Sketcher::SketchObjectPy::staticCallback_isPointOnCurve(), Part::BezierCurve2dPy::staticCallback_isRational(), Part::BSplineCurve2dPy::staticCallback_isRational(), Part::BezierCurvePy::staticCallback_isRational(), Part::BSplineCurvePy::staticCallback_isRational(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_isReady(), Base::RotationPy::staticCallback_isSame(), Part::TopoShapePy::staticCallback_isSame(), Part::TopoShapeEdgePy::staticCallback_isSeam(), Mesh::MeshPy::staticCallback_isSolid(), Part::BSplineSurfacePy::staticCallback_isUClosed(), Part::BezierSurfacePy::staticCallback_isUClosed(), Part::GeometrySurfacePy::staticCallback_isUClosed(), Part::GeometrySurfacePy::staticCallback_isUmbillic(), Part::BezierSurfacePy::staticCallback_isUPeriodic(), Part::BSplineSurfacePy::staticCallback_isUPeriodic(), Part::GeometrySurfacePy::staticCallback_isUPeriodic(), Part::BezierSurfacePy::staticCallback_isURational(), Part::BSplineSurfacePy::staticCallback_isURational(), Base::BoundBoxPy::staticCallback_isValid(), Part::TopoShapePy::staticCallback_isValid(), Part::BezierSurfacePy::staticCallback_isVClosed(), Part::BSplineSurfacePy::staticCallback_isVClosed(), Part::GeometrySurfacePy::staticCallback_isVClosed(), Gui::ViewProviderPy::staticCallback_isVisible(), Part::BezierSurfacePy::staticCallback_isVPeriodic(), Part::BSplineSurfacePy::staticCallback_isVPeriodic(), Part::GeometrySurfacePy::staticCallback_isVPeriodic(), Part::BezierSurfacePy::staticCallback_isVRational(), Part::BSplineSurfacePy::staticCallback_isVRational(), Part::BSplineCurve2dPy::staticCallback_join(), Part::BSplineCurvePy::staticCallback_join(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_lastShape(), Part::TopoShapeEdgePy::staticCallback_lastVertex(), Part::GeometryCurvePy::staticCallback_length(), Part::Curve2dPy::staticCallback_length(), Measure::MeasurementPy::staticCallback_length(), Part::TopoShapePy::staticCallback_limitTolerance(), Gui::PythonWorkbenchPy::staticCallback_listCommandbars(), Gui::PythonWorkbenchPy::staticCallback_ListCommandbars(), Gui::ViewProviderPy::staticCallback_listDisplayModes(), Gui::PythonWorkbenchPy::staticCallback_listMenus(), Gui::PythonWorkbenchPy::staticCallback_ListMenus(), Gui::PythonWorkbenchPy::staticCallback_listToolbars(), Gui::PythonWorkbenchPy::staticCallback_ListToolbars(), Fem::FemPostPipelinePy::staticCallback_load(), App::DocumentPy::staticCallback_load(), Part::PlateSurfacePy::staticCallback_makeApprox(), Part::BSplineCurve2dPy::staticCallback_makeC1Continuous(), Part::BSplineCurvePy::staticCallback_makeC1Continuous(), Part::TopoShapePy::staticCallback_makeChamfer(), TechDraw::DrawViewPartPy::staticCallback_makeCosmeticCircle(), TechDraw::DrawViewPartPy::staticCallback_makeCosmeticCircleArc(), TechDraw::DrawViewPartPy::staticCallback_makeCosmeticLine(), TechDraw::DrawViewPartPy::staticCallback_makeCosmeticVertex(), Part::TopoShapePy::staticCallback_makeFillet(), Part::TopoShapeShellPy::staticCallback_makeHalfSpace(), Part::TopoShapeFacePy::staticCallback_makeHalfSpace(), Part::TopoShapeWirePy::staticCallback_makeHomogenousWires(), Sketcher::SketchObjectPy::staticCallback_makeMissingEquality(), Sketcher::SketchObjectPy::staticCallback_makeMissingPointOnPointCoincident(), Sketcher::SketchObjectPy::staticCallback_makeMissingVerticalHorizontal(), Part::TopoShapeFacePy::staticCallback_makeOffset(), Part::TopoShapeWirePy::staticCallback_makeOffset(), Path::AreaPy::staticCallback_makeOffset(), Part::TopoShapePy::staticCallback_makeOffset2D(), Part::TopoShapePy::staticCallback_makeOffsetShape(), Part::TopoShapePy::staticCallback_makeParallelProjection(), Part::TopoShapePy::staticCallback_makePerspectiveProjection(), Part::TopoShapeWirePy::staticCallback_makePipe(), Part::TopoShapeWirePy::staticCallback_makePipeShell(), Path::AreaPy::staticCallback_makePocket(), Part::GeometryCurvePy::staticCallback_makeRuledSurface(), Path::AreaPy::staticCallback_makeSections(), Part::TopoShapePy::staticCallback_makeShapeFromMesh(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_makeSolid(), PartDesignGui::ViewProviderPy::staticCallback_makeTemporaryVisible(), Part::TopoShapePy::staticCallback_makeThickness(), Gui::DocumentPy::staticCallback_mdiViewsOfType(), Spreadsheet::SheetPy::staticCallback_mergeCells(), Mesh::MeshPy::staticCallback_mergeFacets(), App::DocumentPy::staticCallback_mergeProject(), Gui::DocumentPy::staticCallback_mergeProject(), Mesh::MeshPy::staticCallback_meshFromSegment(), Part::Geometry2dPy::staticCallback_mirror(), Part::GeometryPy::staticCallback_mirror(), Part::TopoShapePy::staticCallback_mirror(), Sketcher::SketchObjectPy::staticCallback_modifyBSplineKnotMultiplicity(), Base::MatrixPy::staticCallback_move(), Mesh::MeshPointPy::staticCallback_move(), Base::AxisPy::staticCallback_move(), Base::PlacementPy::staticCallback_move(), Base::BoundBoxPy::staticCallback_move(), Sketcher::SketchObjectPy::staticCallback_moveDatumsToEnd(), App::DocumentPy::staticCallback_moveObject(), Sketcher::SketchPy::staticCallback_movePoint(), Part::BSplineCurve2dPy::staticCallback_movePoint(), Part::BSplineCurvePy::staticCallback_movePoint(), Sketcher::SketchObjectPy::staticCallback_movePoint(), Part::BSplineSurfacePy::staticCallback_movePoint(), Part::TopoShapePy::staticCallback_multiFuse(), Base::AxisPy::staticCallback_multiply(), Base::PlacementPy::staticCallback_multiply(), Base::RotationPy::staticCallback_multiply(), Base::VectorPy::staticCallback_multiply(), Base::MatrixPy::staticCallback_multiply(), Base::PlacementPy::staticCallback_multVec(), Base::RotationPy::staticCallback_multVec(), Base::MatrixPy::staticCallback_multVec(), Gui::WorkbenchPy::staticCallback_name(), Mesh::MeshPy::staticCallback_nearestFacetOnRay(), Base::VectorPy::staticCallback_negative(), App::GroupExtensionPy::staticCallback_newObject(), Part::GeometrySurfacePy::staticCallback_normal(), Part::Curve2dPy::staticCallback_normal(), Part::GeometryCurvePy::staticCallback_normal(), Part::TopoShapeFacePy::staticCallback_normalAt(), Part::TopoShapeEdgePy::staticCallback_normalAt(), Base::VectorPy::staticCallback_normalize(), Part::TopoShapePy::staticCallback_nullify(), Mesh::MeshPy::staticCallback_offset(), Part::TopoShapeSolidPy::staticCallback_offsetFaces(), Mesh::MeshPy::staticCallback_offsetSpecial(), Part::TopoShapePy::staticCallback_oldFuse(), App::DocumentPy::staticCallback_openTransaction(), Part::TopoShapePy::staticCallback_optimalBoundingBox(), Mesh::MeshPy::staticCallback_optimizeEdges(), Mesh::MeshPy::staticCallback_optimizeTopology(), Mesh::MeshPy::staticCallback_outer(), Part::TopoShapePy::staticCallback_overTolerance(), Part::Curve2dPy::staticCallback_parameter(), Part::GeometryCurvePy::staticCallback_parameter(), Part::GeometrySurfacePy::staticCallback_parameter(), Part::TopoShapeEdgePy::staticCallback_parameterAt(), Part::GeometryCurvePy::staticCallback_parameterAtDistance(), Part::Curve2dPy::staticCallback_parameterAtDistance(), Part::TopoShapeEdgePy::staticCallback_parameters(), Part::GeometryCurvePy::staticCallback_period(), Robot::TrajectoryPy::staticCallback_position(), Part::AttachExtensionPy::staticCallback_positionBySupport(), Mesh::MeshPy::staticCallback_printInfo(), Part::TopoShapePy::staticCallback_project(), Base::VectorPy::staticCallback_projectToLine(), Base::VectorPy::staticCallback_projectToPlane(), Part::TopoShapePy::staticCallback_proximity(), TechDraw::DrawProjGroupPy::staticCallback_purgeProjections(), App::DocumentObjectPy::staticCallback_purgeTouched(), Measure::MeasurementPy::staticCallback_radius(), Mesh::MeshPy::staticCallback_read(), Import::StepShapePy::staticCallback_read(), Fem::FemPostPipelinePy::staticCallback_read(), Points::PointsPy::staticCallback_read(), Part::TopoShapePy::staticCallback_read(), Fem::FemMeshPy::staticCallback_read(), Attacher::AttachEnginePy::staticCallback_readParametersFromFeature(), Mesh::MeshPy::staticCallback_rebuildNeighbourHood(), App::DocumentObjectPy::staticCallback_recompute(), App::DocumentPy::staticCallback_recompute(), App::DocumentPy::staticCallback_redo(), Mesh::MeshPy::staticCallback_refine(), Part::TopoShapePy::staticCallback_reflectLines(), Gui::SelectionObjectPy::staticCallback_remove(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_remove(), Spreadsheet::SheetPy::staticCallback_removeColumns(), Gui::PythonWorkbenchPy::staticCallback_removeCommandbar(), Gui::PythonWorkbenchPy::staticCallback_RemoveCommandbar(), Mesh::MeshPy::staticCallback_removeComponents(), Gui::PythonWorkbenchPy::staticCallback_removeContextMenu(), Gui::PythonWorkbenchPy::staticCallback_RemoveContextMenu(), TechDraw::DrawViewPartPy::staticCallback_removeCosmeticEdge(), TechDraw::DrawViewPartPy::staticCallback_removeCosmeticVertex(), Mesh::MeshFeaturePy::staticCallback_removeDuplicatedFacets(), Mesh::MeshPy::staticCallback_removeDuplicatedFacets(), Mesh::MeshFeaturePy::staticCallback_removeDuplicatedPoints(), Mesh::MeshPy::staticCallback_removeDuplicatedPoints(), Mesh::MeshPy::staticCallback_removeFacets(), Mesh::MeshFeaturePy::staticCallback_removeFoldsOnSurface(), Mesh::MeshPy::staticCallback_removeFoldsOnSurface(), Mesh::MeshPy::staticCallback_removeFullBoundaryFacets(), Part::TopoShapePy::staticCallback_removeInternalWires(), Mesh::MeshFeaturePy::staticCallback_removeInvalidPoints(), Mesh::MeshPy::staticCallback_removeInvalidPoints(), Part::BSplineCurve2dPy::staticCallback_removeKnot(), Part::BSplineCurvePy::staticCallback_removeKnot(), Gui::PythonWorkbenchPy::staticCallback_removeMenu(), Gui::PythonWorkbenchPy::staticCallback_RemoveMenu(), Mesh::MeshPy::staticCallback_removeNeedles(), Mesh::MeshFeaturePy::staticCallback_removeNonManifoldPoints(), Mesh::MeshPy::staticCallback_removeNonManifoldPoints(), Mesh::MeshFeaturePy::staticCallback_removeNonManifolds(), Mesh::MeshPy::staticCallback_removeNonManifolds(), Path::FeaturePathCompoundPy::staticCallback_removeObject(), App::GroupExtensionPy::staticCallback_removeObject(), App::DocumentPy::staticCallback_removeObject(), App::GroupExtensionPy::staticCallback_removeObjects(), App::GroupExtensionPy::staticCallback_removeObjectsFromDocument(), Part::BezierCurve2dPy::staticCallback_removePole(), Part::BezierCurvePy::staticCallback_removePole(), Part::BezierSurfacePy::staticCallback_removePoleCol(), Part::BezierSurfacePy::staticCallback_removePoleRow(), TechDraw::DrawProjGroupPy::staticCallback_removeProjection(), Gui::ViewProviderPy::staticCallback_removeProperty(), App::DocumentObjectPy::staticCallback_removeProperty(), Spreadsheet::SheetPy::staticCallback_removeRows(), MeshGui::ViewProviderMeshPy::staticCallback_removeSelection(), Part::TopoShapePy::staticCallback_removeShape(), Part::TopoShapePy::staticCallback_removeSplitter(), Gui::PythonWorkbenchPy::staticCallback_removeToolbar(), Gui::PythonWorkbenchPy::staticCallback_RemoveToolbar(), Part::BSplineSurfacePy::staticCallback_removeUKnot(), TechDraw::DrawViewClipPy::staticCallback_removeView(), TechDraw::DrawPagePy::staticCallback_removeView(), TechDraw::DrawViewCollectionPy::staticCallback_removeView(), Part::BSplineSurfacePy::staticCallback_removeVKnot(), Sketcher::SketchObjectPy::staticCallback_renameConstraint(), Part::BSplineSurfacePy::staticCallback_reparametrize(), Part::TopoShapePy::staticCallback_replaceShape(), Gui::DocumentPy::staticCallback_resetEdit(), App::DocumentPy::staticCallback_restore(), Base::PersistencePy::staticCallback_restoreContent(), App::PropertyContainerPy::staticCallback_restorePropertyContent(), Part::Curve2dPy::staticCallback_reverse(), Part::GeometryCurvePy::staticCallback_reverse(), Part::TopoShapePy::staticCallback_reverse(), Base::AxisPy::staticCallback_reversed(), Part::GeometryCurvePy::staticCallback_reversedParameter(), Part::TopoShapePy::staticCallback_revolve(), Part::Geometry2dPy::staticCallback_rotate(), Part::GeometryPy::staticCallback_rotate(), Mesh::MeshPy::staticCallback_rotate(), Part::TopoShapePy::staticCallback_rotate(), Base::MatrixPy::staticCallback_rotateX(), Base::MatrixPy::staticCallback_rotateY(), Base::MatrixPy::staticCallback_rotateZ(), App::DocumentPy::staticCallback_save(), App::DocumentPy::staticCallback_saveAs(), App::DocumentPy::staticCallback_saveCopy(), Base::MatrixPy::staticCallback_scale(), Part::GeometryPy::staticCallback_scale(), Part::Geometry2dPy::staticCallback_scale(), Base::VectorPy::staticCallback_scale(), Base::BoundBoxPy::staticCallback_scale(), Part::TopoShapePy::staticCallback_scale(), Gui::DocumentPy::staticCallback_scrollToTreeItem(), Part::TopoShapePy::staticCallback_section(), Part::BezierCurve2dPy::staticCallback_segment(), Part::BezierCurvePy::staticCallback_segment(), Part::BSplineCurve2dPy::staticCallback_segment(), Part::BSplineCurvePy::staticCallback_segment(), Part::BezierSurfacePy::staticCallback_segment(), Part::BSplineSurfacePy::staticCallback_segment(), Gui::DocumentPy::staticCallback_sendMsgToViews(), App::MaterialPy::staticCallback_set(), Spreadsheet::SheetPy::staticCallback_set(), Sketcher::SketchObjectPy::staticCallback_setActive(), Spreadsheet::SheetPy::staticCallback_setAlias(), Spreadsheet::SheetPy::staticCallback_setAlignment(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_setAuxiliarySpine(), Base::CoordinateSystemPy::staticCallback_setAxes(), Spreadsheet::SheetPy::staticCallback_setBackground(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_setBiNormalMode(), PartDesignGui::ViewProviderPy::staticCallback_setBodyMode(), Spreadsheet::SheetPy::staticCallback_setColumnWidth(), Sketcher::SketchObjectPy::staticCallback_setConstruction(), PathSimulator::PathSimPy::staticCallback_SetCurrentTool(), Sketcher::SketchObjectPy::staticCallback_setDatum(), Sketcher::SketchObjectPy::staticCallback_setDatumsDriving(), Path::AreaPy::staticCallback_setDefaultParams(), Spreadsheet::SheetPy::staticCallback_setDisplayUnit(), Sketcher::SketchObjectPy::staticCallback_setDriving(), Gui::DocumentPy::staticCallback_setEdit(), TechDraw::DrawSVGTemplatePy::staticCallback_setEditFieldContent(), App::PropertyContainerPy::staticCallback_setEditorMode(), App::DocumentObjectPy::staticCallback_setExpression(), Part::GeometryPy::staticCallback_setExtension(), Sketcher::ExternalGeometryExtensionPy::staticCallback_setFlag(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_setForceApproxC1(), Spreadsheet::SheetPy::staticCallback_setForeground(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_setFrenetMode(), Path::CommandPy::staticCallback_setFromGCode(), Path::PathPy::staticCallback_setFromGCode(), Path::ToolPy::staticCallback_setFromTemplate(), Path::TooltablePy::staticCallback_setFromTemplate(), Part::BSplineCurve2dPy::staticCallback_setKnot(), Part::BSplineCurvePy::staticCallback_setKnot(), Part::BSplineCurve2dPy::staticCallback_setKnots(), Part::BSplineCurvePy::staticCallback_setKnots(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_setMaxDegree(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_setMaxSegments(), FemGui::ViewProviderFemMeshPy::staticCallback_setNodeColorByScalars(), FemGui::ViewProviderFemMeshPy::staticCallback_setNodeDisplacementByVectors(), Part::BSplineCurve2dPy::staticCallback_setNotPeriodic(), Part::BSplineCurvePy::staticCallback_setNotPeriodic(), App::GroupExtensionPy::staticCallback_setObjects(), Part::BSplineCurve2dPy::staticCallback_setOrigin(), Part::BSplineCurvePy::staticCallback_setOrigin(), Part::LineSegmentPy::staticCallback_setParameterRange(), Part::Line2dSegmentPy::staticCallback_setParameterRange(), Part::TrimmedCurvePy::staticCallback_setParameterRange(), Path::FeatureAreaPy::staticCallback_setParams(), Path::AreaPy::staticCallback_setParams(), Part::BSplineCurve2dPy::staticCallback_setPeriodic(), Part::BSplineCurvePy::staticCallback_setPeriodic(), Base::CoordinateSystemPy::staticCallback_setPlacement(), Path::AreaPy::staticCallback_setPlane(), Mesh::MeshPy::staticCallback_setPoint(), Part::BezierCurve2dPy::staticCallback_setPole(), Part::BezierCurvePy::staticCallback_setPole(), Part::BSplineCurve2dPy::staticCallback_setPole(), Part::BSplineCurvePy::staticCallback_setPole(), Part::BezierSurfacePy::staticCallback_setPole(), Part::BSplineSurfacePy::staticCallback_setPole(), Part::BezierSurfacePy::staticCallback_setPoleCol(), Part::BSplineSurfacePy::staticCallback_setPoleCol(), Part::BezierSurfacePy::staticCallback_setPoleRow(), Part::BSplineSurfacePy::staticCallback_setPoleRow(), Part::BezierCurvePy::staticCallback_setPoles(), Part::BezierCurve2dPy::staticCallback_setPoles(), Gui::DocumentPy::staticCallback_setPos(), Spreadsheet::SheetPy::staticCallback_setRowHeight(), MeshGui::ViewProviderMeshPy::staticCallback_setSelection(), Fem::FemMeshPy::staticCallback_setShape(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_setSpineSupport(), Fem::FemMeshPy::staticCallback_setStandardHypotheses(), Spreadsheet::SheetPy::staticCallback_setStyle(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_setTolerance(), Path::TooltablePy::staticCallback_setTool(), Fem::FemMeshPy::staticCallback_setTransform(), Gui::ViewProviderPy::staticCallback_setTransformation(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_setTransitionMode(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_setTrihedronMode(), Part::BSplineSurfacePy::staticCallback_setUKnot(), Part::BSplineSurfacePy::staticCallback_setUKnots(), Part::BSplineSurfacePy::staticCallback_setUNotPeriodic(), Part::BSplineSurfacePy::staticCallback_setUOrigin(), Part::BSplineSurfacePy::staticCallback_setUPeriodic(), Sketcher::SketchObjectPy::staticCallback_setVirtualSpace(), Part::BSplineSurfacePy::staticCallback_setVKnot(), Part::BSplineSurfacePy::staticCallback_setVKnots(), Part::BSplineSurfacePy::staticCallback_setVNotPeriodic(), Base::BoundBoxPy::staticCallback_setVoid(), Part::BSplineSurfacePy::staticCallback_setVOrigin(), Part::BSplineSurfacePy::staticCallback_setVPeriodic(), Part::BezierCurve2dPy::staticCallback_setWeight(), Part::BezierCurvePy::staticCallback_setWeight(), Part::BSplineCurve2dPy::staticCallback_setWeight(), Part::BSplineCurvePy::staticCallback_setWeight(), Part::BezierSurfacePy::staticCallback_setWeight(), Part::BSplineSurfacePy::staticCallback_setWeight(), Part::BezierSurfacePy::staticCallback_setWeightCol(), Part::BSplineSurfacePy::staticCallback_setWeightCol(), Part::BezierSurfacePy::staticCallback_setWeightRow(), Part::BSplineSurfacePy::staticCallback_setWeightRow(), Part::TopoShapePy::staticCallback_sewShape(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_shape(), Gui::DocumentPy::staticCallback_show(), Gui::ViewProviderPy::staticCallback_show(), Part::BRepOffsetAPI_MakePipeShellPy::staticCallback_simulate(), Part::TopoShapePy::staticCallback_slice(), Part::TopoShapePy::staticCallback_slices(), Mesh::MeshFeaturePy::staticCallback_smooth(), Mesh::MeshPy::staticCallback_smooth(), Mesh::MeshPy::staticCallback_snapVertex(), Sketcher::SketchPy::staticCallback_solve(), Sketcher::SketchObjectPy::staticCallback_solve(), Part::TopoShapeEdgePy::staticCallback_split(), Spreadsheet::SheetPy::staticCallback_splitCell(), Mesh::MeshPy::staticCallback_splitEdge(), Mesh::MeshPy::staticCallback_splitEdges(), Mesh::MeshPy::staticCallback_splitFacet(), Base::VectorPy::staticCallback_sub(), Base::MatrixPy::staticCallback_submatrix(), Attacher::AttachEnginePy::staticCallback_suggestModes(), App::DocumentObjectPy::staticCallback_supportedProperties(), Gui::ViewProviderPy::staticCallback_supportedProperties(), App::DocumentPy::staticCallback_supportedTypes(), Mesh::MeshPy::staticCallback_swapEdge(), Part::GeometrySurfacePy::staticCallback_tangent(), Part::GeometryCurvePy::staticCallback_tangent(), Part::Curve2dPy::staticCallback_tangent(), Part::TopoShapeEdgePy::staticCallback_tangentAt(), Part::TopoShapeFacePy::staticCallback_tangentAt(), Path::ToolPy::staticCallback_templateAttrs(), Path::TooltablePy::staticCallback_templateAttrs(), Part::TopoShapePy::staticCallback_tessellate(), Sketcher::ExternalGeometryExtensionPy::staticCallback_testFlag(), Part::BSplineCurve2dPy::staticCallback_toBezier(), Part::BSplineCurvePy::staticCallback_toBezier(), Part::BSplineCurve2dPy::staticCallback_toBiArcs(), Part::BSplineCurvePy::staticCallback_toBiArcs(), Part::Curve2dPy::staticCallback_toBSpline(), Part::GeometryCurvePy::staticCallback_toBSpline(), Part::GeometrySurfacePy::staticCallback_toBSpline(), Base::RotationPy::staticCallback_toEuler(), Path::CommandPy::staticCallback_toGCode(), Path::PathPy::staticCallback_toGCode(), Sketcher::SketchObjectPy::staticCallback_toggleActive(), Sketcher::SketchObjectPy::staticCallback_toggleConstruction(), Sketcher::SketchObjectPy::staticCallback_toggleDriving(), Gui::DocumentPy::staticCallback_toggleTreeItem(), Sketcher::SketchObjectPy::staticCallback_toggleVirtualSpace(), Base::PlacementPy::staticCallback_toMatrix(), Part::GeometryCurvePy::staticCallback_toNurbs(), Part::TopoShapePy::staticCallback_toNurbs(), Part::GeometryCurvePy::staticCallback_toShape(), Part::GeometrySurfacePy::staticCallback_toShape(), Part::PointPy::staticCallback_toShape(), Part::Curve2dPy::staticCallback_toShape(), Gui::ViewProviderPy::staticCallback_toString(), App::DocumentObjectPy::staticCallback_touch(), Path::CommandPy::staticCallback_transform(), Part::Geometry2dPy::staticCallback_transform(), Part::GeometryPy::staticCallback_transform(), Base::CoordinateSystemPy::staticCallback_transform(), Base::MatrixPy::staticCallback_transform(), Mesh::MeshPy::staticCallback_transform(), Base::BoundBoxPy::staticCallback_transformed(), Part::TopoShapePy::staticCallback_transformGeometry(), Part::TopoShapePy::staticCallback_transformShape(), Base::CoordinateSystemPy::staticCallback_transformTo(), Mesh::MeshPy::staticCallback_transformToEigen(), Part::GeometryPy::staticCallback_translate(), Part::Geometry2dPy::staticCallback_translate(), Mesh::MeshPy::staticCallback_translate(), Part::TopoShapePy::staticCallback_translate(), Base::MatrixPy::staticCallback_transpose(), Base::MatrixPy::staticCallback_transposed(), Part::GeometryCurvePy::staticCallback_trim(), Sketcher::SketchObjectPy::staticCallback_trim(), Mesh::MeshPy::staticCallback_trim(), Part::ConePy::staticCallback_uIso(), Part::SurfaceOfExtrusionPy::staticCallback_uIso(), Part::RectangularTrimmedSurfacePy::staticCallback_uIso(), Part::PlanePy::staticCallback_uIso(), Part::CylinderPy::staticCallback_uIso(), Part::ToroidPy::staticCallback_uIso(), Part::SpherePy::staticCallback_uIso(), Part::GeometrySurfacePy::staticCallback_uIso(), Part::BezierSurfacePy::staticCallback_uIso(), Part::BSplineSurfacePy::staticCallback_uIso(), Mesh::MeshPointPy::staticCallback_unbound(), Mesh::FacetPy::staticCallback_unbound(), App::DocumentPy::staticCallback_undo(), Mesh::MeshPy::staticCallback_unite(), Base::BoundBoxPy::staticCallback_united(), Base::MatrixPy::staticCallback_unity(), Gui::ViewProviderDocumentObjectPy::staticCallback_update(), Gui::DocumentPy::staticCallback_update(), Part::GeometrySurfacePy::staticCallback_UPeriod(), Part::TopoShapeFacePy::staticCallback_validate(), Part::GeometrySurfacePy::staticCallback_value(), Part::GeometryCurvePy::staticCallback_value(), Part::Curve2dPy::staticCallback_value(), Part::TopoShapeEdgePy::staticCallback_valueAt(), Part::TopoShapeFacePy::staticCallback_valueAt(), Robot::TrajectoryPy::staticCallback_velocity(), Part::PlanePy::staticCallback_vIso(), Part::CylinderPy::staticCallback_vIso(), Part::RectangularTrimmedSurfacePy::staticCallback_vIso(), Part::ConePy::staticCallback_vIso(), Part::SpherePy::staticCallback_vIso(), Part::SurfaceOfExtrusionPy::staticCallback_vIso(), Part::ToroidPy::staticCallback_vIso(), Part::GeometrySurfacePy::staticCallback_vIso(), Part::BezierSurfacePy::staticCallback_vIso(), Part::BSplineSurfacePy::staticCallback_vIso(), Part::GeometrySurfacePy::staticCallback_VPeriod(), Mesh::MeshPy::staticCallback_write(), Points::PointsPy::staticCallback_write(), Fem::FemMeshPy::staticCallback_write(), Fem::FemMeshPy::staticCallback_writeABAQUS(), Mesh::MeshPy::staticCallback_writeInventor(), Part::TopoShapePy::staticCallback_writeInventor(), Points::PointsPy::staticCallback_writeInventor(), Attacher::AttachEnginePy::staticCallback_writeParametersToFeature(), TechDrawGui::QGIViewSymbol::symbolToSvg(), MeshPart::MeshingOutput::sync(), Base::RedirectStdError::sync(), TechDrawGui::TaskActiveView::TaskActiveView(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), TechDrawGui::TaskCenterLine::TaskCenterLine(), TechDrawGui::TaskCosVertex::TaskCosVertex(), TechDrawGui::TaskDetail::TaskDetail(), Gui::TaskView::TaskDialogPython::TaskDialogPython(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskRichAnno::TaskRichAnno(), TechDrawGui::TaskSectionView::TaskSectionView(), TechDrawGui::TaskWeldingSymbol::TaskWeldingSymbol(), Gui::AutoSaver::timerEvent(), App::PropertyPythonObject::toString(), SketcherGui::ViewProviderSketch::unsetEdit(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), Gui::ViewProviderVRMLObject::updateData(), PartGui::ViewProviderCurveNet::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), TechDrawGui::TaskDetail::updateDetail(), PartDesignGui::ViewProviderBody::updateOriginDatumSize(), Gui::ViewProviderOriginGroupExtension::updateOriginSize(), Gui::OutputStderr::write(), Gui::PythonDebugStderr::write(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), and PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters().
Get()
ILogger * ConsoleSingleton::Get (const char * Name) const
References Base::ILogger::Name().
Referenced by IsMsgTypeEnabled(), Base::Builder3D::saveToLog(), SetEnabledMsgType(), sPyGetStatus(), and sPySetStatus().
GetLogLevel()
int * ConsoleSingleton::GetLogLevel (const char * tag, bool create = true)
References femsolver.elmer.equations.elasticity::create().
Instance()
ConsoleSingleton & ConsoleSingleton::Instance (void) static
singleton
References ConsoleSingleton().
Referenced by Base::Console(), sPyError(), sPyGetStatus(), sPyLog(), sPyMessage(), sPySetStatus(), and sPyWarning().
IsMsgTypeEnabled()
bool ConsoleSingleton::IsMsgTypeEnabled (const char * sObs, FreeCAD_ConsoleMsgType type) const
Enables or disables message types of a certain console observer.
References Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bWrn, Get(), MsgType_Err, MsgType_Log, MsgType_Txt, and MsgType_Wrn.
Log()
void ConsoleSingleton::Log (const char * pMsg, ...) virtual
Prints a log Message.
Prints a Message This method is appropriate for development and tracking purposes.
It can be used to track execution of algorithms and functions. The normal user doesn't need to see it, it's more for developers and experienced users. So in normal user mode the logging is switched off.
You can use a printf-like interface for example:
Console().Log("Execute part %d in algorithm %s\n",i,str);
See also
Message
Warning
Error
Referenced by Gui::Application::activateWorkbench(), TechDraw::GeometryObject::addGeomFromCompound(), TechDraw::DrawProjGroup::addProjection(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::BSpline::asCircle(), TechDrawGui::ViewProviderPage::attach(), TechDrawGui::MDIViewPage::attachView(), Sketcher::SketchAnalysis::autoconstraint(), Gui::NS::AwaitingMoveState::AwaitingMoveState(), Gui::NS::AwaitingReleaseState::AwaitingReleaseState(), TechDraw::BezierSegment::BezierSegment(), TechDraw::BSpline::BSpline(), TechDraw::DrawViewPart::buildGeometryObject(), TechDraw::GeometryObject::calcBoundingBox(), TechDraw::DrawProjGroup::calculateAutomaticScale(), Gui::MacroManager::cancel(), Gui::ViewProvider::canDropObject(), TechDraw::GeometryUtils::chainGeoms(), Sketcher::SketchObject::changeConstraintsLocking(), PartDesignGui::TaskHoleParameters::changedObject(), TechDraw::DrawViewDimension::checkReferences2D(), TechDraw::DrawViewPart::checkXDirection(), Gui::MacroManager::commit(), App::PropertyFileIncluded::Copy(), TechDrawGui::Grabber3d::copyActiveViewToSvgFile(), TechDrawGui::TaskCenterLine::createCenterLine(), Mesh::GTSAlgos::createGTSSurface(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createWidget(), Gui::WorkbenchManager::createWorkbench(), Gui::Dialog::ButtonModel::data(), App::Application::destruct(), TechDraw::DrawViewDetail::detailExec(), GCS::System::diagnose(), App::Document::Document(), MeshGui::ViewProviderMeshTransformDemolding::DragEndCallback(), TechDrawGui::QGIViewBalloon::draw(), TechDrawGui::QGIViewDimension::draw(), SketcherGui::ViewProviderSketch::editDoubleClicked(), Gui::ViewerEventFilter::eventFilter(), TechDraw::DrawViewMulti::execute(), TechDraw::DrawViewSymbol::execute(), Raytracing::LuxProject::execute(), Raytracing::RayProject::execute(), Import::FeatureImportStep::Execute(), Import::FeatureImportIges::Execute(), Part::ImportBrep::execute(), Part::CurveNet::execute(), Part::ImportIges::execute(), TechDraw::DrawSVGTemplate::execute(), Part::ImportStep::execute(), Drawing::FeaturePage::execute(), Fem::FemMeshShapeNetgenObject::execute(), TechDraw::DrawViewDimension::execute(), Fem::FemVTKTools::exportFreeCADResult(), Gui::ViewProviderGroupExtension::extensionCanDropObject(), TechDraw::DrawGeomHatch::extractFace(), TechDraw::DrawViewPart::extractFaces(), Sketcher::SketchObject::fillet(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::MeshTopoAlgorithm::FillupHoles(), MeshCore::CylinderFit::Fit(), MeshGui::SoFCMeshFaceSet::generatePrimitives(), MeshGui::SoFCMeshObjectShape::generatePrimitives(), MeshGui::SoFCMeshSegmentShape::generatePrimitives(), Gui::NS::GestureState::GestureState(), TechDrawGui::DrawGuiUtil::get3DDirAndRot(), TechDraw::DrawProjGroup::getAnchorDirection(), TechDraw::DrawLeaderLine::getBaseScale(), TechDraw::DrawProjGroup::getBoundingBox(), TechDraw::BSpline::getCircleParms(), TechDrawGui::QGIView::getClipGroup(), TechDraw::DrawViewSection::getCSFromBase(), TechDraw::DrawProjectSplit::getEdges(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), TechDraw::DrawViewPart::getFaceEdgesByIndex(), TechDraw::DrawGeomHatch::getFaceOverlay(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getIndexFromName(), TechDrawGui::ViewProviderPage::getMDIViewPage(), Fem::FemMesh::getNodesBySolid(), TechDrawGui::Grabber3d::getPaperScale(), TechDraw::LineSet::getPatternStartPoint(), TechDrawGui::DrawGuiUtil::getProjDirFromFace(), TechDraw::DrawProjGroup::getProjItem(), TechDraw::DrawProjGroup::getProjObj(), TechDraw::DrawViewPart::getProjVertexByCosTag(), TechDraw::DrawViewPart::getProjVertexByIndex(), TechDraw::DrawProjGroupItem::getScale(), TechDraw::DrawLeaderLine::getScale(), TechDraw::DrawView::getScale(), TechDraw::DrawViewSection::getSectionCS(), TechDraw::ShapeExtractor::getShapesFromObject(), TechDraw::DrawGeomHatch::getTrimmedLines(), TechDraw::DrawView::handleChangedPropertyType(), TechDraw::DrawPage::handleChangedPropertyType(), PartGui::ViewProviderCurveNet::handleEvent(), TechDraw::DrawProjGroup::hasProjection(), Gui::NS::IdleState::IdleState(), Base::Type::importModule(), Part::ImportStepParts(), Image::initModule(), Gui::GuiNativeEvent::initSpaceball(), Gui::NS::InteractState::InteractState(), Gui::Command::invoke(), TechDraw::DrawUtil::isCrazy(), Fem::FemPostPipeline::load(), Mesh::MeshObject::load(), Gui::NS::Event::log(), GCS::SolverReportingManager::LogToConsole(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), TechDraw::mirrorShape(), TechDrawGui::QGIPrimPath::mousePressEvent(), TechDraw::moveShape(), Gui::GUIApplication::notify(), Gui::WindowParameter::OnChange(), TechDraw::DrawViewSymbol::onChanged(), TechDraw::DrawProjGroup::onChanged(), Gui::Document::onRelabel(), Gui::GestureNavigationStyle::onRollGesture(), TechDrawGui::MDIViewPage::onSelectionChanged(), Gui::View3DInventor::onUpdate(), Gui::Document::onUpdate(), Gui::MacroManager::open(), Gui::NS::PanState::PanState(), TechDraw::DrawViewPart::partExec(), TechDraw::EdgeWalker::perform(), Sketcher::SketchObject::port_reversedExternalArcs(), Gui::GestureNavigationStyle::EventQueue::post(), App::Application::processFiles(), TechDraw::DrawSVGTemplate::processTemplate(), MeshPart::CurveProjectorShape::projectCurve(), MeshPart::CurveProjectorSimple::projectCurve(), MeshPart::MeshProjection::projectEdgeToEdge(), TechDraw::GeometryObject::projectShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), TechDraw::DrawProjGroup::purgeProjections(), Base::PyObjectBase::PyObjectBase(), TestJtReader::read(), Fem::readVTKFile(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskRichAnno::removeFeature(), TechDrawGui::TaskLeaderLine::removeFeature(), TechDraw::DrawProjGroup::removeProjection(), TechDraw::rotateShape(), Gui::NS::RotateState::RotateState(), Gui::ConsoleLogTask::run(), Gui::Application::runApplication(), App::Application::runApplication(), Gui::AutoSaver::saveDocument(), TechDraw::scaleShape(), TechDrawGui::TaskProjGroup::scaleTypeChanged(), Gui::Application::setActiveDocument(), TechDrawGui::QGTracker::setCircleFromPoints(), FemGui::ViewProviderFemMeshPy::setNodeColor(), TechDrawGui::QGTracker::setPathFromPoints(), TechDrawGui::QGTracker::setSquareFromPoints(), Sketcher::Sketch::setUpSketch(), Gui::Application::slotDeleteDocument(), Sketcher::Sketch::solve(), TechDraw::EdgeWalker::sortStrip(), sPyLog(), FcLodHandler::startLod(), Gui::GUISingleApplication::Private::startServer(), Gui::NS::StickyPanState::StickyPanState(), Base::RedirectStdOutput::sync(), Base::RedirectStdLog::sync(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskPostDisplay::TaskPostDisplay(), FemGui::TaskPostScalarClip::TaskPostScalarClip(), FemGui::TaskPostWarpVector::TaskPostWarpVector(), Gui::NS::TiltState::TiltState(), Raytracing::PovTools::transferToArray(), SpaceNavigatorDevice::translateEvent(), MeshCore::AbstractPolygonTriangulator::TriangulatePolygon(), TechDraw::DrawPage::unsetupObject(), TechDraw::DrawProjGroup::updateChildrenEnforce(), TechDraw::DrawProjGroup::updateChildrenLock(), TechDraw::DrawProjGroup::updateChildrenScale(), TechDraw::DrawProjGroup::updateChildrenSource(), TechDrawGui::MDIViewPage::updateTemplate(), TechDrawGui::QGIRichAnno::updateView(), PartGui::ViewProviderPartExt::updateVisual(), Gui::Application::viewActivated(), TechDraw::Wire::Wire(), Fem::FemMesh::write(), Raytracing::LuxTools::writeShape(), Raytracing::PovTools::writeShape(), Raytracing::PovTools::writeShapeCSV(), Fem::FemMesh::writeZ88(), Gui::GuiNativeEvent::x11EventFilter(), Gui::Application::~Application(), App::Document::~Document(), TechDraw::DrawTemplate::~DrawTemplate(), Gui::GuiNativeEvent::~GuiNativeEvent(), and Base::PyObjectBase::~PyObjectBase().
LogLevel()
int Base::ConsoleSingleton::LogLevel (int level) const
Referenced by Base::LogLevel::level().
Message()
void ConsoleSingleton::Message (const char * pMsg, ...) virtual
Prints a Message.
Prints a Message This method issues a Message.
Messages are used to show some non vital information. That means when FreeCAD is running in GUI mode a Message appears on the status bar. In console mode a message is printed to the console.
You can use a printf like interface like:
Console().Message("Doing something important %d times\n",i);
See also
Warning
Error
Log
Referenced by CmdSandboxEventLoop::activated(), StdCmdViewIvIssueCamPos::activated(), TechDraw::DrawViewPart::add1CEToGE(), TechDraw::DrawViewPart::add1CLToGE(), TechDraw::DrawViewPart::add1CVToGV(), TechDraw::GeometryObject::addCosmeticVertex(), Mesh::Exporter::addObject(), TechDraw::DrawUtil::angleWithX(), TechDrawGui::TaskSectionView::applyAligned(), TechDraw::BaseGeom::baseFactory(), PartGui::TaskMeasureLinear::buildDimension(), PartGui::TaskMeasureAngular::buildDimension(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDrawGui::TaskRichAnno::calcTextStartPos(), TechDraw::DrawUtil::copyFile(), TechDraw::DrawUtil::countEdges(), TechDraw::DrawUtil::countFaces(), TechDraw::DrawUtil::countWires(), TechDrawGui::QGISVGTemplate::createClickHandles(), MeshGui::ViewProviderMeshCurvature::curvatureInfoCallback(), TechDraw::DrawViewDetail::detailExec(), Part::TopoShapePy::distToShape(), TechDrawGui::QGIWeldSymbol::drawTile(), TechDrawGui::QGIViewPart::drawViewPart(), TechDraw::DashSpec::dump(), TechDraw::LineFormat::dump(), TechDraw::CosmeticVertex::dump(), TechDraw::LineGroup::dump(), TechDraw::PATLineSpec::dump(), TechDraw::CosmeticEdge::dump(), TechDraw::CenterLine::dump(), TechDraw::GeomFormat::dump(), TechDraw::Vertex::dump(), TechDraw::DrawUtil::dump1Vertex(), TechDraw::DrawViewPart::dumpCosEdges(), TechDraw::DrawViewPart::dumpCosVerts(), TechDraw::DrawUtil::dumpCS(), TechDraw::DrawUtil::dumpCS3(), TechDraw::DrawUtil::dumpEdge(), TechDraw::DrawUtil::dumpEdges(), TechDrawGui::QGEPath::dumpGhostPoints(), TechDraw::DrawProjGroup::dumpISO(), PartGui::dumpLinearResults(), TechDrawGui::QGEPath::dumpMarkerPos(), TechDrawGui::QGIViewPart::dumpPath(), TechDrawGui::DrawGuiUtil::dumpPointF(), TechDrawGui::QGIView::dumpRect(), TechDrawGui::DrawGuiUtil::dumpRectF(), TechDraw::DrawUtil::dumpVertexes(), TechDraw::DrawViewPart::dumpVerts(), TechDraw::Ellipse::Ellipse(), PartGui::evaluateAngularPreSelection(), Base::Debugger::exec(), Sandbox::SandboxObject::execute(), Inspection::Feature::execute(), Import::ImpExpDxfWrite::exportBCurve(), Import::ImpExpDxfWrite::exportBSpline(), MeshGui::ViewProviderMesh::faceInfo(), MeshGui::ViewProviderMesh::faceInfoCallback(), MeshGui::ViewProviderMesh::fillHoleCallback(), TechDraw::BaseGeom::findEndPoints(), TechDrawGui::QGIViewDimension::findIsoExt(), MeshCore::SphereFit::Fit(), TechDrawGui::TaskDetail::getAnchorScene(), TechDrawGui::QGILeaderLine::getAttachFromFeature(), TechDraw::CosmeticExtension::getCosmeticEdge(), TechDrawGui::QGEPath::getDeltasFromLeader(), TechDrawGui::ViewProviderPage::getDrawPage(), TechDraw::DrawProjectSplit::getEdges(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), TechDraw::BaseGeom::getEndPoint(), MeshGui::ViewProviderMesh::getFacetsFromPolygon(), MeshGui::CylinderFitParameter::getParameter(), TechDraw::PATLineSpec::getPatternList(), CDxfWrite::getPlateFile(), TechDraw::LineGroup::getRecordFromFile(), TechDraw::PATLineSpec::getSpecsForPattern(), TechDraw::BaseGeom::getStartPoint(), TechDraw::DrawProjGroupItem::getViewAxis(), TechDraw::DrawViewPart::getViewAxis(), TechDrawGui::QGILeaderLine::getWayPointsFromFeature(), TechDraw::DrawProjGroupItem::getXDirection(), TechDraw::ShapeExtractor::getXShapes(), PartGui::goDimensionAngularNoTask(), MeshGui::ViewProviderMeshNode::handleEvent(), InspectionGui::ViewProviderInspection::inspectCallback(), TechDraw::DrawUtil::Intersect2d(), ModelRefine::FaceTypedBSpline::isEqual(), TechDraw::DrawProjectSplit::isOnEdge(), TechDraw::LineGroup::lineGroupFactory(), TechDraw::PATLineSpec::load(), Gui::MainWindow::loadUrls(), TechDraw::DrawViewPartPy::makeCosmeticCircle(), TechDraw::DrawViewPartPy::makeCosmeticCircleArc(), TechDraw::DrawViewPartPy::makeCosmeticLine(), TechDrawGui::QGILeaderLine::makeLeaderPath(), TechDraw::DrawViewSection::makeLineSets(), Part::TopoShape::makeLoft(), MeshGui::ViewProviderMesh::markPartCallback(), Gui::ViewProviderMeasureDistance::measureDistanceCallback(), MeshGui::DlgEvaluateMeshImp::on_analyzeSelfIntersectionButton_clicked(), PartDesignGui::ViewProviderBody::onChanged(), Sandbox::SandboxObject::onChanged(), Fem::ConstraintFluidBoundary::onChanged(), TechDraw::DrawPage::onChanged(), TechDrawGui::TaskDetail::onHighlightMoved(), FemGui::TaskCreateNodeSet::onSelectionChanged(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::TaskLeaderLine::onTrackerFinished(), MeshGui::ViewProviderMesh::partMeshCallback(), FemGui::TaskPostDataAlongLine::pointCallback(), FemGui::TaskPostDataAtPoint::pointCallback(), TechDrawGui::QGVPage::postProcessXml(), TechDraw::DrawSVGTemplate::processTemplate(), Part::ReadNames(), Fem::FemVTKTools::readResult(), TechDraw::DrawProjectSplit::removeDuplicateEdges(), TechDrawGui::TaskLeaderLine::removeFeature(), TechDraw::CosmeticExtension::replaceCenterLine(), TechDraw::CosmeticExtension::replaceCosmeticEdge(), TechDraw::CosmeticExtension::replaceCosmeticVertex(), TechDraw::CosmeticExtension::replaceGeomFormat(), Sandbox::SandboxObject::resetValue(), App::Document::Restore(), TechDrawGui::TaskProjGroup::restoreGroupState(), Part::TopoShape::revolve(), Sandbox::DocumentTestThread::run(), BarThread::run(), MeshTestJob::run(), Gui::ConsoleMessageTask::run(), Gui::Application::runApplication(), TechDraw::CenterLine::Save(), TechDraw::CenterLine::scaledGeometry(), TechDraw::DrawViewSection::sectionExec(), MeshGui::ViewProviderMesh::segmMeshCallback(), Sandbox::SandboxObject::setIntValue(), TechDrawGui::QGTracker::setPoint(), TechDrawGui::QGEPath::showMarkers(), TechDraw::DrawUtil::simpleMinDist(), TechDraw::DrawProjectSplit::split1Edge(), sPyMessage(), TechDrawGui::TaskCenterLine::TaskCenterLine(), TechDraw::DrawProjGroup::updateSecondaryDirs(), TechDrawGui::TaskWeldingSymbol::updateTiles(), and Gui::OutputStdout::write().
NotifyError()
void ConsoleSingleton::NotifyError (const char * sMsg)
References Base::Error.
Referenced by Base::ConsoleOutput::customEvent().
NotifyLog()
void ConsoleSingleton::NotifyLog (const char * sMsg)
References Base::Log.
Referenced by Base::ConsoleOutput::customEvent().
NotifyMessage()
void ConsoleSingleton::NotifyMessage (const char * sMsg)
References Base::Message.
Referenced by Base::ConsoleOutput::customEvent().
NotifyWarning()
void ConsoleSingleton::NotifyWarning (const char * sMsg)
References Base::Warning.
Referenced by Base::ConsoleOutput::customEvent().
Refresh()
void ConsoleSingleton::Refresh ()
SetConnectionMode()
void ConsoleSingleton::SetConnectionMode (ConnectionMode mode)
References connectionMode.
SetConsoleMode()
void ConsoleSingleton::SetConsoleMode (ConsoleMode m)
Change mode.
sets the console in a special mode
References Verbose.
SetDefaultLogLevel()
void Base::ConsoleSingleton::SetDefaultLogLevel (int level)
SetEnabledMsgType()
ConsoleMsgFlags ConsoleSingleton::SetEnabledMsgType (const char * sObs, ConsoleMsgFlags type, bool b)
Enables or disables message types of a certain console observer.
type can be OR'ed with any of the FreeCAD_ConsoleMsgType flags to enable – if b is true – or to disable – if b is false – a console observer with name sObs.
The return value is an OR'ed value of all message types that have changed their state. For example
// switch off warnings and error messages
ConsoleMsgFlags ret = Base::Console().SetEnabledMsgType("myObs",
                      Base:ConsoleSingleton::MsgType_Wrn|Base::ConsoleSingleton::MsgType_Err, false);
// do something without notifying observer myObs
...
// restore the former configuration again
Base::Console().SetEnabledMsgType("myObs", ret, true);
switches off warnings and error messages and restore the state before the modification. If the observer sObs doesn't exist then nothing happens.
References Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bWrn, Get(), MsgType_Err, MsgType_Log, MsgType_Txt, and MsgType_Wrn.
Referenced by Gui::MainWindow::loadWindowSettings(), and Gui::BitmapFactoryInst::pixmapFromSvg().
sPyError()
PyObject * ConsoleSingleton::sPyError (PyObject * self, PyObject * args) static protected
References Error(), and Instance().
sPyGetStatus()
PyObject * ConsoleSingleton::sPyGetStatus (PyObject * self, PyObject * args) static protected
References Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bWrn, Get(), and Instance().
sPyLog()
PyObject * ConsoleSingleton::sPyLog (PyObject * self, PyObject * args) static protected
References Instance(), and Log().
sPyMessage()
PyObject * ConsoleSingleton::sPyMessage (PyObject * self, PyObject * args) static protected
References Instance(), and Message().
sPySetStatus()
PyObject * ConsoleSingleton::sPySetStatus (PyObject * self, PyObject * args) static protected
References Base::BaseExceptionFreeCADError, Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bWrn, Get(), and Instance().
sPyWarning()
PyObject * ConsoleSingleton::sPyWarning (PyObject * self, PyObject * args) static protected
References Instance(), and Warning().
Time()
const char * ConsoleSingleton::Time (void)
Delivers a time/date string.
Delivers the time/date This method gives you a string with the actual time/date.
You can use that for Log() calls to make timestamps.
Returns
Const string with the date/time
UnsetConsoleMode()
void ConsoleSingleton::UnsetConsoleMode (ConsoleMode m)
Change mode.
unsets the console from a special mode
References Verbose.
Warning()
void ConsoleSingleton::Warning (const char * pMsg, ...) virtual
Prints a warning Message.
Prints a Message This method issues a Warning.
Messages are used to get the users attention. That means when FreeCAD is in GUI mode a Message Box pops up. In console mode a colored message is returned to the console! Don't use this carelessly. For information purposes the 'Log' or 'Message' methods are more appropriate.
You can use a printf like interface like:
Console().Warning("Some defects in %s, loading anyway\n",str);
See also
Message
Error
Log
Referenced by ReverseEngineeringGui::Segmentation::accept(), FemGui::TaskDlgCreateNodeSet::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), RobotGui::TaskDlgEdge2Trac::accept(), MeshGui::GmshWidget::accept(), FemGui::TaskDlgFemConstraintFluidBoundary::accept(), Sketcher::Sketch::addEqualConstraint(), Sketcher::Sketch::addPerpendicularConstraint(), Gui::CommandManager::addTo(), TechDraw::DrawPage::addView(), Sketcher::SketchAnalysis::analyseMissingPointOnPointCoincident(), TechDraw::DrawUtil::angleWithX(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDrawGui::ViewProviderDrawingView::attach(), PartDesignGui::TaskFeaturePick::buildFeatures(), TechDrawGui::QGIFace::buildPixHatch(), TechDrawGui::QGIFace::buildSvgHatch(), Gui::PropertyEditor::PropertyEditor::buildUp(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::CenterLine::calcEndPoints2Points(), Attacher::AttachEngine3D::calculateAttachedPlacement(), Attacher::AttachEngineLine::calculateAttachedPlacement(), TechDraw::CenterLine::CenterLineBuilder(), FemGui::TaskDlgMeshShapeNetgen::clicked(), RobotGui::TaskDlgEdge2Trac::clicked(), Base::ConsoleObserverFile::ConsoleObserverFile(), TechDrawGui::Grabber3d::copyActiveViewToSvgFile(), TechDrawGui::QGISVGTemplate::createClickHandles(), PartGui::ViewProvider2DObject::createGrid(), MeshPart::Mesher::createMesh(), Gui::DocumentItem::createNewItem(), Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createWidget(), TechDrawGui::QGIFace::dashedPPath(), SketcherGui::ViewProviderSketch::deleteSelected(), TechDraw::DrawViewDetail::detailExec(), GCS::System::diagnose(), TechDrawGui::QGIViewAnnotation::drawAnnotation(), TechDrawGui::QGIViewClip::drawClip(), SketcherGui::ViewProviderSketch::drawConstraintIcons(), TechDrawGui::QGIViewSection::drawSectionFace(), Gui::ViewerEventFilter::eventFilter(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewSymbol::execute(), TechDraw::DrawViewSection::execute(), Sketcher::SketchObjectSF::execute(), TechDraw::DrawViewPart::execute(), PartDesign::Transformed::execute(), TechDraw::DrawViewDimension::execute(), Import::ImpExpDxfWrite::exportShape(), TechDraw::DrawViewPart::extractFaces(), TechDraw::GeometryObject::extractGeometry(), Gui::PrefWidget::failedToRestore(), Gui::PrefWidget::failedToSave(), ParameterGrp::FindElement(), ParameterGrp::FindOrCreateElement(), TechDraw::DrawViewSection::findSectionPlaneIntersections(), Path::Toolpath::getCycleTime(), TechDrawGui::QGEPath::getDeltasFromLeader(), TechDraw::DrawViewDimension::getDimValue(), TechDraw::DrawProjGroup::getDirsFromFront(), TechDraw::DrawViewDimension::getFormatedValue(), TechDraw::DrawLeaderLine::getKinkPoint(), Attacher::AttachEnginePy::getModeInfo(), TechDrawGui::DrawGuiUtil::getProjDirFromFace(), TechDraw::DrawViewPart::getProjectionCS(), Attacher::AttachEnginePy::getRefTypeInfo(), TechDraw::DrawViewPart::getSourceShape(), TechDraw::DrawViewPart::getSourceShapeFused(), TechDraw::DrawLeaderLine::getTailPoint(), TechDraw::DrawLeaderLine::getTileOrigin(), AttacherGui::getUIStrings(), TechDraw::DrawProjGroupItem::getViewAxis(), TechDraw::DrawProjGroup::getViewIndex(), TechDrawGui::QGILeaderLine::getWayPointsFromFeature(), Gui::View3DInventorViewer::imageFromFramebuffer(), Gui::View3DInventorViewer::init(), TechDrawGui::TaskGeomHatch::initUi(), Sketcher::SketchObject::isCarbonCopyAllowed(), Sketcher::SketchObject::isExternalAllowed(), TechDrawGui::QGIFace::lineSetToFillItems(), Mesh::MeshObject::load(), MeshCore::MeshInput::LoadAny(), Gui::Dialog::DlgCustomKeyboardImp::on_editShortcut_textChanged(), Gui::Dialog::DlgMacroExecuteImp::on_toolbarButton_clicked(), TechDraw::DrawViewSymbol::onChanged(), TechDraw::DrawViewDimension::onChanged(), App::Document::onChanged(), Import::ImpExpDxfRead::OnReadArc(), Import::ImpExpDxfRead::OnReadCircle(), Import::ImpExpDxfRead::OnReadEllipse(), Gui::GestureNavigationStyle::onSetRotationCenter(), TechDrawGui::QGILeaderLine::onSourceChange(), Gui::BitmapFactoryInst::pixmap(), TechDrawGui::MDIViewPage::printPdf(), App::Application::processCmdLineFiles(), App::Application::processFiles(), Gui::MayaGestureNavigationStyle::processSoEvent(), Base::ScriptFactorySingleton::ProduceScript(), Gui::PrefQuantitySpinBox::pushToHistory(), Gui::NS::GestureState::react(), Attacher::AttachEngine::readLinks(), TechDrawGui::TaskRichAnno::removeFeature(), App::PropertyPythonObject::Restore(), TechDraw::CosmeticEdge::Restore(), App::PropertyEnumeration::Restore(), TechDraw::CenterLine::Restore(), App::PropertyLink::Restore(), App::PropertyLinkSubList::Restore(), Fem::PropertyPostDataObject::RestoreDocFile(), Part::PropertyPartShape::RestoreDocFile(), TechDrawGui::QGIProjGroup::rotateView(), Gui::ConsoleWarningTask::run(), Gui::PythonDebugger::runFile(), TechDraw::CosmeticEdge::Save(), MeshCore::MeshOutput::SaveOBJ(), MeshCore::MeshOutput::SaveOFF(), TechDrawGui::MDIViewPage::saveSVG(), TechDraw::CenterLine::scaledGeometry(), TechDraw::DrawViewSection::sectionExec(), Gui::Application::setActiveDocument(), SketcherGui::ViewProviderSketch::setEdit(), Gui::PrefWidget::setParamGrpPath(), Sketcher::Sketch::solve(), TechDraw::LineGroup::split(), sPyWarning(), Gui::Application::sSendActiveView(), Gui::Application::sSendFocusView(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty(), TechDraw::DrawProjGroupItem::unsetupObject(), TechDraw::DrawPage::unsetupObject(), TechDrawGui::QGILeaderLine::updateView(), and TechDrawGui::QGIWeldSymbol::updateView().
Friends And Related Function Documentation
ConsoleOutput
friend class ConsoleOutput friend
Member Data Documentation
BufferSize
const unsigned int Base::ConsoleSingleton::BufferSize = 4024 static
Referenced by GCS::SolverReportingManager::LogToConsole().
connectionMode
ConnectionMode Base::ConsoleSingleton::connectionMode protected
Referenced by SetConnectionMode().
Methods
PyMethodDef ConsoleSingleton::Methods static
Initial value:
= {
    {"PrintMessage",         (PyCFunction) ConsoleSingleton::sPyMessage, METH_VARARGS,
     "PrintMessage(string) -- Print a message to the output"},
    {"PrintLog",             (PyCFunction) ConsoleSingleton::sPyLog, METH_VARARGS,
     "PrintLog(string) -- Print a log message to the output"},
    {"PrintError"  ,         (PyCFunction) ConsoleSingleton::sPyError, METH_VARARGS,
     "PrintError(string) -- Print an error message to the output"},
    {"PrintWarning",         (PyCFunction) ConsoleSingleton::sPyWarning, METH_VARARGS,
     "PrintWarning -- Print a warning to the output"},
    {"SetStatus",            (PyCFunction) ConsoleSingleton::sPySetStatus, METH_VARARGS,
     "Set the status for either Log, Msg, Wrn or Error for an observer"},
    {"GetStatus",            (PyCFunction) ConsoleSingleton::sPyGetStatus, METH_VARARGS,
     "Get the status for either Log, Msg, Wrn or Error for an observer"},
    {NULL, NULL, 0, NULL}
}
The documentation for this class was generated from the following files:
src/Base/Console.h
src/Base/Console.cpp