FreeCAD: TechDrawGui::TaskCL2Lines Class Reference
TechDrawGui::TaskCL2Lines Class Reference
#include <TaskCenterLine.h>
Public Member Functions
virtual bool accept ()
virtual bool reject ()
TaskCL2Lines (TaskCenterLine *tcl)
~TaskCL2Lines ()
Protected Slots
void onFlipToggled (bool b)
Protected Member Functions
void changeEvent (QEvent *e)
void initUi (void)
Constructor & Destructor Documentation
TaskCL2Lines()
TaskCL2Lines::TaskCL2Lines (TechDrawGui::TaskCenterLine * tcl)
References DraftGeomUtils::connect(), initUi(), and onFlipToggled().
~TaskCL2Lines()
TaskCL2Lines::~TaskCL2Lines ()
Member Function Documentation
accept()
bool TaskCL2Lines::accept (void) virtual
References Base::Console(), and Base::ConsoleSingleton::Message().
changeEvent()
void TaskCL2Lines::changeEvent (QEvent * e) protected
initUi()
void TaskCL2Lines::initUi (void) protected
Referenced by TaskCL2Lines().
onFlipToggled
void TaskCL2Lines::onFlipToggled (bool b) protected slot
References Base::Console(), Base::ConsoleSingleton::Message(), and TechDrawGui::TaskCenterLine::setFlipped().
Referenced by TaskCL2Lines().
reject()
bool TaskCL2Lines::reject (void) virtual
References Base::Console(), and Base::ConsoleSingleton::Message().
The documentation for this class was generated from the following files:
src/Mod/TechDraw/Gui/TaskCenterLine.h
src/Mod/TechDraw/Gui/TaskCenterLine.cpp