FreeCAD: draftguitools.gui_edit_part_objects Namespace Reference
draftguitools.gui_edit_part_objects Namespace Reference
Functions
def get_supported_part_objects ()
def getPartBoxPts (obj)
def getPartConePts (obj)
def getPartCylinderPts (obj)
def getPartLinePts (obj)
def getPartSpherePts (obj)
def updatePartBox (obj, nodeIndex, v)
def updatePartCone (obj, nodeIndex, v)
def updatePartCylinder (obj, nodeIndex, v)
def updatePartLine (obj, nodeIndex, v)
def updatePartSphere (obj, nodeIndex, v)
Function Documentation
get_supported_part_objects()
def draftguitools.gui_edit_part_objects.get_supported_part_objects ()
getPartBoxPts()
def draftguitools.gui_edit_part_objects.getPartBoxPts (obj)
getPartConePts()
def draftguitools.gui_edit_part_objects.getPartConePts (obj)
getPartCylinderPts()
def draftguitools.gui_edit_part_objects.getPartCylinderPts (obj)
getPartLinePts()
def draftguitools.gui_edit_part_objects.getPartLinePts (obj)
getPartSpherePts()
def draftguitools.gui_edit_part_objects.getPartSpherePts (obj)
updatePartBox()
def draftguitools.gui_edit_part_objects.updatePartBox (obj, nodeIndex, v)
References DraftVecUtils.project().
updatePartCone()
def draftguitools.gui_edit_part_objects.updatePartCone (obj, nodeIndex, v)
References DraftVecUtils.project().
updatePartCylinder()
def draftguitools.gui_edit_part_objects.updatePartCylinder (obj, nodeIndex, v)
References DraftVecUtils.project().
updatePartLine()
def draftguitools.gui_edit_part_objects.updatePartLine (obj, nodeIndex, v)
updatePartSphere()
def draftguitools.gui_edit_part_objects.updatePartSphere (obj, nodeIndex, v)