FreeCAD: Sketcher::ExternalGeometryExtension Class Reference
Sketcher::ExternalGeometryExtension Class Reference
#include <ExternalGeometryExtension.h>
Public Types
enum Flag {
Defining = 0, Frozen = 1, Detached = 2, Missing = 3,
Sync = 4, NumFlags
}
Public Member Functions
virtual std::unique_ptr< Part::GeometryExtension > copy (void) const override
ExternalGeometryExtension ()=default
size_t flagSize () const
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
const std::string & getRef () const
bool isClear () const
virtual void Restore (Base::XMLReader &) override
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const override
This method is used to save properties to an XML document.
void setFlag (int flag, bool v=true)
void setRef (const std::string &ref)
bool testFlag (int flag) const
virtual ~ExternalGeometryExtension () override=default
Public Member Functions inherited from Part::GeometryExtension
const std::string & getName () const
void setName (const std::string &str)
virtual ~GeometryExtension ()=default
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Attributes
constexpr static std::array< const char *, NumFlags > flag2str {{ "Defining", "Frozen", "Detached","Missing", "Sync" }}
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from Part::GeometryExtension
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
void restoreNameAttribute (Base::XMLReader &)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Member Enumeration Documentation
Flag
enum Sketcher::ExternalGeometryExtension::Flag
Enumerator
Defining
Frozen
Detached
Missing
Sync
NumFlags
Constructor & Destructor Documentation
ExternalGeometryExtension()
Sketcher::ExternalGeometryExtension::ExternalGeometryExtension () default
Referenced by getPyObject().
~ExternalGeometryExtension()
virtual Sketcher::ExternalGeometryExtension::~ExternalGeometryExtension () override virtual default
Member Function Documentation
copy()
std::unique_ptr< Part::GeometryExtension > ExternalGeometryExtension::copy (void) const override virtual
Implements Part::GeometryExtension.
References Part::GeometryExtension::getName().
flagSize()
size_t Sketcher::ExternalGeometryExtension::flagSize () const
getMemSize()
unsigned int ExternalGeometryExtension::getMemSize (void) const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Part::GeometryExtension.
getPyObject()
PyObject * ExternalGeometryExtension::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
References ExternalGeometryExtension().
getRef()
const std::string& Sketcher::ExternalGeometryExtension::getRef () const
Referenced by Sketcher::ExternalGeometryExtensionPy::representation().
isClear()
bool Sketcher::ExternalGeometryExtension::isClear () const
Restore()
void ExternalGeometryExtension::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Part::GeometryExtension.
References Base::XMLReader::getAttribute(), and Part::GeometryExtension::restoreNameAttribute().
Save()
void ExternalGeometryExtension::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Part::GeometryExtension.
References Part::GeometryExtension::getName(), Base::Type::getName(), Base::Persistence::getTypeId(), Base::Writer::ind(), and Base::Writer::Stream().
setFlag()
void Sketcher::ExternalGeometryExtension::setFlag (int flag, bool v = true)
Referenced by Sketcher::ExternalGeometryExtensionPy::setFlag().
setRef()
void Sketcher::ExternalGeometryExtension::setRef (const std::string & ref)
Referenced by Sketcher::ExternalGeometryExtensionPy::setRef().
testFlag()
bool Sketcher::ExternalGeometryExtension::testFlag (int flag) const
Member Data Documentation
flag2str
constexpr std::array< const char *, ExternalGeometryExtension::NumFlags > ExternalGeometryExtension::flag2str {{ "Defining", "Frozen", "Detached","Missing", "Sync" }} static constexpr
Referenced by Sketcher::ExternalGeometryExtensionPy::representation().
The documentation for this class was generated from the following files:
src/Mod/Sketcher/App/ExternalGeometryExtension.h
src/Mod/Sketcher/App/ExternalGeometryExtension.cpp