FreeCAD: TestDraft.DraftTest Class Reference
TestDraft.DraftTest Class Reference
Public Member Functions
def setUp (self)
def tearDown (self)
def testArc (self)
def testBSpline (self)
def testCircle (self)
def testCloneOfPart (self)
def testCopy (self)
def testDimension (self)
def testEllipse (self)
def testLine (self)
def testMove (self)
def testOffset (self)
def testPivy (self)
def testPoint (self)
def testPolygon (self)
def testRectangle (self)
def testRotate (self)
def testText (self)
def testWire (self)
Member Function Documentation
setUp()
def TestDraft.DraftTest.setUp (self)
tearDown()
def TestDraft.DraftTest.tearDown (self)
testArc()
def TestDraft.DraftTest.testArc (self)
References Draft.makeCircle().
testBSpline()
def TestDraft.DraftTest.testBSpline (self)
References Draft.makeBSpline().
testCircle()
def TestDraft.DraftTest.testCircle (self)
References Draft.makeCircle().
testCloneOfPart()
def TestDraft.DraftTest.testCloneOfPart (self)
References Draft.clone().
testCopy()
def TestDraft.DraftTest.testCopy (self)
References Draft.makeLine(), and Draft.move().
testDimension()
def TestDraft.DraftTest.testDimension (self)
References Draft.makeDimension().
testEllipse()
def TestDraft.DraftTest.testEllipse (self)
References Draft.makeEllipse().
testLine()
def TestDraft.DraftTest.testLine (self)
References Draft.makeLine().
testMove()
def TestDraft.DraftTest.testMove (self)
References Draft.makeLine(), and Draft.move().
testOffset()
def TestDraft.DraftTest.testOffset (self)
References Draft.makeRectangle(), and Draft.offset().
testPivy()
def TestDraft.DraftTest.testPivy (self)
testPoint()
def TestDraft.DraftTest.testPoint (self)
References Draft.makePoint().
testPolygon()
def TestDraft.DraftTest.testPolygon (self)
References Draft.makePolygon().
testRectangle()
def TestDraft.DraftTest.testRectangle (self)
References Draft.makeRectangle().
testRotate()
def TestDraft.DraftTest.testRotate (self)
References Draft.makeLine(), and Draft.rotate().
testText()
def TestDraft.DraftTest.testText (self)
References Draft.makeText().
testWire()
def TestDraft.DraftTest.testWire (self)
References Draft.makeWire().
The documentation for this class was generated from the following file:
src/Mod/Draft/TestDraft.py