FreeCAD: DraftLayer Namespace Reference
DraftLayer Namespace Reference
Classes
class CommandLayer
class Layer
class LayerContainer
class ViewProviderLayer
class ViewProviderLayerContainer
Functions
def getLayerContainer ()
def makeLayer (name=None, linecolor=None, drawstyle=None, shapecolor=None, transparency=None)
def QT_TRANSLATE_NOOP (ctx, txt)
def translate (ctx, txt)
Function Documentation
getLayerContainer()
def DraftLayer.getLayerContainer ()
getLayerContainer(): returns a group object to put layers in
Referenced by makeLayer().
makeLayer()
def DraftLayer.makeLayer (name = None, linecolor = None, drawstyle = None, shapecolor = None, transparency = None)
makeLayer([name,linecolor,drawstyle,shapecolor,transparency]):
   creates a Layer object in the active document
References getLayerContainer().
QT_TRANSLATE_NOOP()
def DraftLayer.QT_TRANSLATE_NOOP (ctx, txt)
Referenced by DraftLayer.CommandLayer.GetResources(), and DraftLayer.Layer.setProperties().
translate()
def DraftLayer.translate (ctx, txt)