FreeCAD: ply.yacc Namespace Reference
ply.yacc Namespace Reference
Classes
class Grammar
class GrammarError
class LALRError
class LRGeneratedTable
class LRItem
class LRParser
class LRTable
class MiniProduction
class NullLogger
class ParserReflect
class PlyLogger
class Production
class VersionError
class YaccError
class YaccProduction
class YaccSymbol
Functions
def digraph (X, R, FP)
def format_result (r)
def format_stack_entry (r)
def func_code (f)
def get_caller_module_dict (levels)
def load_ply_lex ()
def parse_grammar (doc, file, line)
def rightmost_terminal (symbols, terminals)
def traverse (x, N, stack, F, X, R, FP)
def yacc (method='LALR', debug=yaccdebug, module=None, tabmodule=tab_module, start=None, check_recursion=1, optimize=0, write_tables=1, debugfile=debug_file, outputdir='', debuglog=None, errorlog=None, picklefile=None)
Variables
debug_file
default_lr
error_count
MAXINT
pickle_protocol
resultlimit
tab_module
yaccdebug
yaccdevel
Function Documentation
digraph()
def ply.yacc.digraph (X, R, FP)
References ply.yacc.traverse().
Referenced by ply.yacc.LRGeneratedTable.compute_follow_sets(), and ply.yacc.LRGeneratedTable.compute_read_sets().
format_result()
def ply.yacc.format_result (r)
format_stack_entry()
def ply.yacc.format_stack_entry (r)
func_code()
def ply.yacc.func_code (f)
Referenced by ply.yacc.ParserReflect.get_pfunctions(), ply.yacc.ParserReflect.validate_error_func(), and ply.yacc.ParserReflect.validate_pfunctions().
get_caller_module_dict()
def ply.yacc.get_caller_module_dict (levels)
Referenced by ply.yacc.yacc().
load_ply_lex()
def ply.yacc.load_ply_lex ()
Referenced by ply.yacc.LRParser.parsedebug(), ply.yacc.LRParser.parseopt(), and ply.yacc.LRParser.parseopt_notrack().
parse_grammar()
def ply.yacc.parse_grammar (doc, file, line)
Referenced by ply.yacc.ParserReflect.validate_pfunctions().
rightmost_terminal()
def ply.yacc.rightmost_terminal (symbols, terminals)
Referenced by ply.yacc.Grammar.add_production().
traverse()
def ply.yacc.traverse (x, N, stack, F, X, R, FP)
Referenced by ply.yacc.digraph().
yacc()
def ply.yacc.yacc (method = 'LALR', debug = yaccdebug, module = None, tabmodule = tab_module, start = None, check_recursion = 1, optimize = 0, write_tables = 1, debugfile = debug_file, outputdir = '', debuglog = None, errorlog = None, picklefile = None)
References ply.yacc.get_caller_module_dict().
Referenced by ply.yacc.ParserReflect.validate_pfunctions().
Variable Documentation
debug_file
ply.yacc.debug_file
default_lr
ply.yacc.default_lr
error_count
ply.yacc.error_count
MAXINT
ply.yacc.MAXINT
pickle_protocol
ply.yacc.pickle_protocol
resultlimit
ply.yacc.resultlimit
tab_module
ply.yacc.tab_module
yaccdebug
ply.yacc.yaccdebug
yaccdevel
ply.yacc.yaccdevel