FreeCAD: draftfunctions.rotate Namespace Reference
draftfunctions.rotate Namespace Reference
Functions
def copy_rotated_edge (object, edge_index, angle, center, axis)
def copy_rotated_edges (arguments)
def rotate (objectslist, angle, center=App.Vector(0, 0, 0), axis=App.Vector(0, 0, 1), copy=False)
def rotate_edge (object, edge_index, angle, center, axis)
def rotate_vector_from_center (vector, angle, axis, center)
def rotate_vertex (object, vertex_index, angle, center, axis)
Variables
def copyRotatedEdges = copy_rotated_edges
def rotateEdge = rotate_edge
def rotateVectorFromCenter = rotate_vector_from_center
def rotateVertex = rotate_vertex
Function Documentation
copy_rotated_edge()
def draftfunctions.rotate.copy_rotated_edge (object, edge_index, angle, center, axis)
Needed for SubObjects modifiers.
Implemented by Dion Moult during 0.19 dev cycle (works only with Draft Wire).
References draftfunctions.rotate.rotate_vector_from_center().
Referenced by draftfunctions.rotate.copy_rotated_edges().
copy_rotated_edges()
def draftfunctions.rotate.copy_rotated_edges (arguments)
Needed for SubObjects modifiers.
Implemented by Dion Moult during 0.19 dev cycle (works only with Draft Wire).
References draftfunctions.rotate.copy_rotated_edge().
rotate()
def draftfunctions.rotate.rotate (objectslist, angle, center = App.Vector(0,0,0), axis = App.Vector(0,0,1), copy = False)
rotate(objects,angle,[center,axis,copy])
Rotates the objects contained in objects (that can be a list of objects
or an object) of the given angle (in degrees) around the center, using
axis as a rotation axis.
Parameters
----------
objectlist : list
angle : list
center : Base.Vector
axis : Base.Vector
    If axis is omitted, the rotation will be around the vertical Z axis.
copy : bool
    If copy is True, the actual objects are not moved, but copies
    are created instead.
Return
----------
The objects (or their copies) are returned.
References DraftVecUtils.rotate(), and DraftVecUtils.tup().
rotate_edge()
def draftfunctions.rotate.rotate_edge (object, edge_index, angle, center, axis)
Needed for SubObjects modifiers.
Implemented by Dion Moult during 0.19 dev cycle (works only with Draft Wire).
References draftfunctions.rotate.rotateVertex.
rotate_vector_from_center()
def draftfunctions.rotate.rotate_vector_from_center (vector, angle, axis, center)
Needed for SubObjects modifiers.
Implemented by Dion Moult during 0.19 dev cycle (works only with Draft Wire).
References DraftVecUtils.rotate().
Referenced by draftfunctions.rotate.copy_rotated_edge(), and draftfunctions.rotate.rotate_vertex().
rotate_vertex()
def draftfunctions.rotate.rotate_vertex (object, vertex_index, angle, center, axis)
Needed for SubObjects modifiers.
Implemented by Dion Moult during 0.19 dev cycle (works only with Draft Wire).
References draftfunctions.rotate.rotate_vector_from_center().
Variable Documentation
copyRotatedEdges
def draftfunctions.rotate.copyRotatedEdges = copy_rotated_edges
rotateEdge
def draftfunctions.rotate.rotateEdge = rotate_edge
rotateVectorFromCenter
def draftfunctions.rotate.rotateVectorFromCenter = rotate_vector_from_center
rotateVertex
def draftfunctions.rotate.rotateVertex = rotate_vertex
Referenced by draftfunctions.rotate.rotate_edge().