FreeCAD: femguiobjects.ViewProviderFemConstraint.ViewProxy Class Reference
femguiobjects.ViewProviderFemConstraint.ViewProxy Class Reference
Public Member Functions
def attach (self, vobj)
def doubleClicked (self, vobj)
def getDefaultDisplayMode (self)
def getDisplayModes (self, obj)
def setDisplayMode (self, mode)
def setEdit (self, vobj, mode=0)
Detailed Description
Proxy View Provider for Pythons base constraint.
Member Function Documentation
attach()
def femguiobjects.ViewProviderFemConstraint.ViewProxy.attach (self, vobj)
doubleClicked()
def femguiobjects.ViewProviderFemConstraint.ViewProxy.doubleClicked (self, vobj)
getDefaultDisplayMode()
def femguiobjects.ViewProviderFemConstraint.ViewProxy.getDefaultDisplayMode (self)
getDisplayModes()
def femguiobjects.ViewProviderFemConstraint.ViewProxy.getDisplayModes (self, obj)
setDisplayMode()
def femguiobjects.ViewProviderFemConstraint.ViewProxy.setDisplayMode (self, mode)
setEdit()
def femguiobjects.ViewProviderFemConstraint.ViewProxy.setEdit (self, vobj, mode = 0)
Referenced by PathScripts.PathSetupSheetGui.ViewProvider.doubleClicked(), Spreadsheet_legacy.ViewProviderSpreadsheet.doubleClicked(), ArchSchedule.CommandArchSchedule.IsActive(), ArchAxis.CommandArchGrid.IsActive(), PathScripts.PathIconViewProvider.ViewProvider.setupContextMenu(), PathScripts.PathToolControllerGui.ViewProvider.setupContextMenu(), PathScripts.PathOpGui.ViewProvider.setupContextMenu(), and PathScripts.PathJobGui.ViewProvider.setupContextMenu().
The documentation for this class was generated from the following file:
src/Mod/Fem/femguiobjects/ViewProviderFemConstraint.py