FreeCAD: femexamples.ccx_cantilever_std Namespace Reference
femexamples.ccx_cantilever_std Namespace Reference
Functions
def init_doc (doc=None)
def setup_cantileverbase (doc=None, solvertype="ccxtools")
def setup_cantileverfaceload (doc=None, solvertype="ccxtools")
def setup_cantileverhexa20faceload (doc=None, solvertype="ccxtools")
def setup_cantilevernodeload (doc=None, solvertype="ccxtools")
def setup_cantileverprescribeddisplacement (doc=None, solvertype="ccxtools")
Variables
mesh_name
Function Documentation
init_doc()
def femexamples.ccx_cantilever_std.init_doc (doc = None)
Referenced by femexamples.ccx_cantilever_std.setup_cantileverbase().
setup_cantileverbase()
def femexamples.ccx_cantilever_std.setup_cantileverbase (doc = None, solvertype = "ccxtools")
References femexamples.ccx_cantilever_std.init_doc(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeSolverCalculix(), ObjectsFem.makeSolverCalculixCcxTools(), ObjectsFem.makeSolverElmer(), and ObjectsFem.makeSolverZ88().
Referenced by femexamples.ccx_cantilever_std.setup_cantileverfaceload(), femexamples.ccx_cantilever_std.setup_cantilevernodeload(), and femexamples.ccx_cantilever_std.setup_cantileverprescribeddisplacement().
setup_cantileverfaceload()
def femexamples.ccx_cantilever_std.setup_cantileverfaceload (doc = None, solvertype = "ccxtools")
References ObjectsFem.makeConstraintForce(), and femexamples.ccx_cantilever_std.setup_cantileverbase().
Referenced by femexamples.ccx_cantilever_std.setup_cantileverhexa20faceload().
setup_cantileverhexa20faceload()
def femexamples.ccx_cantilever_std.setup_cantileverhexa20faceload (doc = None, solvertype = "ccxtools")
References femexamples.ccx_cantilever_std.setup_cantileverfaceload().
setup_cantilevernodeload()
def femexamples.ccx_cantilever_std.setup_cantilevernodeload (doc = None, solvertype = "ccxtools")
References ObjectsFem.makeConstraintForce(), and femexamples.ccx_cantilever_std.setup_cantileverbase().
setup_cantileverprescribeddisplacement()
def femexamples.ccx_cantilever_std.setup_cantileverprescribeddisplacement (doc = None, solvertype = "ccxtools")
References ObjectsFem.makeConstraintDisplacement(), and femexamples.ccx_cantilever_std.setup_cantileverbase().
Variable Documentation
mesh_name
femexamples.ccx_cantilever_std.mesh_name