FreeCAD: TechDrawGui::DlgPrefsTechDraw2Imp Class Reference
TechDrawGui::DlgPrefsTechDraw2Imp Class Reference
#include <DlgPrefsTechDraw2Imp.h>
Public Member Functions
DlgPrefsTechDraw2Imp (QWidget *parent=0)
~DlgPrefsTechDraw2Imp ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=0)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Constructor & Destructor Documentation
DlgPrefsTechDraw2Imp()
DlgPrefsTechDraw2Imp::DlgPrefsTechDraw2Imp (QWidget * parent = 0)
References Base::Unit::Length.
~DlgPrefsTechDraw2Imp()
DlgPrefsTechDraw2Imp::~DlgPrefsTechDraw2Imp ()
Member Function Documentation
changeEvent()
void DlgPrefsTechDraw2Imp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References loadSettings(), and saveSettings().
loadSettings()
void DlgPrefsTechDraw2Imp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
Referenced by changeEvent().
saveSettings()
void DlgPrefsTechDraw2Imp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
Referenced by changeEvent().
The documentation for this class was generated from the following files:
src/Mod/TechDraw/Gui/DlgPrefsTechDraw2Imp.h
src/Mod/TechDraw/Gui/DlgPrefsTechDraw2Imp.cpp