FreeCAD: draftgeoutils.faces Namespace Reference
draftgeoutils.faces Namespace Reference
Functions
def bind (w1, w2)
def cleanFaces (shape)
def concatenate (shape)
def getBoundary (shape)
def isCoplanar (faces, tolerance=0)
def removeSplitter (shape)
Variables
Part = lz.LazyLoader("Part", globals(), "Part")
Function Documentation
bind()
def draftgeoutils.faces.bind (w1, w2)
Bind 2 wires by their endpoints and returns a face.
cleanFaces()
def draftgeoutils.faces.cleanFaces (shape)
Remove inner edges from coplanar faces.
References DraftVecUtils.find(), and draftgeoutils.faces.getBoundary().
concatenate()
def draftgeoutils.faces.concatenate (shape)
Turn several faces into one.
References draftgeoutils.faces.getBoundary().
getBoundary()
def draftgeoutils.faces.getBoundary (shape)
Return the boundary edges of a group of faces.
Referenced by draftgeoutils.faces.cleanFaces(), and draftgeoutils.faces.concatenate().
isCoplanar()
def draftgeoutils.faces.isCoplanar (faces, tolerance = 0)
Return True if all faces in the given list are coplanar.
Tolerance is the maximum deviation to be considered coplanar.
References DraftVecUtils.precision(), and DraftVecUtils.project().
removeSplitter()
def draftgeoutils.faces.removeSplitter (shape)
Return a face from removing the splitter in a list of faces.
This is an alternative, shared edge-based version of Part.removeSplitter.
Returns a face, or `None` if the operation failed.
Variable Documentation
Part
draftgeoutils.faces.Part = lz.LazyLoader("Part", globals(), "Part")