FreeCAD: Part::ToroidPy Class Reference
Part::ToroidPy Class Reference
The python export class for GeomToroid.
#include <ToroidPy.h>
Public Types
typedef GeomToroid * PointerType
Public Types inherited from Part::GeometrySurfacePy
typedef GeomSurface * PointerType
Public Types inherited from Part::GeometryPy
typedef Geometry * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
ToroidPy (GeomToroid *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Part::GeometrySurfacePy
GeometrySurfacePy (GeomSurface *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * isUmbillic (PyObject *args)
implementer for the isUmbillic() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * curvatureDirections (PyObject *args)
implementer for the curvatureDirections() method
PyObject * bounds (PyObject *args)
implementer for the bounds() method
PyObject * isPlanar (PyObject *args)
implementer for the isPlanar() method
PyObject * uIso (PyObject *args)
implementer for the uIso() method
PyObject * vIso (PyObject *args)
implementer for the vIso() method
PyObject * isUPeriodic (PyObject *args)
implementer for the isUPeriodic() method
PyObject * isVPeriodic (PyObject *args)
implementer for the isVPeriodic() method
PyObject * isUClosed (PyObject *args)
implementer for the isUClosed() method
PyObject * isVClosed (PyObject *args)
implementer for the isVClosed() method
PyObject * UPeriod (PyObject *args)
implementer for the UPeriod() method
PyObject * VPeriod (PyObject *args)
implementer for the VPeriod() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * toBSpline (PyObject *args)
implementer for the toBSpline() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * intersectSS (PyObject *args)
implementer for the intersectSS() method
Py::String getContinuity (void) const
getter for the Continuity attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomSurface * getGeomSurfacePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::GeometryPy
GeometryPy (Geometry *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
Py::Boolean getConstruction (void) const
getter for the Construction attribute
void setConstruction (Py::Boolean arg)
setter for the Construction attribute
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry * getGeometryPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometrySurfacePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_isUmbillic (PyObject *self, PyObject *args)
callback for the isUmbillic() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_curvatureDirections (PyObject *self, PyObject *args)
callback for the curvatureDirections() method
static PyObject * staticCallback_bounds (PyObject *self, PyObject *args)
callback for the bounds() method
static PyObject * staticCallback_isPlanar (PyObject *self, PyObject *args)
callback for the isPlanar() method
static PyObject * staticCallback_uIso (PyObject *self, PyObject *args)
callback for the uIso() method
static PyObject * staticCallback_vIso (PyObject *self, PyObject *args)
callback for the vIso() method
static PyObject * staticCallback_isUPeriodic (PyObject *self, PyObject *args)
callback for the isUPeriodic() method
static PyObject * staticCallback_isVPeriodic (PyObject *self, PyObject *args)
callback for the isVPeriodic() method
static PyObject * staticCallback_isUClosed (PyObject *self, PyObject *args)
callback for the isUClosed() method
static PyObject * staticCallback_isVClosed (PyObject *self, PyObject *args)
callback for the isVClosed() method
static PyObject * staticCallback_UPeriod (PyObject *self, PyObject *args)
callback for the UPeriod() method
static PyObject * staticCallback_VPeriod (PyObject *self, PyObject *args)
callback for the VPeriod() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args)
callback for the toBSpline() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_intersectSS (PyObject *self, PyObject *args)
callback for the intersectSS() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
Static Public Member Functions inherited from Part::GeometryPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
static PyObject * staticCallback_getConstruction (PyObject *self, void *closure)
getter callback for the Construction attribute
static int staticCallback_setConstruction (PyObject *self, PyObject *value, void *closure)
setter callback for the Construction attribute
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of ToroidPy.
static PyMethodDef Methods []
Methods structure of ToroidPy.
static PyTypeObject Type
Type structure of ToroidPy.
Static Public Attributes inherited from Part::GeometrySurfacePy
static PyGetSetDef GetterSetter []
Attribute structure of GeometrySurfacePy.
static PyMethodDef Methods []
Methods structure of GeometrySurfacePy.
static PyTypeObject Type
Type structure of GeometrySurfacePy.
Static Public Attributes inherited from Part::GeometryPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryPy.
static PyMethodDef Methods []
Methods structure of GeometryPy.
static PyTypeObject Type
Type structure of GeometryPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~ToroidPy ()
Protected Member Functions inherited from Part::GeometrySurfacePy
~GeometrySurfacePy ()
Protected Member Functions inherited from Part::GeometryPy
~GeometryPy ()
Protected Member Functions inherited from Base::PyObjectBase
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * uIso (PyObject *args)
implementer for the uIso() method
PyObject * vIso (PyObject *args)
implementer for the vIso() method
static PyObject * staticCallback_uIso (PyObject *self, PyObject *args)
callback for the uIso() method
static PyObject * staticCallback_vIso (PyObject *self, PyObject *args)
callback for the vIso() method
callbacks and implementers for the python object attributes
Py::Float getMajorRadius (void) const
getter for the MajorRadius attribute
void setMajorRadius (Py::Float arg)
setter for the MajorRadius attribute
Py::Float getMinorRadius (void) const
getter for the MinorRadius attribute
void setMinorRadius (Py::Float arg)
setter for the MinorRadius attribute
Py::Object getCenter (void) const
getter for the Center attribute
void setCenter (Py::Object arg)
setter for the Center attribute
Py::Object getAxis (void) const
getter for the Axis attribute
void setAxis (Py::Object arg)
setter for the Axis attribute
Py::Float getArea (void) const
getter for the Area attribute
Py::Float getVolume (void) const
getter for the Volume attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomToroid * getGeomToroidPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getMajorRadius (PyObject *self, void *closure)
getter callback for the MajorRadius attribute
static int staticCallback_setMajorRadius (PyObject *self, PyObject *value, void *closure)
setter callback for the MajorRadius attribute
static PyObject * staticCallback_getMinorRadius (PyObject *self, void *closure)
getter callback for the MinorRadius attribute
static int staticCallback_setMinorRadius (PyObject *self, PyObject *value, void *closure)
setter callback for the MinorRadius attribute
static PyObject * staticCallback_getCenter (PyObject *self, void *closure)
getter callback for the Center attribute
static int staticCallback_setCenter (PyObject *self, PyObject *value, void *closure)
setter callback for the Center attribute
static PyObject * staticCallback_getAxis (PyObject *self, void *closure)
getter callback for the Axis attribute
static int staticCallback_setAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis attribute
static PyObject * staticCallback_getArea (PyObject *self, void *closure)
getter callback for the Area attribute
static int staticCallback_setArea (PyObject *self, PyObject *value, void *closure)
setter callback for the Area attribute
static PyObject * staticCallback_getVolume (PyObject *self, void *closure)
getter callback for the Volume attribute
static int staticCallback_setVolume (PyObject *self, PyObject *value, void *closure)
setter callback for the Volume attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomToroid.
Member Typedef Documentation
PointerType
typedef GeomToroid* Part::ToroidPy::PointerType
Constructor & Destructor Documentation
~ToroidPy()
ToroidPy::~ToroidPy () protected
ToroidPy()
ToroidPy::ToroidPy (GeomToroid * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getArea()
Py::Float ToroidPy::getArea (void) const
getter for the Area attribute
References getGeomToroidPtr().
Referenced by staticCallback_getArea().
getAxis()
Py::Object ToroidPy::getAxis (void) const
getter for the Axis attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getAxis().
getCenter()
Py::Object ToroidPy::getCenter (void) const
getter for the Center attribute
References getGeomToroidPtr().
Referenced by staticCallback_getCenter().
getCustomAttributes()
PyObject * ToroidPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeomToroidPtr()
GeomToroid * ToroidPy::getGeomToroidPtr (void) const
getter for the object handled by this class
Referenced by getArea(), getCenter(), getMajorRadius(), getMinorRadius(), getVolume(), PyInit(), setCenter(), setMajorRadius(), setMinorRadius(), uIso(), and vIso().
getMajorRadius()
Py::Float ToroidPy::getMajorRadius (void) const
getter for the MajorRadius attribute
References getGeomToroidPtr().
Referenced by staticCallback_getMajorRadius().
getMinorRadius()
Py::Float ToroidPy::getMinorRadius (void) const
getter for the MinorRadius attribute
References getGeomToroidPtr().
Referenced by staticCallback_getMinorRadius().
GetType()
virtual PyTypeObject* Part::ToroidPy::GetType (void) virtual
Reimplemented from Part::GeometrySurfacePy.
getVolume()
Py::Float ToroidPy::getVolume (void) const
getter for the Volume attribute
References getGeomToroidPtr().
Referenced by staticCallback_getVolume().
PyInit()
int ToroidPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometrySurfacePy.
References getGeomToroidPtr().
PyMake()
PyObject * ToroidPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References ToroidPy().
representation()
std::string ToroidPy::representation (void) const
Referenced by config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr2(), config_control_design.degenerate_pcurve::wr2(), automotive_design.pcurve::wr2(), and automotive_design.degenerate_pcurve::wr2().
setAxis()
void ToroidPy::setAxis (Py::Object arg)
setter for the Axis attribute
References Part::GeometryPy::getGeometryPtr(), Base::VectorPy::Type, and Part::GeometrySurfacePy::value().
Referenced by staticCallback_setAxis().
setCenter()
void ToroidPy::setCenter (Py::Object arg)
setter for the Center attribute
References getGeomToroidPtr(), Base::VectorPy::Type, Part::GeometrySurfacePy::value(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_setCenter().
setCustomAttributes()
int ToroidPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setMajorRadius()
void ToroidPy::setMajorRadius (Py::Float arg)
setter for the MajorRadius attribute
References getGeomToroidPtr().
Referenced by staticCallback_setMajorRadius().
setMinorRadius()
void ToroidPy::setMinorRadius (Py::Float arg)
setter for the MinorRadius attribute
References getGeomToroidPtr().
Referenced by staticCallback_setMinorRadius().
staticCallback_getArea()
PyObject * ToroidPy::staticCallback_getArea (PyObject * self, void * closure) static
getter callback for the Area attribute
References Base::BaseExceptionFreeCADError, getArea(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAxis()
PyObject * ToroidPy::staticCallback_getAxis (PyObject * self, void * closure) static
getter callback for the Axis attribute
References Base::BaseExceptionFreeCADError, getAxis(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCenter()
PyObject * ToroidPy::staticCallback_getCenter (PyObject * self, void * closure) static
getter callback for the Center attribute
References Base::BaseExceptionFreeCADError, getCenter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMajorRadius()
PyObject * ToroidPy::staticCallback_getMajorRadius (PyObject * self, void * closure) static
getter callback for the MajorRadius attribute
References Base::BaseExceptionFreeCADError, getMajorRadius(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMinorRadius()
PyObject * ToroidPy::staticCallback_getMinorRadius (PyObject * self, void * closure) static
getter callback for the MinorRadius attribute
References Base::BaseExceptionFreeCADError, getMinorRadius(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVolume()
PyObject * ToroidPy::staticCallback_getVolume (PyObject * self, void * closure) static
getter callback for the Volume attribute
References Base::BaseExceptionFreeCADError, getVolume(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setArea()
int ToroidPy::staticCallback_setArea (PyObject * self, PyObject * value, void * closure) static
setter callback for the Area attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setAxis()
int ToroidPy::staticCallback_setAxis (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAxis().
staticCallback_setCenter()
int ToroidPy::staticCallback_setCenter (PyObject * self, PyObject * value, void * closure) static
setter callback for the Center attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setCenter().
staticCallback_setMajorRadius()
int ToroidPy::staticCallback_setMajorRadius (PyObject * self, PyObject * value, void * closure) static
setter callback for the MajorRadius attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMajorRadius().
staticCallback_setMinorRadius()
int ToroidPy::staticCallback_setMinorRadius (PyObject * self, PyObject * value, void * closure) static
setter callback for the MinorRadius attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMinorRadius().
staticCallback_setVolume()
int ToroidPy::staticCallback_setVolume (PyObject * self, PyObject * value, void * closure) static
setter callback for the Volume attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_uIso()
PyObject * ToroidPy::staticCallback_uIso (PyObject * self, PyObject * args) static
callback for the uIso() method
References Base::BaseExceptionFreeCADError, Base::Console(), Base::ConsoleSingleton::Error(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and uIso().
staticCallback_vIso()
PyObject * ToroidPy::staticCallback_vIso (PyObject * self, PyObject * args) static
callback for the vIso() method
References Base::BaseExceptionFreeCADError, Base::Console(), Base::ConsoleSingleton::Error(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and vIso().
uIso()
PyObject * ToroidPy::uIso (PyObject * args)
implementer for the uIso() method
References getGeomToroidPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_uIso().
vIso()
PyObject * ToroidPy::vIso (PyObject * args)
implementer for the vIso() method
References getGeomToroidPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_vIso().
Member Data Documentation
GetterSetter
PyGetSetDef ToroidPy::GetterSetter static
Attribute structure of ToroidPy.
Methods
PyMethodDef ToroidPy::Methods static
Initial value:
= {
    {"uIso",
        reinterpret_cast<PyCFunction>( staticCallback_uIso ),
        METH_VARARGS,
        "Builds the U isoparametric circle of this toroid"
    },
    {"vIso",
        reinterpret_cast<PyCFunction>( staticCallback_vIso ),
        METH_VARARGS,
        "Builds the V isoparametric circle of this toroid"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of ToroidPy.
Type
PyTypeObject ToroidPy::Type static
Type structure of ToroidPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchSchedule.CommandArchSchedule::IsActive(), and ArchAxis.CommandArchGrid::IsActive().
The documentation for this class was generated from the following files:
build/webdoc/src/Mod/Part/App/ToroidPy.h
src/Mod/Part/App/ToroidPyImp.cpp
build/webdoc/src/Mod/Part/App/ToroidPy.cpp