FreeCAD: DraftGui Namespace Reference
DraftGui Namespace Reference
Workbenches » Python workbenches » Draft
GUI elements and utilities of the Draft workbench.
Classes
class DraftBaseWidget
class DraftDockWidget
class DraftLineEdit
class DraftTaskPanel
class DraftToolBar
class FacebinderTaskPanel
Functions
def displayExternal (internValue, decimals=None, dim='Length', showUnit=True, unit=None)
def getDefaultUnit (dim)
def makeFormatSpec (decimals=4, dim='Length')
Variables
draftToolBar
for debugging: else: msg = "TranslateWidget: Can not translate widget: {0} type: {1}\n".format(w.objectName(),w.metaObject().className()) FreeCAD.Console.PrintMessage(msg)
dictionary inCommandShortcuts
todo = draftutils.todo.ToDo
translate = draftutils.translate.translate
utf8_decode = draftutils.utils.utf8_decode
Detailed Description
GUI elements and utilities of the Draft workbench.
This module provides GUI tools for the Draft workbench, such as toolbars and task panels, and Qt-dependent utilities such as a delayed (todo) commit system
Function Documentation
displayExternal()
def DraftGui.displayExternal (internValue, decimals = None, dim = 'Length', showUnit = True, unit = None)
return an internal value (ie mm) Length or Angle converted for display according
to Units Schema in use. Unit can be used to force the value to express in a certain unit
Referenced by DraftGui.DraftToolBar.changeAngleValue(), DraftGui.DraftToolBar.displayPoint(), and DraftGui.DraftToolBar.setRadiusValue().
getDefaultUnit()
def DraftGui.getDefaultUnit (dim)
return default Unit of Measure for a Dimension based on user preference
Units Schema
Referenced by makeFormatSpec().
makeFormatSpec()
def DraftGui.makeFormatSpec (decimals = 4, dim = 'Length')
return a % format spec with specified decimals for a specified
dimension based on on user preference Units Schema
References getDefaultUnit().
Variable Documentation
draftToolBar
DraftGui.draftToolBar
for debugging: else: msg = "TranslateWidget: Can not translate widget: {0} type: {1}\n".format(w.objectName(),w.metaObject().className()) FreeCAD.Console.PrintMessage(msg)
inCommandShortcuts
dictionary DraftGui.inCommandShortcuts
Initial value:
 =  {
     "Relative":       [Draft.getParam("inCommandShortcutRelative", "R"),translate("draft","Relative"),             "isRelative"],
     "Continue":       [Draft.getParam("inCommandShortcutContinue", "T"),translate("draft","Continue"),             "continueCmd"],
     "Close":          [Draft.getParam("inCommandShortcutClose", "O"),translate("draft","Close"),                "closeButton"],
     "Copy":           [Draft.getParam("inCommandShortcutCopy", "P"),translate("draft","Copy"),                 "isCopy"],
     "SubelementMode": [Draft.getParam("inCommandShortcutSubelementMode", "D"),translate("draft","Subelement mode"), "isSubelementMode"],
     "Fill":           [Draft.getParam("inCommandShortcutFill", "L"),translate("draft","Fill"),                 "hasFill"],
     "Exit":           [Draft.getParam("inCommandShortcutExit", "A"),translate("draft","Exit"),                 "finishButton"],
     "Snap":           [Draft.getParam("inCommandShortcutSnap", "S"),translate("draft","Snap On/Off"),          None],
     "Increase":       [Draft.getParam("inCommandShortcutIncrease", "["),translate("draft","Increase snap radius"), None],
     "Decrease":       [Draft.getParam("inCommandShortcutDecrease", "]"),translate("draft","Decrease snap radius"), None],
     "RestrictX":      [Draft.getParam("inCommandShortcutRestrictX", "X"),translate("draft","Restrict X"),           None],
     "RestrictY":      [Draft.getParam("inCommandShortcutRestrictY", "Y"),translate("draft","Restrict Y"),           None],
     "RestrictZ":      [Draft.getParam("inCommandShortcutRestrictZ", "Z"),translate("draft","Restrict Z"),           None],
     "SelectEdge":     [Draft.getParam("inCommandShortcutSelectEdge", "E"),translate("draft","Select edge"),          "selectButton"],
     "AddHold":        [Draft.getParam("inCommandShortcutAddHold", "Q"),translate("draft","Add custom snap point"),None],
     "Length":         [Draft.getParam("inCommandShortcutLength", "H"),translate("draft","Length mode"),          "lengthValue"],
     "Wipe":           [Draft.getParam("inCommandShortcutWipe", "W"),translate("draft","Wipe"),                 "wipeButton"],
     "SetWP":          [Draft.getParam("inCommandShortcutSetWP", "U"),translate("draft","Set Working Plane"), "orientWPButton"],
     "CycleSnap":      [Draft.getParam("inCommandShortcutCycleSnap", "`"),translate("draft","Cycle snap object"), None],
     "NearSnap":       [Draft.getParam("inCommandShortcutNearSnap", "N"),translate("draft","Toggle near snap on/off"), None],
 }
todo
DraftGui.todo = draftutils.todo.ToDo
translate
DraftGui.translate = draftutils.translate.translate
utf8_decode
DraftGui.utf8_decode = draftutils.utils.utf8_decode
Referenced by DraftGui.DraftToolBar.validateFile().