FreeCAD: draftutils.init_tools Namespace Reference
draftutils.init_tools Namespace Reference
Functions
def get_draft_annotation_commands ()
def get_draft_array_commands ()
def get_draft_context_commands ()
def get_draft_drawing_commands ()
def get_draft_line_commands ()
def get_draft_modification_commands ()
def get_draft_small_commands ()
def get_draft_snap_commands ()
def get_draft_utility_commands ()
def init_draft_menus (workbench)
def init_draft_toolbars (workbench)
Function Documentation
get_draft_annotation_commands()
def draftutils.init_tools.get_draft_annotation_commands ()
Return the annotation commands list.
Referenced by draftutils.init_tools.init_draft_menus(), and draftutils.init_tools.init_draft_toolbars().
get_draft_array_commands()
def draftutils.init_tools.get_draft_array_commands ()
Return the array commands list.
Referenced by draftutils.init_tools.get_draft_modification_commands().
get_draft_context_commands()
def draftutils.init_tools.get_draft_context_commands ()
Return the context menu commands list.
Referenced by draftutils.init_tools.init_draft_menus().
get_draft_drawing_commands()
def draftutils.init_tools.get_draft_drawing_commands ()
Return the drawing commands list.
Referenced by draftutils.init_tools.init_draft_menus(), and draftutils.init_tools.init_draft_toolbars().
get_draft_line_commands()
def draftutils.init_tools.get_draft_line_commands ()
Return the line commands list.
get_draft_modification_commands()
def draftutils.init_tools.get_draft_modification_commands ()
Return the modification commands list.
References draftutils.init_tools.get_draft_array_commands().
Referenced by draftutils.init_tools.init_draft_menus(), and draftutils.init_tools.init_draft_toolbars().
get_draft_small_commands()
def draftutils.init_tools.get_draft_small_commands ()
Return a list with only some utilities.
get_draft_snap_commands()
def draftutils.init_tools.get_draft_snap_commands ()
Return the snapping commands list.
get_draft_utility_commands()
def draftutils.init_tools.get_draft_utility_commands ()
Return the utility commands list.
Referenced by draftutils.init_tools.init_draft_menus().
init_draft_menus()
def draftutils.init_tools.init_draft_menus (workbench)
Initialize the Draft menus.
Parameters
----------
workbench : Gui.Workbench
    The workbench class on which the commands have to be available.
    If called from within the `Initialize` method
    of a workbench class defined inside `InitGui.py`,
    it can be used as `setup_draft_menus(self)`.
References draftutils.init_tools.get_draft_annotation_commands(), draftutils.init_tools.get_draft_context_commands(), draftutils.init_tools.get_draft_drawing_commands(), draftutils.init_tools.get_draft_modification_commands(), and draftutils.init_tools.get_draft_utility_commands().
init_draft_toolbars()
def draftutils.init_tools.init_draft_toolbars (workbench)
Initialize the Draft toolbars.
Parameters
----------
workbench : Gui.Workbench
    The workbench class on which the commands have to be available.
    If called from within the `Initialize` method
    of a workbench class defined inside `InitGui.py`,
    it can be used as `setup_draft_toolbars(self)`.
References draftutils.init_tools.get_draft_annotation_commands(), draftutils.init_tools.get_draft_drawing_commands(), and draftutils.init_tools.get_draft_modification_commands().